<?php
declare(strict_types=1);
namespace Flint;
/**
 * @property-read array{'audience': string, 'delivery_selection'?: array{'amount_money': array{'amount': string, 'currency': string}|object, 'buyer_location'?: mixed, 'calculation_expires_at': string|\DateTimeInterface, 'checkout_session_id': string, 'choices': list<DeliverySelectionChoiceResourceInput|array<array-key, mixed>|\stdClass>, 'created_at': string|\DateTimeInterface, 'delivery_quote_id': string, 'delivery_quote_revision': string, 'delivery_selection_id': string, 'destination_address'?: array{'city'?: string, 'country'?: string, 'line1'?: string, 'line2'?: string, 'postal_code'?: string, 'state'?: string, ...}|object, 'eligibility_context_revision': string, 'expires_at': string|\DateTimeInterface, 'input_requirements': list<DeliveryInputRequirementInput|array<array-key, mixed>|\stdClass>, 'instructions'?: string, 'lifecycle_events'?: list<DeliverySelectionLifecycleEventResourceInput|array<array-key, mixed>|\stdClass>, 'lifecycle_updated_at': string|\DateTimeInterface, 'limiting_deadline_reason': string, 'order_id': string, 'private_data_status'?: string, 'recipient'?: array{'email'?: string, 'name'?: string, 'phone'?: string, ...}|object, 'redacted_at'?: string|\DateTimeInterface, 'status': string, ...}|object|null, 'mutable': bool, 'originating_checkout_session_id'?: string, 'source': string, ...}|object|array{'audience': string, 'delivery_selection'?: array{'amount_money': MoneyValueInput|array<array-key, mixed>|\stdClass, 'choices': list<BuyerDeliverySelectionChoiceResourceInput|array<array-key, mixed>|\stdClass>, 'delivery_quote_id': string, 'delivery_selection_id': string, 'destination_address'?: DeliveryAddressResourceInput|array<array-key, mixed>|\stdClass, 'expires_at': string|\DateTimeInterface, 'input_requirements': list<BuyerDeliveryInputRequirementResourceInput|array<array-key, mixed>|\stdClass>, 'recipient'?: DeliveryRecipientResourceInput|array<array-key, mixed>|\stdClass, 'status': string, ...}|object|null, 'mutable': bool, 'source': string, ...}|object $data
 * @property-read ResponseMetaInput|array<array-key, mixed>|\stdClass $meta
 * @property-read string $request_id
 * Presence-aware input; omitted fields throw when accessed. */
final class CheckoutEffectiveDeliverySelectionResponseInput extends Model {
    /** @param array{'data': array{'audience': string, 'delivery_selection'?: array{'amount_money': array{'amount': string, 'currency': string}|object, 'buyer_location'?: mixed, 'calculation_expires_at': string|\DateTimeInterface, 'checkout_session_id': string, 'choices': list<DeliverySelectionChoiceResourceInput|array<array-key, mixed>|\stdClass>, 'created_at': string|\DateTimeInterface, 'delivery_quote_id': string, 'delivery_quote_revision': string, 'delivery_selection_id': string, 'destination_address'?: array{'city'?: string, 'country'?: string, 'line1'?: string, 'line2'?: string, 'postal_code'?: string, 'state'?: string, ...}|object, 'eligibility_context_revision': string, 'expires_at': string|\DateTimeInterface, 'input_requirements': list<DeliveryInputRequirementInput|array<array-key, mixed>|\stdClass>, 'instructions'?: string, 'lifecycle_events'?: list<DeliverySelectionLifecycleEventResourceInput|array<array-key, mixed>|\stdClass>, 'lifecycle_updated_at': string|\DateTimeInterface, 'limiting_deadline_reason': string, 'order_id': string, 'private_data_status'?: string, 'recipient'?: array{'email'?: string, 'name'?: string, 'phone'?: string, ...}|object, 'redacted_at'?: string|\DateTimeInterface, 'status': string, ...}|object|null, 'mutable': bool, 'originating_checkout_session_id'?: string, 'source': string, ...}|object|array{'audience': string, 'delivery_selection'?: array{'amount_money': MoneyValueInput|array<array-key, mixed>|\stdClass, 'choices': list<BuyerDeliverySelectionChoiceResourceInput|array<array-key, mixed>|\stdClass>, 'delivery_quote_id': string, 'delivery_selection_id': string, 'destination_address'?: DeliveryAddressResourceInput|array<array-key, mixed>|\stdClass, 'expires_at': string|\DateTimeInterface, 'input_requirements': list<BuyerDeliveryInputRequirementResourceInput|array<array-key, mixed>|\stdClass>, 'recipient'?: DeliveryRecipientResourceInput|array<array-key, mixed>|\stdClass, 'status': string, ...}|object|null, 'mutable': bool, 'source': string, ...}|object, 'meta'?: ResponseMetaInput|array<array-key, mixed>|\stdClass, 'request_id'?: string, ...}|object $values */
    public function __construct(array|object $values = [], array $redactFields = []) { parent::__construct($values, [], false, $redactFields, ['constraints' => true] + SchemaRegistry::source()->model('CheckoutEffectiveDeliverySelectionResponseInput')); }
    /** @return array{'audience': string, 'delivery_selection'?: array{'amount_money': array{'amount': string, 'currency': string}|object, 'buyer_location'?: mixed, 'calculation_expires_at': string|\DateTimeInterface, 'checkout_session_id': string, 'choices': list<DeliverySelectionChoiceResourceInput|array<array-key, mixed>|\stdClass>, 'created_at': string|\DateTimeInterface, 'delivery_quote_id': string, 'delivery_quote_revision': string, 'delivery_selection_id': string, 'destination_address'?: array{'city'?: string, 'country'?: string, 'line1'?: string, 'line2'?: string, 'postal_code'?: string, 'state'?: string, ...}|object, 'eligibility_context_revision': string, 'expires_at': string|\DateTimeInterface, 'input_requirements': list<DeliveryInputRequirementInput|array<array-key, mixed>|\stdClass>, 'instructions'?: string, 'lifecycle_events'?: list<DeliverySelectionLifecycleEventResourceInput|array<array-key, mixed>|\stdClass>, 'lifecycle_updated_at': string|\DateTimeInterface, 'limiting_deadline_reason': string, 'order_id': string, 'private_data_status'?: string, 'recipient'?: array{'email'?: string, 'name'?: string, 'phone'?: string, ...}|object, 'redacted_at'?: string|\DateTimeInterface, 'status': string, ...}|object|null, 'mutable': bool, 'originating_checkout_session_id'?: string, 'source': string, ...}|object|array{'audience': string, 'delivery_selection'?: array{'amount_money': MoneyValueInput|array<array-key, mixed>|\stdClass, 'choices': list<BuyerDeliverySelectionChoiceResourceInput|array<array-key, mixed>|\stdClass>, 'delivery_quote_id': string, 'delivery_selection_id': string, 'destination_address'?: DeliveryAddressResourceInput|array<array-key, mixed>|\stdClass, 'expires_at': string|\DateTimeInterface, 'input_requirements': list<BuyerDeliveryInputRequirementResourceInput|array<array-key, mixed>|\stdClass>, 'recipient'?: DeliveryRecipientResourceInput|array<array-key, mixed>|\stdClass, 'status': string, ...}|object|null, 'mutable': bool, 'source': string, ...}|object
     * @throws SdkError When data is omitted; use hasData() or valueOrDefault().
     */
    public function getData(): mixed { return $this->get('data'); }
    public function hasData(): bool { return $this->has('data'); }
    /** @return ResponseMetaInput|array<array-key, mixed>|\stdClass
     * @throws SdkError When meta is omitted; use hasMeta() or valueOrDefault().
     */
    public function getMeta(): mixed { return $this->get('meta'); }
    public function hasMeta(): bool { return $this->has('meta'); }
    /** @return string
     * @throws SdkError When request_id is omitted; use hasRequestId() or valueOrDefault().
     */
    public function getRequestId(): string { return $this->get('request_id'); }
    public function hasRequestId(): bool { return $this->has('request_id'); }
}
