<?php
declare(strict_types=1);
namespace Flint;
final class CustomerDeletionRequestsResource {
    public function __construct(private readonly Runtime $runtime) {}
    /** Lists deletion requests across the selected merchant environment so a merchant can discover and review buyer-created requests.
     * @param array<array-key, mixed>|Model|null $params Flat body fields and query/header parameters; path arguments follow URL order.
     * @return CustomerDeletionRequestsListResponse200
     */
    public function list(array|Model|null $params = null, ?RequestOptions $options = null): CustomerDeletionRequestsListResponse200 { $input = []; $params = $params instanceof Model ? $params->toInputArray() : $params; $rest = $params ?? []; if ($rest && array_is_list($rest)) throw new SdkError('validation', 'Expected associative params', 'not_sent'); if (array_key_exists('status', $rest)) { $input['status'] = $rest['status']; unset($rest['status']); } if (array_key_exists('customer_id', $rest)) { $input['customer_id'] = $rest['customer_id']; unset($rest['customer_id']); } if (array_key_exists('page_size', $rest)) { $input['page_size'] = $rest['page_size']; unset($rest['page_size']); } if (array_key_exists('page_token', $rest)) { $input['page_token'] = $rest['page_token']; unset($rest['page_token']); } if (array_key_exists('X-Request-Id', $rest)) { $input['X-Request-Id'] = $rest['X-Request-Id']; unset($rest['X-Request-Id']); } if (array_key_exists('Flint-Version', $rest)) { $input['Flint-Version'] = $rest['Flint-Version']; unset($rest['Flint-Version']); } foreach ($rest as $name => $value) { if (array_key_exists($name, $input)) throw new SdkError('validation', 'Path values belong in positional arguments', 'not_sent'); $input[$name] = $value; } return SdkResponse::payload($this->runtime->request('listCustomerDeletionRequests', $input instanceof CustomerDeletionRequestsListInput ? $input->toInputArray() : (new CustomerDeletionRequestsListInput($input))->toInputArray(), $options), []); }
    /** @return SdkResponse<CustomerDeletionRequestsListResponse200> */
    public function listWithResponse(array|Model|null $params = null, ?RequestOptions $options = null): SdkResponse { $input = []; $params = $params instanceof Model ? $params->toInputArray() : $params; $rest = $params ?? []; if ($rest && array_is_list($rest)) throw new SdkError('validation', 'Expected associative params', 'not_sent'); if (array_key_exists('status', $rest)) { $input['status'] = $rest['status']; unset($rest['status']); } if (array_key_exists('customer_id', $rest)) { $input['customer_id'] = $rest['customer_id']; unset($rest['customer_id']); } if (array_key_exists('page_size', $rest)) { $input['page_size'] = $rest['page_size']; unset($rest['page_size']); } if (array_key_exists('page_token', $rest)) { $input['page_token'] = $rest['page_token']; unset($rest['page_token']); } if (array_key_exists('X-Request-Id', $rest)) { $input['X-Request-Id'] = $rest['X-Request-Id']; unset($rest['X-Request-Id']); } if (array_key_exists('Flint-Version', $rest)) { $input['Flint-Version'] = $rest['Flint-Version']; unset($rest['Flint-Version']); } foreach ($rest as $name => $value) { if (array_key_exists($name, $input)) throw new SdkError('validation', 'Path values belong in positional arguments', 'not_sent'); $input[$name] = $value; } $result = $this->runtime->request('listCustomerDeletionRequests', $input instanceof CustomerDeletionRequestsListInput ? $input->toInputArray() : (new CustomerDeletionRequestsListInput($input))->toInputArray(), $options); return new SdkResponse($result->data, $result->meta, $result->raw); }
    /** @return \Generator<int, CustomerDeletionRequestsListResponse200> */
    public function listPages(array|Model|null $params = null, ?RequestOptions $options = null): \Generator { $input = []; $params = $params instanceof Model ? $params->toInputArray() : $params; $rest = $params ?? []; if ($rest && array_is_list($rest)) throw new SdkError('validation', 'Expected associative params', 'not_sent'); if (array_key_exists('status', $rest)) { $input['status'] = $rest['status']; unset($rest['status']); } if (array_key_exists('customer_id', $rest)) { $input['customer_id'] = $rest['customer_id']; unset($rest['customer_id']); } if (array_key_exists('page_size', $rest)) { $input['page_size'] = $rest['page_size']; unset($rest['page_size']); } if (array_key_exists('page_token', $rest)) { $input['page_token'] = $rest['page_token']; unset($rest['page_token']); } if (array_key_exists('X-Request-Id', $rest)) { $input['X-Request-Id'] = $rest['X-Request-Id']; unset($rest['X-Request-Id']); } if (array_key_exists('Flint-Version', $rest)) { $input['Flint-Version'] = $rest['Flint-Version']; unset($rest['Flint-Version']); } foreach ($rest as $name => $value) { if (array_key_exists($name, $input)) throw new SdkError('validation', 'Path values belong in positional arguments', 'not_sent'); $input[$name] = $value; } return SdkResponse::payloadPages($this->runtime->pages('listCustomerDeletionRequests', $input instanceof CustomerDeletionRequestsListInput ? $input->toInputArray() : (new CustomerDeletionRequestsListInput($input))->toInputArray(), $options), []); }
    /** @return \Generator<int, SdkResponse<CustomerDeletionRequestsListResponse200>> */
    public function listPagesWithResponse(array|Model|null $params = null, ?RequestOptions $options = null): \Generator { $input = []; $params = $params instanceof Model ? $params->toInputArray() : $params; $rest = $params ?? []; if ($rest && array_is_list($rest)) throw new SdkError('validation', 'Expected associative params', 'not_sent'); if (array_key_exists('status', $rest)) { $input['status'] = $rest['status']; unset($rest['status']); } if (array_key_exists('customer_id', $rest)) { $input['customer_id'] = $rest['customer_id']; unset($rest['customer_id']); } if (array_key_exists('page_size', $rest)) { $input['page_size'] = $rest['page_size']; unset($rest['page_size']); } if (array_key_exists('page_token', $rest)) { $input['page_token'] = $rest['page_token']; unset($rest['page_token']); } if (array_key_exists('X-Request-Id', $rest)) { $input['X-Request-Id'] = $rest['X-Request-Id']; unset($rest['X-Request-Id']); } if (array_key_exists('Flint-Version', $rest)) { $input['Flint-Version'] = $rest['Flint-Version']; unset($rest['Flint-Version']); } foreach ($rest as $name => $value) { if (array_key_exists($name, $input)) throw new SdkError('validation', 'Path values belong in positional arguments', 'not_sent'); $input[$name] = $value; } return SdkResponse::responsePages($this->runtime->pages('listCustomerDeletionRequests', $input instanceof CustomerDeletionRequestsListInput ? $input->toInputArray() : (new CustomerDeletionRequestsListInput($input))->toInputArray(), $options)); }
    /** @return \Generator<int, CustomerDeletionRequest> */
    public function listItems(array|Model|null $params = null, ?RequestOptions $options = null): \Generator { $input = []; $params = $params instanceof Model ? $params->toInputArray() : $params; $rest = $params ?? []; if ($rest && array_is_list($rest)) throw new SdkError('validation', 'Expected associative params', 'not_sent'); if (array_key_exists('status', $rest)) { $input['status'] = $rest['status']; unset($rest['status']); } if (array_key_exists('customer_id', $rest)) { $input['customer_id'] = $rest['customer_id']; unset($rest['customer_id']); } if (array_key_exists('page_size', $rest)) { $input['page_size'] = $rest['page_size']; unset($rest['page_size']); } if (array_key_exists('page_token', $rest)) { $input['page_token'] = $rest['page_token']; unset($rest['page_token']); } if (array_key_exists('X-Request-Id', $rest)) { $input['X-Request-Id'] = $rest['X-Request-Id']; unset($rest['X-Request-Id']); } if (array_key_exists('Flint-Version', $rest)) { $input['Flint-Version'] = $rest['Flint-Version']; unset($rest['Flint-Version']); } foreach ($rest as $name => $value) { if (array_key_exists($name, $input)) throw new SdkError('validation', 'Path values belong in positional arguments', 'not_sent'); $input[$name] = $value; } return $this->runtime->items('listCustomerDeletionRequests', $input instanceof CustomerDeletionRequestsListInput ? $input->toInputArray() : (new CustomerDeletionRequestsListInput($input))->toInputArray(), $options); }
    /** Approves or rejects a pending deletion request. Approval returns processing while account data and buyer credentials are deleted asynchronously. A failed deletion can be approved again but cannot be rejected. Approval is blocked while the customer has non-canceled subscriptions or usable saved payment methods.
     * @param array<array-key, mixed>|Model $params Flat body fields and query/header parameters; path arguments follow URL order.
     * @return CustomerDeletionRequest
     */
    public function resolve(string|Model $customer_deletion_request_id, array|Model $params, ?RequestOptions $options = null): CustomerDeletionRequest { $input = ['customer_deletion_request_id' => $customer_deletion_request_id]; $params = $params instanceof Model ? $params->toInputArray() : $params; $rest = $params ?? []; if ($rest && array_is_list($rest)) throw new SdkError('validation', 'Expected associative params', 'not_sent'); if (array_key_exists('Idempotency-Key', $rest)) { $input['Idempotency-Key'] = $rest['Idempotency-Key']; unset($rest['Idempotency-Key']); } if (array_key_exists('X-Request-Id', $rest)) { $input['X-Request-Id'] = $rest['X-Request-Id']; unset($rest['X-Request-Id']); } if (array_key_exists('Flint-Version', $rest)) { $input['Flint-Version'] = $rest['Flint-Version']; unset($rest['Flint-Version']); } if (true) $input['body'] = (object) $rest; return SdkResponse::payload($this->runtime->request('resolveCustomerDeletionRequest', $input instanceof CustomerDeletionRequestsResolveInput ? $input->toInputArray() : (new CustomerDeletionRequestsResolveInput($input))->toInputArray(), $options), ['data']); }
    /** @return SdkResponse<CustomerDeletionRequestsResolveResponse200> */
    public function resolveWithResponse(string|Model $customer_deletion_request_id, array|Model $params, ?RequestOptions $options = null): SdkResponse { $input = ['customer_deletion_request_id' => $customer_deletion_request_id]; $params = $params instanceof Model ? $params->toInputArray() : $params; $rest = $params ?? []; if ($rest && array_is_list($rest)) throw new SdkError('validation', 'Expected associative params', 'not_sent'); if (array_key_exists('Idempotency-Key', $rest)) { $input['Idempotency-Key'] = $rest['Idempotency-Key']; unset($rest['Idempotency-Key']); } if (array_key_exists('X-Request-Id', $rest)) { $input['X-Request-Id'] = $rest['X-Request-Id']; unset($rest['X-Request-Id']); } if (array_key_exists('Flint-Version', $rest)) { $input['Flint-Version'] = $rest['Flint-Version']; unset($rest['Flint-Version']); } if (true) $input['body'] = (object) $rest; $result = $this->runtime->request('resolveCustomerDeletionRequest', $input instanceof CustomerDeletionRequestsResolveInput ? $input->toInputArray() : (new CustomerDeletionRequestsResolveInput($input))->toInputArray(), $options); return new SdkResponse($result->data, $result->meta, $result->raw); }
}
