<?php
declare(strict_types=1);
namespace Flint;
final class DeliveryZonesResource {
    public function __construct(private readonly Runtime $runtime) {}
    /** Delivery zones define versioned geographic eligibility. Creation publishes immutable revision 1. It starts active.
     * @param array<array-key, mixed>|Model $params Flat body fields and query/header parameters; path arguments follow URL order.
     * @return DeliveryZone
     */
    public function create(array|Model $params, ?RequestOptions $options = null): DeliveryZone { $input = []; $params = $params instanceof Model ? $params->toInputArray() : $params; $rest = $params ?? []; if ($rest && array_is_list($rest)) throw new SdkError('validation', 'Expected associative params', 'not_sent'); if (array_key_exists('Idempotency-Key', $rest)) { $input['Idempotency-Key'] = $rest['Idempotency-Key']; unset($rest['Idempotency-Key']); } if (array_key_exists('Flint-Version', $rest)) { $input['Flint-Version'] = $rest['Flint-Version']; unset($rest['Flint-Version']); } if (true) $input['body'] = (object) $rest; return SdkResponse::payload($this->runtime->request('createDeliveryZone', $input instanceof DeliveryZonesCreateInput ? $input->toInputArray() : (new DeliveryZonesCreateInput($input))->toInputArray(), $options), ['data']); }
    /** @return SdkResponse<DeliveryZonesCreateResponse201> */
    public function createWithResponse(array|Model $params, ?RequestOptions $options = null): SdkResponse { $input = []; $params = $params instanceof Model ? $params->toInputArray() : $params; $rest = $params ?? []; if ($rest && array_is_list($rest)) throw new SdkError('validation', 'Expected associative params', 'not_sent'); if (array_key_exists('Idempotency-Key', $rest)) { $input['Idempotency-Key'] = $rest['Idempotency-Key']; unset($rest['Idempotency-Key']); } if (array_key_exists('Flint-Version', $rest)) { $input['Flint-Version'] = $rest['Flint-Version']; unset($rest['Flint-Version']); } if (true) $input['body'] = (object) $rest; $result = $this->runtime->request('createDeliveryZone', $input instanceof DeliveryZonesCreateInput ? $input->toInputArray() : (new DeliveryZonesCreateInput($input))->toInputArray(), $options); return new SdkResponse($result->data, $result->meta, $result->raw); }
    /** Retires the delivery zone after checking current dependencies. The retired resource remains available by ID for historical records.
     * @param array<array-key, mixed>|Model|null $params Flat body fields and query/header parameters; path arguments follow URL order.
     * @return DeliveryZone
     */
    public function remove(string|Model $delivery_zone_id, array|Model|null $params = null, ?RequestOptions $options = null): DeliveryZone { $input = ['delivery_zone_id' => $delivery_zone_id]; $params = $params instanceof Model ? $params->toInputArray() : $params; $rest = $params ?? []; if ($rest && array_is_list($rest)) throw new SdkError('validation', 'Expected associative params', 'not_sent'); if (array_key_exists('expected_version', $rest)) { $input['expected_version'] = $rest['expected_version']; unset($rest['expected_version']); } if (array_key_exists('Idempotency-Key', $rest)) { $input['Idempotency-Key'] = $rest['Idempotency-Key']; unset($rest['Idempotency-Key']); } if (array_key_exists('Flint-Version', $rest)) { $input['Flint-Version'] = $rest['Flint-Version']; unset($rest['Flint-Version']); } foreach ($rest as $name => $value) { if (array_key_exists($name, $input)) throw new SdkError('validation', 'Path values belong in positional arguments', 'not_sent'); $input[$name] = $value; } return SdkResponse::payload($this->runtime->request('deleteDeliveryZone', $input instanceof DeliveryZonesRemoveInput ? $input->toInputArray() : (new DeliveryZonesRemoveInput($input))->toInputArray(), $options), ['data']); }
    /** @return SdkResponse<DeliveryZonesRemoveResponse200> */
    public function removeWithResponse(string|Model $delivery_zone_id, array|Model|null $params = null, ?RequestOptions $options = null): SdkResponse { $input = ['delivery_zone_id' => $delivery_zone_id]; $params = $params instanceof Model ? $params->toInputArray() : $params; $rest = $params ?? []; if ($rest && array_is_list($rest)) throw new SdkError('validation', 'Expected associative params', 'not_sent'); if (array_key_exists('expected_version', $rest)) { $input['expected_version'] = $rest['expected_version']; unset($rest['expected_version']); } if (array_key_exists('Idempotency-Key', $rest)) { $input['Idempotency-Key'] = $rest['Idempotency-Key']; unset($rest['Idempotency-Key']); } if (array_key_exists('Flint-Version', $rest)) { $input['Flint-Version'] = $rest['Flint-Version']; unset($rest['Flint-Version']); } foreach ($rest as $name => $value) { if (array_key_exists($name, $input)) throw new SdkError('validation', 'Path values belong in positional arguments', 'not_sent'); $input[$name] = $value; } $result = $this->runtime->request('deleteDeliveryZone', $input instanceof DeliveryZonesRemoveInput ? $input->toInputArray() : (new DeliveryZonesRemoveInput($input))->toInputArray(), $options); return new SdkResponse($result->data, $result->meta, $result->raw); }
    /** Returns the current revision and lifecycle state for one delivery zone.
     * @param array<array-key, mixed>|Model|null $params Flat body fields and query/header parameters; path arguments follow URL order.
     * @return DeliveryZone
     */
    public function get(string|Model $delivery_zone_id, array|Model|null $params = null, ?RequestOptions $options = null): DeliveryZone { $input = ['delivery_zone_id' => $delivery_zone_id]; $params = $params instanceof Model ? $params->toInputArray() : $params; $rest = $params ?? []; if ($rest && array_is_list($rest)) throw new SdkError('validation', 'Expected associative params', 'not_sent'); if (array_key_exists('Flint-Version', $rest)) { $input['Flint-Version'] = $rest['Flint-Version']; unset($rest['Flint-Version']); } foreach ($rest as $name => $value) { if (array_key_exists($name, $input)) throw new SdkError('validation', 'Path values belong in positional arguments', 'not_sent'); $input[$name] = $value; } return SdkResponse::payload($this->runtime->request('getDeliveryZone', $input instanceof DeliveryZonesGetInput ? $input->toInputArray() : (new DeliveryZonesGetInput($input))->toInputArray(), $options), ['data']); }
    /** @return SdkResponse<DeliveryZonesGetResponse200> */
    public function getWithResponse(string|Model $delivery_zone_id, array|Model|null $params = null, ?RequestOptions $options = null): SdkResponse { $input = ['delivery_zone_id' => $delivery_zone_id]; $params = $params instanceof Model ? $params->toInputArray() : $params; $rest = $params ?? []; if ($rest && array_is_list($rest)) throw new SdkError('validation', 'Expected associative params', 'not_sent'); if (array_key_exists('Flint-Version', $rest)) { $input['Flint-Version'] = $rest['Flint-Version']; unset($rest['Flint-Version']); } foreach ($rest as $name => $value) { if (array_key_exists($name, $input)) throw new SdkError('validation', 'Path values belong in positional arguments', 'not_sent'); $input[$name] = $value; } $result = $this->runtime->request('getDeliveryZone', $input instanceof DeliveryZonesGetInput ? $input->toInputArray() : (new DeliveryZonesGetInput($input))->toInputArray(), $options); return new SdkResponse($result->data, $result->meta, $result->raw); }
    /** Returns delivery zones in a stable, cursor-paginated order.
     * @param array<array-key, mixed>|Model|null $params Flat body fields and query/header parameters; path arguments follow URL order.
     * @return DeliveryZonesListResponse200
     */
    public function list(array|Model|null $params = null, ?RequestOptions $options = null): DeliveryZonesListResponse200 { $input = []; $params = $params instanceof Model ? $params->toInputArray() : $params; $rest = $params ?? []; if ($rest && array_is_list($rest)) throw new SdkError('validation', 'Expected associative params', 'not_sent'); if (array_key_exists('page_size', $rest)) { $input['page_size'] = $rest['page_size']; unset($rest['page_size']); } if (array_key_exists('page_token', $rest)) { $input['page_token'] = $rest['page_token']; unset($rest['page_token']); } if (array_key_exists('query', $rest)) { $input['query'] = $rest['query']; unset($rest['query']); } if (array_key_exists('external_reference_id', $rest)) { $input['external_reference_id'] = $rest['external_reference_id']; unset($rest['external_reference_id']); } if (array_key_exists('status', $rest)) { $input['status'] = $rest['status']; unset($rest['status']); } if (array_key_exists('delivery_method_id', $rest)) { $input['delivery_method_id'] = $rest['delivery_method_id']; unset($rest['delivery_method_id']); } if (array_key_exists('Flint-Version', $rest)) { $input['Flint-Version'] = $rest['Flint-Version']; unset($rest['Flint-Version']); } foreach ($rest as $name => $value) { if (array_key_exists($name, $input)) throw new SdkError('validation', 'Path values belong in positional arguments', 'not_sent'); $input[$name] = $value; } return SdkResponse::payload($this->runtime->request('listDeliveryZones', $input instanceof DeliveryZonesListInput ? $input->toInputArray() : (new DeliveryZonesListInput($input))->toInputArray(), $options), []); }
    /** @return SdkResponse<DeliveryZonesListResponse200> */
    public function listWithResponse(array|Model|null $params = null, ?RequestOptions $options = null): SdkResponse { $input = []; $params = $params instanceof Model ? $params->toInputArray() : $params; $rest = $params ?? []; if ($rest && array_is_list($rest)) throw new SdkError('validation', 'Expected associative params', 'not_sent'); if (array_key_exists('page_size', $rest)) { $input['page_size'] = $rest['page_size']; unset($rest['page_size']); } if (array_key_exists('page_token', $rest)) { $input['page_token'] = $rest['page_token']; unset($rest['page_token']); } if (array_key_exists('query', $rest)) { $input['query'] = $rest['query']; unset($rest['query']); } if (array_key_exists('external_reference_id', $rest)) { $input['external_reference_id'] = $rest['external_reference_id']; unset($rest['external_reference_id']); } if (array_key_exists('status', $rest)) { $input['status'] = $rest['status']; unset($rest['status']); } if (array_key_exists('delivery_method_id', $rest)) { $input['delivery_method_id'] = $rest['delivery_method_id']; unset($rest['delivery_method_id']); } if (array_key_exists('Flint-Version', $rest)) { $input['Flint-Version'] = $rest['Flint-Version']; unset($rest['Flint-Version']); } foreach ($rest as $name => $value) { if (array_key_exists($name, $input)) throw new SdkError('validation', 'Path values belong in positional arguments', 'not_sent'); $input[$name] = $value; } $result = $this->runtime->request('listDeliveryZones', $input instanceof DeliveryZonesListInput ? $input->toInputArray() : (new DeliveryZonesListInput($input))->toInputArray(), $options); return new SdkResponse($result->data, $result->meta, $result->raw); }
    /** @return \Generator<int, DeliveryZonesListResponse200> */
    public function listPages(array|Model|null $params = null, ?RequestOptions $options = null): \Generator { $input = []; $params = $params instanceof Model ? $params->toInputArray() : $params; $rest = $params ?? []; if ($rest && array_is_list($rest)) throw new SdkError('validation', 'Expected associative params', 'not_sent'); if (array_key_exists('page_size', $rest)) { $input['page_size'] = $rest['page_size']; unset($rest['page_size']); } if (array_key_exists('page_token', $rest)) { $input['page_token'] = $rest['page_token']; unset($rest['page_token']); } if (array_key_exists('query', $rest)) { $input['query'] = $rest['query']; unset($rest['query']); } if (array_key_exists('external_reference_id', $rest)) { $input['external_reference_id'] = $rest['external_reference_id']; unset($rest['external_reference_id']); } if (array_key_exists('status', $rest)) { $input['status'] = $rest['status']; unset($rest['status']); } if (array_key_exists('delivery_method_id', $rest)) { $input['delivery_method_id'] = $rest['delivery_method_id']; unset($rest['delivery_method_id']); } if (array_key_exists('Flint-Version', $rest)) { $input['Flint-Version'] = $rest['Flint-Version']; unset($rest['Flint-Version']); } foreach ($rest as $name => $value) { if (array_key_exists($name, $input)) throw new SdkError('validation', 'Path values belong in positional arguments', 'not_sent'); $input[$name] = $value; } return SdkResponse::payloadPages($this->runtime->pages('listDeliveryZones', $input instanceof DeliveryZonesListInput ? $input->toInputArray() : (new DeliveryZonesListInput($input))->toInputArray(), $options), []); }
    /** @return \Generator<int, SdkResponse<DeliveryZonesListResponse200>> */
    public function listPagesWithResponse(array|Model|null $params = null, ?RequestOptions $options = null): \Generator { $input = []; $params = $params instanceof Model ? $params->toInputArray() : $params; $rest = $params ?? []; if ($rest && array_is_list($rest)) throw new SdkError('validation', 'Expected associative params', 'not_sent'); if (array_key_exists('page_size', $rest)) { $input['page_size'] = $rest['page_size']; unset($rest['page_size']); } if (array_key_exists('page_token', $rest)) { $input['page_token'] = $rest['page_token']; unset($rest['page_token']); } if (array_key_exists('query', $rest)) { $input['query'] = $rest['query']; unset($rest['query']); } if (array_key_exists('external_reference_id', $rest)) { $input['external_reference_id'] = $rest['external_reference_id']; unset($rest['external_reference_id']); } if (array_key_exists('status', $rest)) { $input['status'] = $rest['status']; unset($rest['status']); } if (array_key_exists('delivery_method_id', $rest)) { $input['delivery_method_id'] = $rest['delivery_method_id']; unset($rest['delivery_method_id']); } if (array_key_exists('Flint-Version', $rest)) { $input['Flint-Version'] = $rest['Flint-Version']; unset($rest['Flint-Version']); } foreach ($rest as $name => $value) { if (array_key_exists($name, $input)) throw new SdkError('validation', 'Path values belong in positional arguments', 'not_sent'); $input[$name] = $value; } return SdkResponse::responsePages($this->runtime->pages('listDeliveryZones', $input instanceof DeliveryZonesListInput ? $input->toInputArray() : (new DeliveryZonesListInput($input))->toInputArray(), $options)); }
    /** @return \Generator<int, DeliveryZone> */
    public function listItems(array|Model|null $params = null, ?RequestOptions $options = null): \Generator { $input = []; $params = $params instanceof Model ? $params->toInputArray() : $params; $rest = $params ?? []; if ($rest && array_is_list($rest)) throw new SdkError('validation', 'Expected associative params', 'not_sent'); if (array_key_exists('page_size', $rest)) { $input['page_size'] = $rest['page_size']; unset($rest['page_size']); } if (array_key_exists('page_token', $rest)) { $input['page_token'] = $rest['page_token']; unset($rest['page_token']); } if (array_key_exists('query', $rest)) { $input['query'] = $rest['query']; unset($rest['query']); } if (array_key_exists('external_reference_id', $rest)) { $input['external_reference_id'] = $rest['external_reference_id']; unset($rest['external_reference_id']); } if (array_key_exists('status', $rest)) { $input['status'] = $rest['status']; unset($rest['status']); } if (array_key_exists('delivery_method_id', $rest)) { $input['delivery_method_id'] = $rest['delivery_method_id']; unset($rest['delivery_method_id']); } if (array_key_exists('Flint-Version', $rest)) { $input['Flint-Version'] = $rest['Flint-Version']; unset($rest['Flint-Version']); } foreach ($rest as $name => $value) { if (array_key_exists($name, $input)) throw new SdkError('validation', 'Path values belong in positional arguments', 'not_sent'); $input[$name] = $value; } return $this->runtime->items('listDeliveryZones', $input instanceof DeliveryZonesListInput ? $input->toInputArray() : (new DeliveryZonesListInput($input))->toInputArray(), $options); }
    /** Sparsely updates mutable fields. A change to pinned configuration publishes a new immutable revision and requires expected_version.
     * @param array<array-key, mixed>|Model $params Flat body fields and query/header parameters; path arguments follow URL order.
     * @return DeliveryZone
     */
    public function update(string|Model $delivery_zone_id, array|Model $params, ?RequestOptions $options = null): DeliveryZone { $input = ['delivery_zone_id' => $delivery_zone_id]; $params = $params instanceof Model ? $params->toInputArray() : $params; $rest = $params ?? []; if ($rest && array_is_list($rest)) throw new SdkError('validation', 'Expected associative params', 'not_sent'); if (array_key_exists('Idempotency-Key', $rest)) { $input['Idempotency-Key'] = $rest['Idempotency-Key']; unset($rest['Idempotency-Key']); } if (array_key_exists('Flint-Version', $rest)) { $input['Flint-Version'] = $rest['Flint-Version']; unset($rest['Flint-Version']); } if (true) $input['body'] = (object) $rest; return SdkResponse::payload($this->runtime->request('updateDeliveryZone', $input instanceof DeliveryZonesUpdateInput ? $input->toInputArray() : (new DeliveryZonesUpdateInput($input))->toInputArray(), $options), ['data']); }
    /** @return SdkResponse<DeliveryZonesUpdateResponse200> */
    public function updateWithResponse(string|Model $delivery_zone_id, array|Model $params, ?RequestOptions $options = null): SdkResponse { $input = ['delivery_zone_id' => $delivery_zone_id]; $params = $params instanceof Model ? $params->toInputArray() : $params; $rest = $params ?? []; if ($rest && array_is_list($rest)) throw new SdkError('validation', 'Expected associative params', 'not_sent'); if (array_key_exists('Idempotency-Key', $rest)) { $input['Idempotency-Key'] = $rest['Idempotency-Key']; unset($rest['Idempotency-Key']); } if (array_key_exists('Flint-Version', $rest)) { $input['Flint-Version'] = $rest['Flint-Version']; unset($rest['Flint-Version']); } if (true) $input['body'] = (object) $rest; $result = $this->runtime->request('updateDeliveryZone', $input instanceof DeliveryZonesUpdateInput ? $input->toInputArray() : (new DeliveryZonesUpdateInput($input))->toInputArray(), $options); return new SdkResponse($result->data, $result->meta, $result->raw); }
}
