<?php
declare(strict_types=1);
namespace Flint;
final class GiftCardFundingDisputesResource {
    public function __construct(private readonly Runtime $runtime) {}
    /** Accepts a confirmed funding dispute loss and honors all gift card value funded by that payment, including replacement refund lots. Records the dispute amount, original gift card consideration, honored value and preserved reservations. Clears only this dispute restriction; balances, unrelated restrictions and unresolved payment reservations remain intact. Requires gift card adjustment authority and a durable Idempotency-Key.
     * @param array<array-key, mixed>|Model $params Flat body fields and query/header parameters; path arguments follow URL order.
     * @return GiftCardCommandResult
     */
    public function honorValue(string|Model $dispute_id, array|Model $params, ?RequestOptions $options = null): GiftCardCommandResult { $input = ['dispute_id' => $dispute_id]; $params = $params instanceof Model ? $params->toInputArray() : $params; $rest = $params ?? []; if ($rest && array_is_list($rest)) throw new SdkError('validation', 'Expected associative params', 'not_sent'); if (array_key_exists('X-Request-Id', $rest)) { $input['X-Request-Id'] = $rest['X-Request-Id']; unset($rest['X-Request-Id']); } if (array_key_exists('Idempotency-Key', $rest)) { $input['Idempotency-Key'] = $rest['Idempotency-Key']; unset($rest['Idempotency-Key']); } if (array_key_exists('Flint-Version', $rest)) { $input['Flint-Version'] = $rest['Flint-Version']; unset($rest['Flint-Version']); } if (true) $input['body'] = (object) $rest; return SdkResponse::payload($this->runtime->request('honorGiftCardFundingLoss', $input instanceof GiftCardFundingDisputesHonorValueInput ? $input->toInputArray() : (new GiftCardFundingDisputesHonorValueInput($input))->toInputArray(), $options), ['data']); }
    /** @return SdkResponse<GiftCardFundingDisputesHonorValueResponse200> */
    public function honorValueWithResponse(string|Model $dispute_id, array|Model $params, ?RequestOptions $options = null): SdkResponse { $input = ['dispute_id' => $dispute_id]; $params = $params instanceof Model ? $params->toInputArray() : $params; $rest = $params ?? []; if ($rest && array_is_list($rest)) throw new SdkError('validation', 'Expected associative params', 'not_sent'); if (array_key_exists('X-Request-Id', $rest)) { $input['X-Request-Id'] = $rest['X-Request-Id']; unset($rest['X-Request-Id']); } if (array_key_exists('Idempotency-Key', $rest)) { $input['Idempotency-Key'] = $rest['Idempotency-Key']; unset($rest['Idempotency-Key']); } if (array_key_exists('Flint-Version', $rest)) { $input['Flint-Version'] = $rest['Flint-Version']; unset($rest['Flint-Version']); } if (true) $input['body'] = (object) $rest; $result = $this->runtime->request('honorGiftCardFundingLoss', $input instanceof GiftCardFundingDisputesHonorValueInput ? $input->toInputArray() : (new GiftCardFundingDisputesHonorValueInput($input))->toInputArray(), $options); return new SdkResponse($result->data, $result->meta, $result->raw); }
}
