<?php
declare(strict_types=1);
namespace Flint;
final class GiftCardLoadsResource {
    public function __construct(private readonly Runtime $runtime) {}
    /** Adds positive value with separately recorded consideration and funding provenance. Limits apply to externally funded value and imports as well as Flint-funded sales. Loading a pending card activates it; loading a frozen card does not remove its restrictions.
     * @param array<array-key, mixed>|Model $params Flat body fields and query/header parameters; path arguments follow URL order.
     * @return GiftCardCommandResult
     */
    public function create(string|Model $gift_card_id, array|Model $params, ?RequestOptions $options = null): GiftCardCommandResult { $input = ['gift_card_id' => $gift_card_id]; $params = $params instanceof Model ? $params->toInputArray() : $params; $rest = $params ?? []; if ($rest && array_is_list($rest)) throw new SdkError('validation', 'Expected associative params', 'not_sent'); if (array_key_exists('X-Request-Id', $rest)) { $input['X-Request-Id'] = $rest['X-Request-Id']; unset($rest['X-Request-Id']); } if (array_key_exists('Idempotency-Key', $rest)) { $input['Idempotency-Key'] = $rest['Idempotency-Key']; unset($rest['Idempotency-Key']); } if (array_key_exists('Flint-Version', $rest)) { $input['Flint-Version'] = $rest['Flint-Version']; unset($rest['Flint-Version']); } if (true) $input['body'] = (object) $rest; return SdkResponse::payload($this->runtime->request('createGiftCardLoad', $input instanceof GiftCardLoadsCreateInput ? $input->toInputArray() : (new GiftCardLoadsCreateInput($input))->toInputArray(), $options), ['data']); }
    /** @return SdkResponse<GiftCardLoadsCreateResponse201> */
    public function createWithResponse(string|Model $gift_card_id, array|Model $params, ?RequestOptions $options = null): SdkResponse { $input = ['gift_card_id' => $gift_card_id]; $params = $params instanceof Model ? $params->toInputArray() : $params; $rest = $params ?? []; if ($rest && array_is_list($rest)) throw new SdkError('validation', 'Expected associative params', 'not_sent'); if (array_key_exists('X-Request-Id', $rest)) { $input['X-Request-Id'] = $rest['X-Request-Id']; unset($rest['X-Request-Id']); } if (array_key_exists('Idempotency-Key', $rest)) { $input['Idempotency-Key'] = $rest['Idempotency-Key']; unset($rest['Idempotency-Key']); } if (array_key_exists('Flint-Version', $rest)) { $input['Flint-Version'] = $rest['Flint-Version']; unset($rest['Flint-Version']); } if (true) $input['body'] = (object) $rest; $result = $this->runtime->request('createGiftCardLoad', $input instanceof GiftCardLoadsCreateInput ? $input->toInputArray() : (new GiftCardLoadsCreateInput($input))->toInputArray(), $options); return new SdkResponse($result->data, $result->meta, $result->raw); }
    /** Retrieves original value, consideration, funding provenance and remaining attributable value for one load.
     * @param array<array-key, mixed>|Model|null $params Flat body fields and query/header parameters; path arguments follow URL order.
     * @return GiftCardLoad
     */
    public function get(string|Model $gift_card_load_id, array|Model|null $params = null, ?RequestOptions $options = null): GiftCardLoad { $input = ['gift_card_load_id' => $gift_card_load_id]; $params = $params instanceof Model ? $params->toInputArray() : $params; $rest = $params ?? []; if ($rest && array_is_list($rest)) throw new SdkError('validation', 'Expected associative params', 'not_sent'); if (array_key_exists('X-Request-Id', $rest)) { $input['X-Request-Id'] = $rest['X-Request-Id']; unset($rest['X-Request-Id']); } if (array_key_exists('Flint-Version', $rest)) { $input['Flint-Version'] = $rest['Flint-Version']; unset($rest['Flint-Version']); } foreach ($rest as $name => $value) { if (array_key_exists($name, $input)) throw new SdkError('validation', 'Path values belong in positional arguments', 'not_sent'); $input[$name] = $value; } return SdkResponse::payload($this->runtime->request('getGiftCardLoad', $input instanceof GiftCardLoadsGetInput ? $input->toInputArray() : (new GiftCardLoadsGetInput($input))->toInputArray(), $options), ['data']); }
    /** @return SdkResponse<GiftCardLoadsGetResponse200> */
    public function getWithResponse(string|Model $gift_card_load_id, array|Model|null $params = null, ?RequestOptions $options = null): SdkResponse { $input = ['gift_card_load_id' => $gift_card_load_id]; $params = $params instanceof Model ? $params->toInputArray() : $params; $rest = $params ?? []; if ($rest && array_is_list($rest)) throw new SdkError('validation', 'Expected associative params', 'not_sent'); if (array_key_exists('X-Request-Id', $rest)) { $input['X-Request-Id'] = $rest['X-Request-Id']; unset($rest['X-Request-Id']); } if (array_key_exists('Flint-Version', $rest)) { $input['Flint-Version'] = $rest['Flint-Version']; unset($rest['Flint-Version']); } foreach ($rest as $name => $value) { if (array_key_exists($name, $input)) throw new SdkError('validation', 'Path values belong in positional arguments', 'not_sent'); $input[$name] = $value; } $result = $this->runtime->request('getGiftCardLoad', $input instanceof GiftCardLoadsGetInput ? $input->toInputArray() : (new GiftCardLoadsGetInput($input))->toInputArray(), $options); return new SdkResponse($result->data, $result->meta, $result->raw); }
    /** Lists funding lots in descending ID order. Consideration may be null for imported balances whose original purchase price is unknown. The idempotency_key filter recovers a load after a lost command response.
     * @param array<array-key, mixed>|Model|null $params Flat body fields and query/header parameters; path arguments follow URL order.
     * @return GiftCardLoadsListResponse200
     */
    public function list(array|Model|null $params = null, ?RequestOptions $options = null): GiftCardLoadsListResponse200 { $input = []; $params = $params instanceof Model ? $params->toInputArray() : $params; $rest = $params ?? []; if ($rest && array_is_list($rest)) throw new SdkError('validation', 'Expected associative params', 'not_sent'); if (array_key_exists('X-Request-Id', $rest)) { $input['X-Request-Id'] = $rest['X-Request-Id']; unset($rest['X-Request-Id']); } if (array_key_exists('from_at', $rest)) { $input['from_at'] = $rest['from_at']; unset($rest['from_at']); } if (array_key_exists('gift_card_id', $rest)) { $input['gift_card_id'] = $rest['gift_card_id']; unset($rest['gift_card_id']); } if (array_key_exists('idempotency_key', $rest)) { $input['idempotency_key'] = $rest['idempotency_key']; unset($rest['idempotency_key']); } if (array_key_exists('order_id', $rest)) { $input['order_id'] = $rest['order_id']; unset($rest['order_id']); } if (array_key_exists('page_size', $rest)) { $input['page_size'] = $rest['page_size']; unset($rest['page_size']); } if (array_key_exists('page_token', $rest)) { $input['page_token'] = $rest['page_token']; unset($rest['page_token']); } if (array_key_exists('source_id', $rest)) { $input['source_id'] = $rest['source_id']; unset($rest['source_id']); } if (array_key_exists('source_type', $rest)) { $input['source_type'] = $rest['source_type']; unset($rest['source_type']); } if (array_key_exists('until_at', $rest)) { $input['until_at'] = $rest['until_at']; unset($rest['until_at']); } if (array_key_exists('Flint-Version', $rest)) { $input['Flint-Version'] = $rest['Flint-Version']; unset($rest['Flint-Version']); } foreach ($rest as $name => $value) { if (array_key_exists($name, $input)) throw new SdkError('validation', 'Path values belong in positional arguments', 'not_sent'); $input[$name] = $value; } return SdkResponse::payload($this->runtime->request('listGiftCardLoads', $input instanceof GiftCardLoadsListInput ? $input->toInputArray() : (new GiftCardLoadsListInput($input))->toInputArray(), $options), []); }
    /** @return SdkResponse<GiftCardLoadsListResponse200> */
    public function listWithResponse(array|Model|null $params = null, ?RequestOptions $options = null): SdkResponse { $input = []; $params = $params instanceof Model ? $params->toInputArray() : $params; $rest = $params ?? []; if ($rest && array_is_list($rest)) throw new SdkError('validation', 'Expected associative params', 'not_sent'); if (array_key_exists('X-Request-Id', $rest)) { $input['X-Request-Id'] = $rest['X-Request-Id']; unset($rest['X-Request-Id']); } if (array_key_exists('from_at', $rest)) { $input['from_at'] = $rest['from_at']; unset($rest['from_at']); } if (array_key_exists('gift_card_id', $rest)) { $input['gift_card_id'] = $rest['gift_card_id']; unset($rest['gift_card_id']); } if (array_key_exists('idempotency_key', $rest)) { $input['idempotency_key'] = $rest['idempotency_key']; unset($rest['idempotency_key']); } if (array_key_exists('order_id', $rest)) { $input['order_id'] = $rest['order_id']; unset($rest['order_id']); } if (array_key_exists('page_size', $rest)) { $input['page_size'] = $rest['page_size']; unset($rest['page_size']); } if (array_key_exists('page_token', $rest)) { $input['page_token'] = $rest['page_token']; unset($rest['page_token']); } if (array_key_exists('source_id', $rest)) { $input['source_id'] = $rest['source_id']; unset($rest['source_id']); } if (array_key_exists('source_type', $rest)) { $input['source_type'] = $rest['source_type']; unset($rest['source_type']); } if (array_key_exists('until_at', $rest)) { $input['until_at'] = $rest['until_at']; unset($rest['until_at']); } if (array_key_exists('Flint-Version', $rest)) { $input['Flint-Version'] = $rest['Flint-Version']; unset($rest['Flint-Version']); } foreach ($rest as $name => $value) { if (array_key_exists($name, $input)) throw new SdkError('validation', 'Path values belong in positional arguments', 'not_sent'); $input[$name] = $value; } $result = $this->runtime->request('listGiftCardLoads', $input instanceof GiftCardLoadsListInput ? $input->toInputArray() : (new GiftCardLoadsListInput($input))->toInputArray(), $options); return new SdkResponse($result->data, $result->meta, $result->raw); }
    /** @return \Generator<int, GiftCardLoadsListResponse200> */
    public function listPages(array|Model|null $params = null, ?RequestOptions $options = null): \Generator { $input = []; $params = $params instanceof Model ? $params->toInputArray() : $params; $rest = $params ?? []; if ($rest && array_is_list($rest)) throw new SdkError('validation', 'Expected associative params', 'not_sent'); if (array_key_exists('X-Request-Id', $rest)) { $input['X-Request-Id'] = $rest['X-Request-Id']; unset($rest['X-Request-Id']); } if (array_key_exists('from_at', $rest)) { $input['from_at'] = $rest['from_at']; unset($rest['from_at']); } if (array_key_exists('gift_card_id', $rest)) { $input['gift_card_id'] = $rest['gift_card_id']; unset($rest['gift_card_id']); } if (array_key_exists('idempotency_key', $rest)) { $input['idempotency_key'] = $rest['idempotency_key']; unset($rest['idempotency_key']); } if (array_key_exists('order_id', $rest)) { $input['order_id'] = $rest['order_id']; unset($rest['order_id']); } if (array_key_exists('page_size', $rest)) { $input['page_size'] = $rest['page_size']; unset($rest['page_size']); } if (array_key_exists('page_token', $rest)) { $input['page_token'] = $rest['page_token']; unset($rest['page_token']); } if (array_key_exists('source_id', $rest)) { $input['source_id'] = $rest['source_id']; unset($rest['source_id']); } if (array_key_exists('source_type', $rest)) { $input['source_type'] = $rest['source_type']; unset($rest['source_type']); } if (array_key_exists('until_at', $rest)) { $input['until_at'] = $rest['until_at']; unset($rest['until_at']); } if (array_key_exists('Flint-Version', $rest)) { $input['Flint-Version'] = $rest['Flint-Version']; unset($rest['Flint-Version']); } foreach ($rest as $name => $value) { if (array_key_exists($name, $input)) throw new SdkError('validation', 'Path values belong in positional arguments', 'not_sent'); $input[$name] = $value; } return SdkResponse::payloadPages($this->runtime->pages('listGiftCardLoads', $input instanceof GiftCardLoadsListInput ? $input->toInputArray() : (new GiftCardLoadsListInput($input))->toInputArray(), $options), []); }
    /** @return \Generator<int, SdkResponse<GiftCardLoadsListResponse200>> */
    public function listPagesWithResponse(array|Model|null $params = null, ?RequestOptions $options = null): \Generator { $input = []; $params = $params instanceof Model ? $params->toInputArray() : $params; $rest = $params ?? []; if ($rest && array_is_list($rest)) throw new SdkError('validation', 'Expected associative params', 'not_sent'); if (array_key_exists('X-Request-Id', $rest)) { $input['X-Request-Id'] = $rest['X-Request-Id']; unset($rest['X-Request-Id']); } if (array_key_exists('from_at', $rest)) { $input['from_at'] = $rest['from_at']; unset($rest['from_at']); } if (array_key_exists('gift_card_id', $rest)) { $input['gift_card_id'] = $rest['gift_card_id']; unset($rest['gift_card_id']); } if (array_key_exists('idempotency_key', $rest)) { $input['idempotency_key'] = $rest['idempotency_key']; unset($rest['idempotency_key']); } if (array_key_exists('order_id', $rest)) { $input['order_id'] = $rest['order_id']; unset($rest['order_id']); } if (array_key_exists('page_size', $rest)) { $input['page_size'] = $rest['page_size']; unset($rest['page_size']); } if (array_key_exists('page_token', $rest)) { $input['page_token'] = $rest['page_token']; unset($rest['page_token']); } if (array_key_exists('source_id', $rest)) { $input['source_id'] = $rest['source_id']; unset($rest['source_id']); } if (array_key_exists('source_type', $rest)) { $input['source_type'] = $rest['source_type']; unset($rest['source_type']); } if (array_key_exists('until_at', $rest)) { $input['until_at'] = $rest['until_at']; unset($rest['until_at']); } if (array_key_exists('Flint-Version', $rest)) { $input['Flint-Version'] = $rest['Flint-Version']; unset($rest['Flint-Version']); } foreach ($rest as $name => $value) { if (array_key_exists($name, $input)) throw new SdkError('validation', 'Path values belong in positional arguments', 'not_sent'); $input[$name] = $value; } return SdkResponse::responsePages($this->runtime->pages('listGiftCardLoads', $input instanceof GiftCardLoadsListInput ? $input->toInputArray() : (new GiftCardLoadsListInput($input))->toInputArray(), $options)); }
    /** @return \Generator<int, GiftCardLoad> */
    public function listItems(array|Model|null $params = null, ?RequestOptions $options = null): \Generator { $input = []; $params = $params instanceof Model ? $params->toInputArray() : $params; $rest = $params ?? []; if ($rest && array_is_list($rest)) throw new SdkError('validation', 'Expected associative params', 'not_sent'); if (array_key_exists('X-Request-Id', $rest)) { $input['X-Request-Id'] = $rest['X-Request-Id']; unset($rest['X-Request-Id']); } if (array_key_exists('from_at', $rest)) { $input['from_at'] = $rest['from_at']; unset($rest['from_at']); } if (array_key_exists('gift_card_id', $rest)) { $input['gift_card_id'] = $rest['gift_card_id']; unset($rest['gift_card_id']); } if (array_key_exists('idempotency_key', $rest)) { $input['idempotency_key'] = $rest['idempotency_key']; unset($rest['idempotency_key']); } if (array_key_exists('order_id', $rest)) { $input['order_id'] = $rest['order_id']; unset($rest['order_id']); } if (array_key_exists('page_size', $rest)) { $input['page_size'] = $rest['page_size']; unset($rest['page_size']); } if (array_key_exists('page_token', $rest)) { $input['page_token'] = $rest['page_token']; unset($rest['page_token']); } if (array_key_exists('source_id', $rest)) { $input['source_id'] = $rest['source_id']; unset($rest['source_id']); } if (array_key_exists('source_type', $rest)) { $input['source_type'] = $rest['source_type']; unset($rest['source_type']); } if (array_key_exists('until_at', $rest)) { $input['until_at'] = $rest['until_at']; unset($rest['until_at']); } if (array_key_exists('Flint-Version', $rest)) { $input['Flint-Version'] = $rest['Flint-Version']; unset($rest['Flint-Version']); } foreach ($rest as $name => $value) { if (array_key_exists($name, $input)) throw new SdkError('validation', 'Path values belong in positional arguments', 'not_sent'); $input[$name] = $value; } return $this->runtime->items('listGiftCardLoads', $input instanceof GiftCardLoadsListInput ? $input->toInputArray() : (new GiftCardLoadsListInput($input))->toInputArray(), $options); }
}
