<?php
declare(strict_types=1);
namespace Flint;
final class InventoryAllocationPoliciesResource {
    public function __construct(private readonly Runtime $runtime) {}
    /** Create an allocation policy with its routing configuration.
     * @param array<array-key, mixed>|Model $params Flat body fields and query/header parameters; path arguments follow URL order.
     * @return InventoryAllocationPolicy
     */
    public function create(array|Model $params, ?RequestOptions $options = null): InventoryAllocationPolicy { $input = []; $params = $params instanceof Model ? $params->toInputArray() : $params; $rest = $params ?? []; if ($rest && array_is_list($rest)) throw new SdkError('validation', 'Expected associative params', 'not_sent'); if (array_key_exists('Idempotency-Key', $rest)) { $input['Idempotency-Key'] = $rest['Idempotency-Key']; unset($rest['Idempotency-Key']); } if (array_key_exists('Flint-Version', $rest)) { $input['Flint-Version'] = $rest['Flint-Version']; unset($rest['Flint-Version']); } if (true) $input['body'] = (object) $rest; return SdkResponse::payload($this->runtime->request('createInventoryAllocationPolicy', $input instanceof InventoryAllocationPoliciesCreateInput ? $input->toInputArray() : (new InventoryAllocationPoliciesCreateInput($input))->toInputArray(), $options), ['data']); }
    /** @return SdkResponse<InventoryAllocationPoliciesCreateResponse201> */
    public function createWithResponse(array|Model $params, ?RequestOptions $options = null): SdkResponse { $input = []; $params = $params instanceof Model ? $params->toInputArray() : $params; $rest = $params ?? []; if ($rest && array_is_list($rest)) throw new SdkError('validation', 'Expected associative params', 'not_sent'); if (array_key_exists('Idempotency-Key', $rest)) { $input['Idempotency-Key'] = $rest['Idempotency-Key']; unset($rest['Idempotency-Key']); } if (array_key_exists('Flint-Version', $rest)) { $input['Flint-Version'] = $rest['Flint-Version']; unset($rest['Flint-Version']); } if (true) $input['body'] = (object) $rest; $result = $this->runtime->request('createInventoryAllocationPolicy', $input instanceof InventoryAllocationPoliciesCreateInput ? $input->toInputArray() : (new InventoryAllocationPoliciesCreateInput($input))->toInputArray(), $options); return new SdkResponse($result->data, $result->meta, $result->raw); }
    /** Retire an allocation policy. The policy is archived: it stays readable by ID and appears in lists only when you filter by status archived.
     * @param array<array-key, mixed>|Model|null $params Flat body fields and query/header parameters; path arguments follow URL order.
     * @return InventoryAllocationPolicy
     */
    public function remove(string|Model $inventory_allocation_policy_id, array|Model|null $params = null, ?RequestOptions $options = null): InventoryAllocationPolicy { $input = ['inventory_allocation_policy_id' => $inventory_allocation_policy_id]; $params = $params instanceof Model ? $params->toInputArray() : $params; $rest = $params ?? []; if ($rest && array_is_list($rest)) throw new SdkError('validation', 'Expected associative params', 'not_sent'); if (array_key_exists('expected_version', $rest)) { $input['expected_version'] = $rest['expected_version']; unset($rest['expected_version']); } if (array_key_exists('Idempotency-Key', $rest)) { $input['Idempotency-Key'] = $rest['Idempotency-Key']; unset($rest['Idempotency-Key']); } if (array_key_exists('Flint-Version', $rest)) { $input['Flint-Version'] = $rest['Flint-Version']; unset($rest['Flint-Version']); } foreach ($rest as $name => $value) { if (array_key_exists($name, $input)) throw new SdkError('validation', 'Path values belong in positional arguments', 'not_sent'); $input[$name] = $value; } return SdkResponse::payload($this->runtime->request('deleteInventoryAllocationPolicy', $input instanceof InventoryAllocationPoliciesRemoveInput ? $input->toInputArray() : (new InventoryAllocationPoliciesRemoveInput($input))->toInputArray(), $options), ['data']); }
    /** @return SdkResponse<InventoryAllocationPoliciesRemoveResponse200> */
    public function removeWithResponse(string|Model $inventory_allocation_policy_id, array|Model|null $params = null, ?RequestOptions $options = null): SdkResponse { $input = ['inventory_allocation_policy_id' => $inventory_allocation_policy_id]; $params = $params instanceof Model ? $params->toInputArray() : $params; $rest = $params ?? []; if ($rest && array_is_list($rest)) throw new SdkError('validation', 'Expected associative params', 'not_sent'); if (array_key_exists('expected_version', $rest)) { $input['expected_version'] = $rest['expected_version']; unset($rest['expected_version']); } if (array_key_exists('Idempotency-Key', $rest)) { $input['Idempotency-Key'] = $rest['Idempotency-Key']; unset($rest['Idempotency-Key']); } if (array_key_exists('Flint-Version', $rest)) { $input['Flint-Version'] = $rest['Flint-Version']; unset($rest['Flint-Version']); } foreach ($rest as $name => $value) { if (array_key_exists($name, $input)) throw new SdkError('validation', 'Path values belong in positional arguments', 'not_sent'); $input[$name] = $value; } $result = $this->runtime->request('deleteInventoryAllocationPolicy', $input instanceof InventoryAllocationPoliciesRemoveInput ? $input->toInputArray() : (new InventoryAllocationPoliciesRemoveInput($input))->toInputArray(), $options); return new SdkResponse($result->data, $result->meta, $result->raw); }
    /** Retrieve an allocation policy by ID, including archived policies.
     * @param array<array-key, mixed>|Model|null $params Flat body fields and query/header parameters; path arguments follow URL order.
     * @return InventoryAllocationPolicy
     */
    public function get(string|Model $inventory_allocation_policy_id, array|Model|null $params = null, ?RequestOptions $options = null): InventoryAllocationPolicy { $input = ['inventory_allocation_policy_id' => $inventory_allocation_policy_id]; $params = $params instanceof Model ? $params->toInputArray() : $params; $rest = $params ?? []; if ($rest && array_is_list($rest)) throw new SdkError('validation', 'Expected associative params', 'not_sent'); if (array_key_exists('Flint-Version', $rest)) { $input['Flint-Version'] = $rest['Flint-Version']; unset($rest['Flint-Version']); } foreach ($rest as $name => $value) { if (array_key_exists($name, $input)) throw new SdkError('validation', 'Path values belong in positional arguments', 'not_sent'); $input[$name] = $value; } return SdkResponse::payload($this->runtime->request('getInventoryAllocationPolicy', $input instanceof InventoryAllocationPoliciesGetInput ? $input->toInputArray() : (new InventoryAllocationPoliciesGetInput($input))->toInputArray(), $options), ['data']); }
    /** @return SdkResponse<InventoryAllocationPoliciesGetResponse200> */
    public function getWithResponse(string|Model $inventory_allocation_policy_id, array|Model|null $params = null, ?RequestOptions $options = null): SdkResponse { $input = ['inventory_allocation_policy_id' => $inventory_allocation_policy_id]; $params = $params instanceof Model ? $params->toInputArray() : $params; $rest = $params ?? []; if ($rest && array_is_list($rest)) throw new SdkError('validation', 'Expected associative params', 'not_sent'); if (array_key_exists('Flint-Version', $rest)) { $input['Flint-Version'] = $rest['Flint-Version']; unset($rest['Flint-Version']); } foreach ($rest as $name => $value) { if (array_key_exists($name, $input)) throw new SdkError('validation', 'Path values belong in positional arguments', 'not_sent'); $input[$name] = $value; } $result = $this->runtime->request('getInventoryAllocationPolicy', $input instanceof InventoryAllocationPoliciesGetInput ? $input->toInputArray() : (new InventoryAllocationPoliciesGetInput($input))->toInputArray(), $options); return new SdkResponse($result->data, $result->meta, $result->raw); }
    /** List allocation policies. Archived policies are excluded unless you filter by status archived.
     * @param array<array-key, mixed>|Model|null $params Flat body fields and query/header parameters; path arguments follow URL order.
     * @return InventoryAllocationPoliciesListResponse200
     */
    public function list(array|Model|null $params = null, ?RequestOptions $options = null): InventoryAllocationPoliciesListResponse200 { $input = []; $params = $params instanceof Model ? $params->toInputArray() : $params; $rest = $params ?? []; if ($rest && array_is_list($rest)) throw new SdkError('validation', 'Expected associative params', 'not_sent'); if (array_key_exists('page_size', $rest)) { $input['page_size'] = $rest['page_size']; unset($rest['page_size']); } if (array_key_exists('page_token', $rest)) { $input['page_token'] = $rest['page_token']; unset($rest['page_token']); } if (array_key_exists('status', $rest)) { $input['status'] = $rest['status']; unset($rest['status']); } if (array_key_exists('external_reference_id', $rest)) { $input['external_reference_id'] = $rest['external_reference_id']; unset($rest['external_reference_id']); } if (array_key_exists('query', $rest)) { $input['query'] = $rest['query']; unset($rest['query']); } if (array_key_exists('Flint-Version', $rest)) { $input['Flint-Version'] = $rest['Flint-Version']; unset($rest['Flint-Version']); } foreach ($rest as $name => $value) { if (array_key_exists($name, $input)) throw new SdkError('validation', 'Path values belong in positional arguments', 'not_sent'); $input[$name] = $value; } return SdkResponse::payload($this->runtime->request('listInventoryAllocationPolicies', $input instanceof InventoryAllocationPoliciesListInput ? $input->toInputArray() : (new InventoryAllocationPoliciesListInput($input))->toInputArray(), $options), []); }
    /** @return SdkResponse<InventoryAllocationPoliciesListResponse200> */
    public function listWithResponse(array|Model|null $params = null, ?RequestOptions $options = null): SdkResponse { $input = []; $params = $params instanceof Model ? $params->toInputArray() : $params; $rest = $params ?? []; if ($rest && array_is_list($rest)) throw new SdkError('validation', 'Expected associative params', 'not_sent'); if (array_key_exists('page_size', $rest)) { $input['page_size'] = $rest['page_size']; unset($rest['page_size']); } if (array_key_exists('page_token', $rest)) { $input['page_token'] = $rest['page_token']; unset($rest['page_token']); } if (array_key_exists('status', $rest)) { $input['status'] = $rest['status']; unset($rest['status']); } if (array_key_exists('external_reference_id', $rest)) { $input['external_reference_id'] = $rest['external_reference_id']; unset($rest['external_reference_id']); } if (array_key_exists('query', $rest)) { $input['query'] = $rest['query']; unset($rest['query']); } if (array_key_exists('Flint-Version', $rest)) { $input['Flint-Version'] = $rest['Flint-Version']; unset($rest['Flint-Version']); } foreach ($rest as $name => $value) { if (array_key_exists($name, $input)) throw new SdkError('validation', 'Path values belong in positional arguments', 'not_sent'); $input[$name] = $value; } $result = $this->runtime->request('listInventoryAllocationPolicies', $input instanceof InventoryAllocationPoliciesListInput ? $input->toInputArray() : (new InventoryAllocationPoliciesListInput($input))->toInputArray(), $options); return new SdkResponse($result->data, $result->meta, $result->raw); }
    /** @return \Generator<int, InventoryAllocationPoliciesListResponse200> */
    public function listPages(array|Model|null $params = null, ?RequestOptions $options = null): \Generator { $input = []; $params = $params instanceof Model ? $params->toInputArray() : $params; $rest = $params ?? []; if ($rest && array_is_list($rest)) throw new SdkError('validation', 'Expected associative params', 'not_sent'); if (array_key_exists('page_size', $rest)) { $input['page_size'] = $rest['page_size']; unset($rest['page_size']); } if (array_key_exists('page_token', $rest)) { $input['page_token'] = $rest['page_token']; unset($rest['page_token']); } if (array_key_exists('status', $rest)) { $input['status'] = $rest['status']; unset($rest['status']); } if (array_key_exists('external_reference_id', $rest)) { $input['external_reference_id'] = $rest['external_reference_id']; unset($rest['external_reference_id']); } if (array_key_exists('query', $rest)) { $input['query'] = $rest['query']; unset($rest['query']); } if (array_key_exists('Flint-Version', $rest)) { $input['Flint-Version'] = $rest['Flint-Version']; unset($rest['Flint-Version']); } foreach ($rest as $name => $value) { if (array_key_exists($name, $input)) throw new SdkError('validation', 'Path values belong in positional arguments', 'not_sent'); $input[$name] = $value; } return SdkResponse::payloadPages($this->runtime->pages('listInventoryAllocationPolicies', $input instanceof InventoryAllocationPoliciesListInput ? $input->toInputArray() : (new InventoryAllocationPoliciesListInput($input))->toInputArray(), $options), []); }
    /** @return \Generator<int, SdkResponse<InventoryAllocationPoliciesListResponse200>> */
    public function listPagesWithResponse(array|Model|null $params = null, ?RequestOptions $options = null): \Generator { $input = []; $params = $params instanceof Model ? $params->toInputArray() : $params; $rest = $params ?? []; if ($rest && array_is_list($rest)) throw new SdkError('validation', 'Expected associative params', 'not_sent'); if (array_key_exists('page_size', $rest)) { $input['page_size'] = $rest['page_size']; unset($rest['page_size']); } if (array_key_exists('page_token', $rest)) { $input['page_token'] = $rest['page_token']; unset($rest['page_token']); } if (array_key_exists('status', $rest)) { $input['status'] = $rest['status']; unset($rest['status']); } if (array_key_exists('external_reference_id', $rest)) { $input['external_reference_id'] = $rest['external_reference_id']; unset($rest['external_reference_id']); } if (array_key_exists('query', $rest)) { $input['query'] = $rest['query']; unset($rest['query']); } if (array_key_exists('Flint-Version', $rest)) { $input['Flint-Version'] = $rest['Flint-Version']; unset($rest['Flint-Version']); } foreach ($rest as $name => $value) { if (array_key_exists($name, $input)) throw new SdkError('validation', 'Path values belong in positional arguments', 'not_sent'); $input[$name] = $value; } return SdkResponse::responsePages($this->runtime->pages('listInventoryAllocationPolicies', $input instanceof InventoryAllocationPoliciesListInput ? $input->toInputArray() : (new InventoryAllocationPoliciesListInput($input))->toInputArray(), $options)); }
    /** @return \Generator<int, InventoryAllocationPolicy> */
    public function listItems(array|Model|null $params = null, ?RequestOptions $options = null): \Generator { $input = []; $params = $params instanceof Model ? $params->toInputArray() : $params; $rest = $params ?? []; if ($rest && array_is_list($rest)) throw new SdkError('validation', 'Expected associative params', 'not_sent'); if (array_key_exists('page_size', $rest)) { $input['page_size'] = $rest['page_size']; unset($rest['page_size']); } if (array_key_exists('page_token', $rest)) { $input['page_token'] = $rest['page_token']; unset($rest['page_token']); } if (array_key_exists('status', $rest)) { $input['status'] = $rest['status']; unset($rest['status']); } if (array_key_exists('external_reference_id', $rest)) { $input['external_reference_id'] = $rest['external_reference_id']; unset($rest['external_reference_id']); } if (array_key_exists('query', $rest)) { $input['query'] = $rest['query']; unset($rest['query']); } if (array_key_exists('Flint-Version', $rest)) { $input['Flint-Version'] = $rest['Flint-Version']; unset($rest['Flint-Version']); } foreach ($rest as $name => $value) { if (array_key_exists($name, $input)) throw new SdkError('validation', 'Path values belong in positional arguments', 'not_sent'); $input[$name] = $value; } return $this->runtime->items('listInventoryAllocationPolicies', $input instanceof InventoryAllocationPoliciesListInput ? $input->toInputArray() : (new InventoryAllocationPoliciesListInput($input))->toInputArray(), $options); }
    /** Update policy fields, availability, or atomically replace its routing configuration. Send expected_version to reject concurrent changes.
     * @param array<array-key, mixed>|Model $params Flat body fields and query/header parameters; path arguments follow URL order.
     * @return InventoryAllocationPolicy
     */
    public function update(string|Model $inventory_allocation_policy_id, array|Model $params, ?RequestOptions $options = null): InventoryAllocationPolicy { $input = ['inventory_allocation_policy_id' => $inventory_allocation_policy_id]; $params = $params instanceof Model ? $params->toInputArray() : $params; $rest = $params ?? []; if ($rest && array_is_list($rest)) throw new SdkError('validation', 'Expected associative params', 'not_sent'); if (array_key_exists('Idempotency-Key', $rest)) { $input['Idempotency-Key'] = $rest['Idempotency-Key']; unset($rest['Idempotency-Key']); } if (array_key_exists('Flint-Version', $rest)) { $input['Flint-Version'] = $rest['Flint-Version']; unset($rest['Flint-Version']); } if (true) $input['body'] = (object) $rest; return SdkResponse::payload($this->runtime->request('updateInventoryAllocationPolicy', $input instanceof InventoryAllocationPoliciesUpdateInput ? $input->toInputArray() : (new InventoryAllocationPoliciesUpdateInput($input))->toInputArray(), $options), ['data']); }
    /** @return SdkResponse<InventoryAllocationPoliciesUpdateResponse200> */
    public function updateWithResponse(string|Model $inventory_allocation_policy_id, array|Model $params, ?RequestOptions $options = null): SdkResponse { $input = ['inventory_allocation_policy_id' => $inventory_allocation_policy_id]; $params = $params instanceof Model ? $params->toInputArray() : $params; $rest = $params ?? []; if ($rest && array_is_list($rest)) throw new SdkError('validation', 'Expected associative params', 'not_sent'); if (array_key_exists('Idempotency-Key', $rest)) { $input['Idempotency-Key'] = $rest['Idempotency-Key']; unset($rest['Idempotency-Key']); } if (array_key_exists('Flint-Version', $rest)) { $input['Flint-Version'] = $rest['Flint-Version']; unset($rest['Flint-Version']); } if (true) $input['body'] = (object) $rest; $result = $this->runtime->request('updateInventoryAllocationPolicy', $input instanceof InventoryAllocationPoliciesUpdateInput ? $input->toInputArray() : (new InventoryAllocationPoliciesUpdateInput($input))->toInputArray(), $options); return new SdkResponse($result->data, $result->meta, $result->raw); }
}
