<?php
declare(strict_types=1);
namespace Flint;
final class InvoicesResource {
    public function __construct(private readonly Runtime $runtime) {}
    /** Assesses the frozen late fee policy once per invoice or overdue schedule entry. The issued document remains unchanged.
     * @param array<array-key, mixed>|Model $params Flat body fields and query/header parameters; path arguments follow URL order.
     * @return Invoice
     */
    public function assessLateFee(string|Model $invoice_id, array|Model $params, ?RequestOptions $options = null): Invoice { $input = ['invoice_id' => $invoice_id]; $params = $params instanceof Model ? $params->toInputArray() : $params; $rest = $params ?? []; if ($rest && array_is_list($rest)) throw new SdkError('validation', 'Expected associative params', 'not_sent'); if (array_key_exists('Idempotency-Key', $rest)) { $input['Idempotency-Key'] = $rest['Idempotency-Key']; unset($rest['Idempotency-Key']); } if (array_key_exists('Flint-Version', $rest)) { $input['Flint-Version'] = $rest['Flint-Version']; unset($rest['Flint-Version']); } if (true) $input['body'] = (object) $rest; return SdkResponse::payload($this->runtime->request('assessInvoiceLateFee', $input instanceof InvoicesAssessLateFeeInput ? $input->toInputArray() : (new InvoicesAssessLateFeeInput($input))->toInputArray(), $options), ['data']); }
    /** @return SdkResponse<InvoicesAssessLateFeeResponse200> */
    public function assessLateFeeWithResponse(string|Model $invoice_id, array|Model $params, ?RequestOptions $options = null): SdkResponse { $input = ['invoice_id' => $invoice_id]; $params = $params instanceof Model ? $params->toInputArray() : $params; $rest = $params ?? []; if ($rest && array_is_list($rest)) throw new SdkError('validation', 'Expected associative params', 'not_sent'); if (array_key_exists('Idempotency-Key', $rest)) { $input['Idempotency-Key'] = $rest['Idempotency-Key']; unset($rest['Idempotency-Key']); } if (array_key_exists('Flint-Version', $rest)) { $input['Flint-Version'] = $rest['Flint-Version']; unset($rest['Flint-Version']); } if (true) $input['body'] = (object) $rest; $result = $this->runtime->request('assessInvoiceLateFee', $input instanceof InvoicesAssessLateFeeInput ? $input->toInputArray() : (new InvoicesAssessLateFeeInput($input))->toInputArray(), $options); return new SdkResponse($result->data, $result->meta, $result->raw); }
    /** Cancels an active invoice payment attempt and its payment intent. Safe to retry with the same Idempotency-Key.
     * @param array<array-key, mixed>|Model|null $params Flat body fields and query/header parameters; path arguments follow URL order.
     * @return InvoicePaymentAttempt
     */
    public function cancelPaymentAttempt(string|Model $invoice_id, string|Model $invoice_payment_attempt_id, array|Model|null $params = null, ?RequestOptions $options = null): InvoicePaymentAttempt { $input = ['invoice_id' => $invoice_id, 'invoice_payment_attempt_id' => $invoice_payment_attempt_id]; $params = $params instanceof Model ? $params->toInputArray() : $params; $rest = $params ?? []; if ($rest && array_is_list($rest)) throw new SdkError('validation', 'Expected associative params', 'not_sent'); if (array_key_exists('Idempotency-Key', $rest)) { $input['Idempotency-Key'] = $rest['Idempotency-Key']; unset($rest['Idempotency-Key']); } if (array_key_exists('X-Request-Id', $rest)) { $input['X-Request-Id'] = $rest['X-Request-Id']; unset($rest['X-Request-Id']); } if (array_key_exists('Flint-Version', $rest)) { $input['Flint-Version'] = $rest['Flint-Version']; unset($rest['Flint-Version']); } foreach ($rest as $name => $value) { if (array_key_exists($name, $input)) throw new SdkError('validation', 'Path values belong in positional arguments', 'not_sent'); $input[$name] = $value; } return SdkResponse::payload($this->runtime->request('cancelInvoicePaymentAttempt', $input instanceof InvoicesCancelPaymentAttemptInput ? $input->toInputArray() : (new InvoicesCancelPaymentAttemptInput($input))->toInputArray(), $options), ['data']); }
    /** @return SdkResponse<InvoicesCancelPaymentAttemptResponse200> */
    public function cancelPaymentAttemptWithResponse(string|Model $invoice_id, string|Model $invoice_payment_attempt_id, array|Model|null $params = null, ?RequestOptions $options = null): SdkResponse { $input = ['invoice_id' => $invoice_id, 'invoice_payment_attempt_id' => $invoice_payment_attempt_id]; $params = $params instanceof Model ? $params->toInputArray() : $params; $rest = $params ?? []; if ($rest && array_is_list($rest)) throw new SdkError('validation', 'Expected associative params', 'not_sent'); if (array_key_exists('Idempotency-Key', $rest)) { $input['Idempotency-Key'] = $rest['Idempotency-Key']; unset($rest['Idempotency-Key']); } if (array_key_exists('X-Request-Id', $rest)) { $input['X-Request-Id'] = $rest['X-Request-Id']; unset($rest['X-Request-Id']); } if (array_key_exists('Flint-Version', $rest)) { $input['Flint-Version'] = $rest['Flint-Version']; unset($rest['Flint-Version']); } foreach ($rest as $name => $value) { if (array_key_exists($name, $input)) throw new SdkError('validation', 'Path values belong in positional arguments', 'not_sent'); $input[$name] = $value; } $result = $this->runtime->request('cancelInvoicePaymentAttempt', $input instanceof InvoicesCancelPaymentAttemptInput ? $input->toInputArray() : (new InvoicesCancelPaymentAttemptInput($input))->toInputArray(), $options); return new SdkResponse($result->data, $result->meta, $result->raw); }
    /** Charges the invoice's saved payment method or the supplied saved payment method. This command requires a caller-chosen Idempotency-Key that is reused for retries of the same collection request.
     * @param array<array-key, mixed>|Model $params Flat body fields and query/header parameters; path arguments follow URL order.
     * @return CollectInvoiceResult
     */
    public function collect(string|Model $invoice_id, array|Model $params, ?RequestOptions $options = null): CollectInvoiceResult { $input = ['invoice_id' => $invoice_id]; $params = $params instanceof Model ? $params->toInputArray() : $params; $rest = $params ?? []; if ($rest && array_is_list($rest)) throw new SdkError('validation', 'Expected associative params', 'not_sent'); if (array_key_exists('Idempotency-Key', $rest)) { $input['Idempotency-Key'] = $rest['Idempotency-Key']; unset($rest['Idempotency-Key']); } if (array_key_exists('X-Request-Id', $rest)) { $input['X-Request-Id'] = $rest['X-Request-Id']; unset($rest['X-Request-Id']); } if (array_key_exists('Flint-Version', $rest)) { $input['Flint-Version'] = $rest['Flint-Version']; unset($rest['Flint-Version']); } if (true) $input['body'] = (object) $rest; return SdkResponse::payload($this->runtime->request('collectInvoice', $input instanceof InvoicesCollectInput ? $input->toInputArray() : (new InvoicesCollectInput($input))->toInputArray(), $options), ['data']); }
    /** @return SdkResponse<InvoicesCollectResponse200> */
    public function collectWithResponse(string|Model $invoice_id, array|Model $params, ?RequestOptions $options = null): SdkResponse { $input = ['invoice_id' => $invoice_id]; $params = $params instanceof Model ? $params->toInputArray() : $params; $rest = $params ?? []; if ($rest && array_is_list($rest)) throw new SdkError('validation', 'Expected associative params', 'not_sent'); if (array_key_exists('Idempotency-Key', $rest)) { $input['Idempotency-Key'] = $rest['Idempotency-Key']; unset($rest['Idempotency-Key']); } if (array_key_exists('X-Request-Id', $rest)) { $input['X-Request-Id'] = $rest['X-Request-Id']; unset($rest['X-Request-Id']); } if (array_key_exists('Flint-Version', $rest)) { $input['Flint-Version'] = $rest['Flint-Version']; unset($rest['Flint-Version']); } if (true) $input['body'] = (object) $rest; $result = $this->runtime->request('collectInvoice', $input instanceof InvoicesCollectInput ? $input->toInputArray() : (new InvoicesCollectInput($input))->toInputArray(), $options); return new SdkResponse($result->data, $result->meta, $result->raw); }
    /** Creates an invoice draft. Provide exactly one source: order_id for an order-backed draft, or quick_pay for a hidden backing-order draft.
     * @param array<array-key, mixed>|Model $params Flat body fields and query/header parameters; path arguments follow URL order.
     * @return Invoice
     */
    public function create(array|Model $params, ?RequestOptions $options = null): Invoice { $input = []; $params = $params instanceof Model ? $params->toInputArray() : $params; $rest = $params ?? []; if ($rest && array_is_list($rest)) throw new SdkError('validation', 'Expected associative params', 'not_sent'); if (array_key_exists('Idempotency-Key', $rest)) { $input['Idempotency-Key'] = $rest['Idempotency-Key']; unset($rest['Idempotency-Key']); } if (array_key_exists('X-Request-Id', $rest)) { $input['X-Request-Id'] = $rest['X-Request-Id']; unset($rest['X-Request-Id']); } if (array_key_exists('Flint-Version', $rest)) { $input['Flint-Version'] = $rest['Flint-Version']; unset($rest['Flint-Version']); } if (true) $input['body'] = (object) $rest; return SdkResponse::payload($this->runtime->request('createInvoice', $input instanceof InvoicesCreateInput ? $input->toInputArray() : (new InvoicesCreateInput($input))->toInputArray(), $options), ['data']); }
    /** @return SdkResponse<InvoicesCreateResponse201> */
    public function createWithResponse(array|Model $params, ?RequestOptions $options = null): SdkResponse { $input = []; $params = $params instanceof Model ? $params->toInputArray() : $params; $rest = $params ?? []; if ($rest && array_is_list($rest)) throw new SdkError('validation', 'Expected associative params', 'not_sent'); if (array_key_exists('Idempotency-Key', $rest)) { $input['Idempotency-Key'] = $rest['Idempotency-Key']; unset($rest['Idempotency-Key']); } if (array_key_exists('X-Request-Id', $rest)) { $input['X-Request-Id'] = $rest['X-Request-Id']; unset($rest['X-Request-Id']); } if (array_key_exists('Flint-Version', $rest)) { $input['Flint-Version'] = $rest['Flint-Version']; unset($rest['Flint-Version']); } if (true) $input['body'] = (object) $rest; $result = $this->runtime->request('createInvoice', $input instanceof InvoicesCreateInput ? $input->toInputArray() : (new InvoicesCreateInput($input))->toInputArray(), $options); return new SdkResponse($result->data, $result->meta, $result->raw); }
    /** Returns a single invoice by ID.
     * @param array<array-key, mixed>|Model|null $params Flat body fields and query/header parameters; path arguments follow URL order.
     * @return Invoice
     */
    public function get(string|Model $invoice_id, array|Model|null $params = null, ?RequestOptions $options = null): Invoice { $input = ['invoice_id' => $invoice_id]; $params = $params instanceof Model ? $params->toInputArray() : $params; $rest = $params ?? []; if ($rest && array_is_list($rest)) throw new SdkError('validation', 'Expected associative params', 'not_sent'); if (array_key_exists('expand', $rest)) { $input['expand'] = $rest['expand']; unset($rest['expand']); } if (array_key_exists('Flint-Version', $rest)) { $input['Flint-Version'] = $rest['Flint-Version']; unset($rest['Flint-Version']); } foreach ($rest as $name => $value) { if (array_key_exists($name, $input)) throw new SdkError('validation', 'Path values belong in positional arguments', 'not_sent'); $input[$name] = $value; } return SdkResponse::payload($this->runtime->request('getInvoice', $input instanceof InvoicesGetInput ? $input->toInputArray() : (new InvoicesGetInput($input))->toInputArray(), $options), ['data']); }
    /** @return SdkResponse<InvoicesGetResponse200> */
    public function getWithResponse(string|Model $invoice_id, array|Model|null $params = null, ?RequestOptions $options = null): SdkResponse { $input = ['invoice_id' => $invoice_id]; $params = $params instanceof Model ? $params->toInputArray() : $params; $rest = $params ?? []; if ($rest && array_is_list($rest)) throw new SdkError('validation', 'Expected associative params', 'not_sent'); if (array_key_exists('expand', $rest)) { $input['expand'] = $rest['expand']; unset($rest['expand']); } if (array_key_exists('Flint-Version', $rest)) { $input['Flint-Version'] = $rest['Flint-Version']; unset($rest['Flint-Version']); } foreach ($rest as $name => $value) { if (array_key_exists($name, $input)) throw new SdkError('validation', 'Path values belong in positional arguments', 'not_sent'); $input[$name] = $value; } $result = $this->runtime->request('getInvoice', $input instanceof InvoicesGetInput ? $input->toInputArray() : (new InvoicesGetInput($input))->toInputArray(), $options); return new SdkResponse($result->data, $result->meta, $result->raw); }
    /** Returns one card or ACH collection attempt for the invoice.
     * @param array<array-key, mixed>|Model|null $params Flat body fields and query/header parameters; path arguments follow URL order.
     * @return InvoicePaymentAttempt
     */
    public function getPaymentAttempt(string|Model $invoice_id, string|Model $invoice_payment_attempt_id, array|Model|null $params = null, ?RequestOptions $options = null): InvoicePaymentAttempt { $input = ['invoice_id' => $invoice_id, 'invoice_payment_attempt_id' => $invoice_payment_attempt_id]; $params = $params instanceof Model ? $params->toInputArray() : $params; $rest = $params ?? []; if ($rest && array_is_list($rest)) throw new SdkError('validation', 'Expected associative params', 'not_sent'); if (array_key_exists('Flint-Version', $rest)) { $input['Flint-Version'] = $rest['Flint-Version']; unset($rest['Flint-Version']); } foreach ($rest as $name => $value) { if (array_key_exists($name, $input)) throw new SdkError('validation', 'Path values belong in positional arguments', 'not_sent'); $input[$name] = $value; } return SdkResponse::payload($this->runtime->request('getInvoicePaymentAttempt', $input instanceof InvoicesGetPaymentAttemptInput ? $input->toInputArray() : (new InvoicesGetPaymentAttemptInput($input))->toInputArray(), $options), ['data']); }
    /** @return SdkResponse<InvoicesGetPaymentAttemptResponse200> */
    public function getPaymentAttemptWithResponse(string|Model $invoice_id, string|Model $invoice_payment_attempt_id, array|Model|null $params = null, ?RequestOptions $options = null): SdkResponse { $input = ['invoice_id' => $invoice_id, 'invoice_payment_attempt_id' => $invoice_payment_attempt_id]; $params = $params instanceof Model ? $params->toInputArray() : $params; $rest = $params ?? []; if ($rest && array_is_list($rest)) throw new SdkError('validation', 'Expected associative params', 'not_sent'); if (array_key_exists('Flint-Version', $rest)) { $input['Flint-Version'] = $rest['Flint-Version']; unset($rest['Flint-Version']); } foreach ($rest as $name => $value) { if (array_key_exists($name, $input)) throw new SdkError('validation', 'Path values belong in positional arguments', 'not_sent'); $input[$name] = $value; } $result = $this->runtime->request('getInvoicePaymentAttempt', $input instanceof InvoicesGetPaymentAttemptInput ? $input->toInputArray() : (new InvoicesGetPaymentAttemptInput($input))->toInputArray(), $options); return new SdkResponse($result->data, $result->meta, $result->raw); }
    /** Downloads the merchant-authenticated PDF artifact generated from the invoice snapshot.
     * @param array<array-key, mixed>|Model|null $params Flat body fields and query/header parameters; path arguments follow URL order.
     * @return Result<string>
     */
    public function getPDF(string|Model $invoice_id, array|Model|null $params = null, ?RequestOptions $options = null): Result { $input = ['invoice_id' => $invoice_id]; $params = $params instanceof Model ? $params->toInputArray() : $params; $rest = $params ?? []; if ($rest && array_is_list($rest)) throw new SdkError('validation', 'Expected associative params', 'not_sent'); if (array_key_exists('Flint-Version', $rest)) { $input['Flint-Version'] = $rest['Flint-Version']; unset($rest['Flint-Version']); } foreach ($rest as $name => $value) { if (array_key_exists($name, $input)) throw new SdkError('validation', 'Path values belong in positional arguments', 'not_sent'); $input[$name] = $value; } return $this->runtime->request('getInvoicePDF', $input instanceof InvoicesGetPDFInput ? $input->toInputArray() : (new InvoicesGetPDFInput($input))->toInputArray(), $options); }
    /** Returns the current open invoice checkout session and aligned card attempt when they still match the invoice balance and collection run. A newly created session and attempt share the fixed expiration of the active invoice public-link generation. Unexpired sessions are reused regardless of remaining lifetime; active payment work returns a resolving conflict instead of creating competing collection. When the invoice's order has items to deliver, a new session offers the delivery methods in settings.checkout.default_delivery_method_ids, and the request fails with a validation error when those methods cannot deliver every item. return_url sets where the checkout sends the buyer after paying. A reused session takes a new return_url only until a payment starts on it, and keeps the one it has after that.
     * @param array<array-key, mixed>|Model|null $params Flat body fields and query/header parameters; path arguments follow URL order.
     * @return InvoiceCheckoutSessionResult
     */
    public function getOrCreateCheckoutSession(string|Model $invoice_id, array|Model|null $params = null, ?RequestOptions $options = null): InvoiceCheckoutSessionResult { $input = ['invoice_id' => $invoice_id]; $params = $params instanceof Model ? $params->toInputArray() : $params; $rest = $params ?? []; if ($rest && array_is_list($rest)) throw new SdkError('validation', 'Expected associative params', 'not_sent'); if (array_key_exists('Idempotency-Key', $rest)) { $input['Idempotency-Key'] = $rest['Idempotency-Key']; unset($rest['Idempotency-Key']); } if (array_key_exists('X-Request-Id', $rest)) { $input['X-Request-Id'] = $rest['X-Request-Id']; unset($rest['X-Request-Id']); } if (array_key_exists('Flint-Version', $rest)) { $input['Flint-Version'] = $rest['Flint-Version']; unset($rest['Flint-Version']); } if ($params !== null && (!$params || $rest)) $input['body'] = (object) $rest; return SdkResponse::payload($this->runtime->request('getOrCreateInvoiceCheckoutSession', $input instanceof InvoicesGetOrCreateCheckoutSessionInput ? $input->toInputArray() : (new InvoicesGetOrCreateCheckoutSessionInput($input))->toInputArray(), $options), ['data']); }
    /** @return SdkResponse<InvoicesGetOrCreateCheckoutSessionResponse200|InvoicesGetOrCreateCheckoutSessionResponse201> */
    public function getOrCreateCheckoutSessionWithResponse(string|Model $invoice_id, array|Model|null $params = null, ?RequestOptions $options = null): SdkResponse { $input = ['invoice_id' => $invoice_id]; $params = $params instanceof Model ? $params->toInputArray() : $params; $rest = $params ?? []; if ($rest && array_is_list($rest)) throw new SdkError('validation', 'Expected associative params', 'not_sent'); if (array_key_exists('Idempotency-Key', $rest)) { $input['Idempotency-Key'] = $rest['Idempotency-Key']; unset($rest['Idempotency-Key']); } if (array_key_exists('X-Request-Id', $rest)) { $input['X-Request-Id'] = $rest['X-Request-Id']; unset($rest['X-Request-Id']); } if (array_key_exists('Flint-Version', $rest)) { $input['Flint-Version'] = $rest['Flint-Version']; unset($rest['Flint-Version']); } if ($params !== null && (!$params || $rest)) $input['body'] = (object) $rest; $result = $this->runtime->request('getOrCreateInvoiceCheckoutSession', $input instanceof InvoicesGetOrCreateCheckoutSessionInput ? $input->toInputArray() : (new InvoicesGetOrCreateCheckoutSessionInput($input))->toInputArray(), $options); return new SdkResponse($result->data, $result->meta, $result->raw); }
    /** Issues the invoice, creates the buyer-access link, and uses the selected delivery mode. Safe to retry with the same Idempotency-Key.
     * @param array<array-key, mixed>|Model $params Flat body fields and query/header parameters; path arguments follow URL order.
     * @return IssueInvoiceResult
     */
    public function issue(string|Model $invoice_id, array|Model $params, ?RequestOptions $options = null): IssueInvoiceResult { $input = ['invoice_id' => $invoice_id]; $params = $params instanceof Model ? $params->toInputArray() : $params; $rest = $params ?? []; if ($rest && array_is_list($rest)) throw new SdkError('validation', 'Expected associative params', 'not_sent'); if (array_key_exists('Idempotency-Key', $rest)) { $input['Idempotency-Key'] = $rest['Idempotency-Key']; unset($rest['Idempotency-Key']); } if (array_key_exists('X-Request-Id', $rest)) { $input['X-Request-Id'] = $rest['X-Request-Id']; unset($rest['X-Request-Id']); } if (array_key_exists('Flint-Version', $rest)) { $input['Flint-Version'] = $rest['Flint-Version']; unset($rest['Flint-Version']); } if (true) $input['body'] = (object) $rest; return SdkResponse::payload($this->runtime->request('issueInvoice', $input instanceof InvoicesIssueInput ? $input->toInputArray() : (new InvoicesIssueInput($input))->toInputArray(), $options), ['data']); }
    /** @return SdkResponse<InvoicesIssueResponse200> */
    public function issueWithResponse(string|Model $invoice_id, array|Model $params, ?RequestOptions $options = null): SdkResponse { $input = ['invoice_id' => $invoice_id]; $params = $params instanceof Model ? $params->toInputArray() : $params; $rest = $params ?? []; if ($rest && array_is_list($rest)) throw new SdkError('validation', 'Expected associative params', 'not_sent'); if (array_key_exists('Idempotency-Key', $rest)) { $input['Idempotency-Key'] = $rest['Idempotency-Key']; unset($rest['Idempotency-Key']); } if (array_key_exists('X-Request-Id', $rest)) { $input['X-Request-Id'] = $rest['X-Request-Id']; unset($rest['X-Request-Id']); } if (array_key_exists('Flint-Version', $rest)) { $input['Flint-Version'] = $rest['Flint-Version']; unset($rest['Flint-Version']); } if (true) $input['body'] = (object) $rest; $result = $this->runtime->request('issueInvoice', $input instanceof InvoicesIssueInput ? $input->toInputArray() : (new InvoicesIssueInput($input))->toInputArray(), $options); return new SdkResponse($result->data, $result->meta, $result->raw); }
    /** Returns a read-only history of an invoice for timelines and debugging, newest first. Use sort_direction=asc for chronological order. Read the invoice and the resources each row references for authoritative state.
     * @param array<array-key, mixed>|Model|null $params Flat body fields and query/header parameters; path arguments follow URL order.
     * @return InvoicesListActivitiesResponse200
     */
    public function listActivities(string|Model $invoice_id, array|Model|null $params = null, ?RequestOptions $options = null): InvoicesListActivitiesResponse200 { $input = ['invoice_id' => $invoice_id]; $params = $params instanceof Model ? $params->toInputArray() : $params; $rest = $params ?? []; if ($rest && array_is_list($rest)) throw new SdkError('validation', 'Expected associative params', 'not_sent'); if (array_key_exists('page_size', $rest)) { $input['page_size'] = $rest['page_size']; unset($rest['page_size']); } if (array_key_exists('page_token', $rest)) { $input['page_token'] = $rest['page_token']; unset($rest['page_token']); } if (array_key_exists('sort_direction', $rest)) { $input['sort_direction'] = $rest['sort_direction']; unset($rest['sort_direction']); } if (array_key_exists('type', $rest)) { $input['type'] = $rest['type']; unset($rest['type']); } if (array_key_exists('Flint-Version', $rest)) { $input['Flint-Version'] = $rest['Flint-Version']; unset($rest['Flint-Version']); } foreach ($rest as $name => $value) { if (array_key_exists($name, $input)) throw new SdkError('validation', 'Path values belong in positional arguments', 'not_sent'); $input[$name] = $value; } return SdkResponse::payload($this->runtime->request('listInvoiceActivities', $input instanceof InvoicesListActivitiesInput ? $input->toInputArray() : (new InvoicesListActivitiesInput($input))->toInputArray(), $options), []); }
    /** @return SdkResponse<InvoicesListActivitiesResponse200> */
    public function listActivitiesWithResponse(string|Model $invoice_id, array|Model|null $params = null, ?RequestOptions $options = null): SdkResponse { $input = ['invoice_id' => $invoice_id]; $params = $params instanceof Model ? $params->toInputArray() : $params; $rest = $params ?? []; if ($rest && array_is_list($rest)) throw new SdkError('validation', 'Expected associative params', 'not_sent'); if (array_key_exists('page_size', $rest)) { $input['page_size'] = $rest['page_size']; unset($rest['page_size']); } if (array_key_exists('page_token', $rest)) { $input['page_token'] = $rest['page_token']; unset($rest['page_token']); } if (array_key_exists('sort_direction', $rest)) { $input['sort_direction'] = $rest['sort_direction']; unset($rest['sort_direction']); } if (array_key_exists('type', $rest)) { $input['type'] = $rest['type']; unset($rest['type']); } if (array_key_exists('Flint-Version', $rest)) { $input['Flint-Version'] = $rest['Flint-Version']; unset($rest['Flint-Version']); } foreach ($rest as $name => $value) { if (array_key_exists($name, $input)) throw new SdkError('validation', 'Path values belong in positional arguments', 'not_sent'); $input[$name] = $value; } $result = $this->runtime->request('listInvoiceActivities', $input instanceof InvoicesListActivitiesInput ? $input->toInputArray() : (new InvoicesListActivitiesInput($input))->toInputArray(), $options); return new SdkResponse($result->data, $result->meta, $result->raw); }
    /** @return \Generator<int, InvoicesListActivitiesResponse200> */
    public function listActivitiesPages(string|Model $invoice_id, array|Model|null $params = null, ?RequestOptions $options = null): \Generator { $input = ['invoice_id' => $invoice_id]; $params = $params instanceof Model ? $params->toInputArray() : $params; $rest = $params ?? []; if ($rest && array_is_list($rest)) throw new SdkError('validation', 'Expected associative params', 'not_sent'); if (array_key_exists('page_size', $rest)) { $input['page_size'] = $rest['page_size']; unset($rest['page_size']); } if (array_key_exists('page_token', $rest)) { $input['page_token'] = $rest['page_token']; unset($rest['page_token']); } if (array_key_exists('sort_direction', $rest)) { $input['sort_direction'] = $rest['sort_direction']; unset($rest['sort_direction']); } if (array_key_exists('type', $rest)) { $input['type'] = $rest['type']; unset($rest['type']); } if (array_key_exists('Flint-Version', $rest)) { $input['Flint-Version'] = $rest['Flint-Version']; unset($rest['Flint-Version']); } foreach ($rest as $name => $value) { if (array_key_exists($name, $input)) throw new SdkError('validation', 'Path values belong in positional arguments', 'not_sent'); $input[$name] = $value; } return SdkResponse::payloadPages($this->runtime->pages('listInvoiceActivities', $input instanceof InvoicesListActivitiesInput ? $input->toInputArray() : (new InvoicesListActivitiesInput($input))->toInputArray(), $options), []); }
    /** @return \Generator<int, SdkResponse<InvoicesListActivitiesResponse200>> */
    public function listActivitiesPagesWithResponse(string|Model $invoice_id, array|Model|null $params = null, ?RequestOptions $options = null): \Generator { $input = ['invoice_id' => $invoice_id]; $params = $params instanceof Model ? $params->toInputArray() : $params; $rest = $params ?? []; if ($rest && array_is_list($rest)) throw new SdkError('validation', 'Expected associative params', 'not_sent'); if (array_key_exists('page_size', $rest)) { $input['page_size'] = $rest['page_size']; unset($rest['page_size']); } if (array_key_exists('page_token', $rest)) { $input['page_token'] = $rest['page_token']; unset($rest['page_token']); } if (array_key_exists('sort_direction', $rest)) { $input['sort_direction'] = $rest['sort_direction']; unset($rest['sort_direction']); } if (array_key_exists('type', $rest)) { $input['type'] = $rest['type']; unset($rest['type']); } if (array_key_exists('Flint-Version', $rest)) { $input['Flint-Version'] = $rest['Flint-Version']; unset($rest['Flint-Version']); } foreach ($rest as $name => $value) { if (array_key_exists($name, $input)) throw new SdkError('validation', 'Path values belong in positional arguments', 'not_sent'); $input[$name] = $value; } return SdkResponse::responsePages($this->runtime->pages('listInvoiceActivities', $input instanceof InvoicesListActivitiesInput ? $input->toInputArray() : (new InvoicesListActivitiesInput($input))->toInputArray(), $options)); }
    /** @return \Generator<int, InvoiceActivity> */
    public function listActivitiesItems(string|Model $invoice_id, array|Model|null $params = null, ?RequestOptions $options = null): \Generator { $input = ['invoice_id' => $invoice_id]; $params = $params instanceof Model ? $params->toInputArray() : $params; $rest = $params ?? []; if ($rest && array_is_list($rest)) throw new SdkError('validation', 'Expected associative params', 'not_sent'); if (array_key_exists('page_size', $rest)) { $input['page_size'] = $rest['page_size']; unset($rest['page_size']); } if (array_key_exists('page_token', $rest)) { $input['page_token'] = $rest['page_token']; unset($rest['page_token']); } if (array_key_exists('sort_direction', $rest)) { $input['sort_direction'] = $rest['sort_direction']; unset($rest['sort_direction']); } if (array_key_exists('type', $rest)) { $input['type'] = $rest['type']; unset($rest['type']); } if (array_key_exists('Flint-Version', $rest)) { $input['Flint-Version'] = $rest['Flint-Version']; unset($rest['Flint-Version']); } foreach ($rest as $name => $value) { if (array_key_exists($name, $input)) throw new SdkError('validation', 'Path values belong in positional arguments', 'not_sent'); $input[$name] = $value; } return $this->runtime->items('listInvoiceActivities', $input instanceof InvoicesListActivitiesInput ? $input->toInputArray() : (new InvoicesListActivitiesInput($input))->toInputArray(), $options); }
    /** Returns email delivery attempts for send and reminder actions.
     * @param array<array-key, mixed>|Model|null $params Flat body fields and query/header parameters; path arguments follow URL order.
     * @return InvoicesListDeliveryAttemptsResponse200
     */
    public function listDeliveryAttempts(string|Model $invoice_id, array|Model|null $params = null, ?RequestOptions $options = null): InvoicesListDeliveryAttemptsResponse200 { $input = ['invoice_id' => $invoice_id]; $params = $params instanceof Model ? $params->toInputArray() : $params; $rest = $params ?? []; if ($rest && array_is_list($rest)) throw new SdkError('validation', 'Expected associative params', 'not_sent'); if (array_key_exists('page_size', $rest)) { $input['page_size'] = $rest['page_size']; unset($rest['page_size']); } if (array_key_exists('page_token', $rest)) { $input['page_token'] = $rest['page_token']; unset($rest['page_token']); } if (array_key_exists('Flint-Version', $rest)) { $input['Flint-Version'] = $rest['Flint-Version']; unset($rest['Flint-Version']); } foreach ($rest as $name => $value) { if (array_key_exists($name, $input)) throw new SdkError('validation', 'Path values belong in positional arguments', 'not_sent'); $input[$name] = $value; } return SdkResponse::payload($this->runtime->request('listInvoiceDeliveryAttempts', $input instanceof InvoicesListDeliveryAttemptsInput ? $input->toInputArray() : (new InvoicesListDeliveryAttemptsInput($input))->toInputArray(), $options), []); }
    /** @return SdkResponse<InvoicesListDeliveryAttemptsResponse200> */
    public function listDeliveryAttemptsWithResponse(string|Model $invoice_id, array|Model|null $params = null, ?RequestOptions $options = null): SdkResponse { $input = ['invoice_id' => $invoice_id]; $params = $params instanceof Model ? $params->toInputArray() : $params; $rest = $params ?? []; if ($rest && array_is_list($rest)) throw new SdkError('validation', 'Expected associative params', 'not_sent'); if (array_key_exists('page_size', $rest)) { $input['page_size'] = $rest['page_size']; unset($rest['page_size']); } if (array_key_exists('page_token', $rest)) { $input['page_token'] = $rest['page_token']; unset($rest['page_token']); } if (array_key_exists('Flint-Version', $rest)) { $input['Flint-Version'] = $rest['Flint-Version']; unset($rest['Flint-Version']); } foreach ($rest as $name => $value) { if (array_key_exists($name, $input)) throw new SdkError('validation', 'Path values belong in positional arguments', 'not_sent'); $input[$name] = $value; } $result = $this->runtime->request('listInvoiceDeliveryAttempts', $input instanceof InvoicesListDeliveryAttemptsInput ? $input->toInputArray() : (new InvoicesListDeliveryAttemptsInput($input))->toInputArray(), $options); return new SdkResponse($result->data, $result->meta, $result->raw); }
    /** @return \Generator<int, InvoicesListDeliveryAttemptsResponse200> */
    public function listDeliveryAttemptsPages(string|Model $invoice_id, array|Model|null $params = null, ?RequestOptions $options = null): \Generator { $input = ['invoice_id' => $invoice_id]; $params = $params instanceof Model ? $params->toInputArray() : $params; $rest = $params ?? []; if ($rest && array_is_list($rest)) throw new SdkError('validation', 'Expected associative params', 'not_sent'); if (array_key_exists('page_size', $rest)) { $input['page_size'] = $rest['page_size']; unset($rest['page_size']); } if (array_key_exists('page_token', $rest)) { $input['page_token'] = $rest['page_token']; unset($rest['page_token']); } if (array_key_exists('Flint-Version', $rest)) { $input['Flint-Version'] = $rest['Flint-Version']; unset($rest['Flint-Version']); } foreach ($rest as $name => $value) { if (array_key_exists($name, $input)) throw new SdkError('validation', 'Path values belong in positional arguments', 'not_sent'); $input[$name] = $value; } return SdkResponse::payloadPages($this->runtime->pages('listInvoiceDeliveryAttempts', $input instanceof InvoicesListDeliveryAttemptsInput ? $input->toInputArray() : (new InvoicesListDeliveryAttemptsInput($input))->toInputArray(), $options), []); }
    /** @return \Generator<int, SdkResponse<InvoicesListDeliveryAttemptsResponse200>> */
    public function listDeliveryAttemptsPagesWithResponse(string|Model $invoice_id, array|Model|null $params = null, ?RequestOptions $options = null): \Generator { $input = ['invoice_id' => $invoice_id]; $params = $params instanceof Model ? $params->toInputArray() : $params; $rest = $params ?? []; if ($rest && array_is_list($rest)) throw new SdkError('validation', 'Expected associative params', 'not_sent'); if (array_key_exists('page_size', $rest)) { $input['page_size'] = $rest['page_size']; unset($rest['page_size']); } if (array_key_exists('page_token', $rest)) { $input['page_token'] = $rest['page_token']; unset($rest['page_token']); } if (array_key_exists('Flint-Version', $rest)) { $input['Flint-Version'] = $rest['Flint-Version']; unset($rest['Flint-Version']); } foreach ($rest as $name => $value) { if (array_key_exists($name, $input)) throw new SdkError('validation', 'Path values belong in positional arguments', 'not_sent'); $input[$name] = $value; } return SdkResponse::responsePages($this->runtime->pages('listInvoiceDeliveryAttempts', $input instanceof InvoicesListDeliveryAttemptsInput ? $input->toInputArray() : (new InvoicesListDeliveryAttemptsInput($input))->toInputArray(), $options)); }
    /** @return \Generator<int, InvoiceDeliveryAttempt> */
    public function listDeliveryAttemptsItems(string|Model $invoice_id, array|Model|null $params = null, ?RequestOptions $options = null): \Generator { $input = ['invoice_id' => $invoice_id]; $params = $params instanceof Model ? $params->toInputArray() : $params; $rest = $params ?? []; if ($rest && array_is_list($rest)) throw new SdkError('validation', 'Expected associative params', 'not_sent'); if (array_key_exists('page_size', $rest)) { $input['page_size'] = $rest['page_size']; unset($rest['page_size']); } if (array_key_exists('page_token', $rest)) { $input['page_token'] = $rest['page_token']; unset($rest['page_token']); } if (array_key_exists('Flint-Version', $rest)) { $input['Flint-Version'] = $rest['Flint-Version']; unset($rest['Flint-Version']); } foreach ($rest as $name => $value) { if (array_key_exists($name, $input)) throw new SdkError('validation', 'Path values belong in positional arguments', 'not_sent'); $input[$name] = $value; } return $this->runtime->items('listInvoiceDeliveryAttempts', $input instanceof InvoicesListDeliveryAttemptsInput ? $input->toInputArray() : (new InvoicesListDeliveryAttemptsInput($input))->toInputArray(), $options); }
    /** Lists card and ACH collection attempts for an invoice in reverse chronological order.
     * @param array<array-key, mixed>|Model|null $params Flat body fields and query/header parameters; path arguments follow URL order.
     * @return InvoicesListPaymentAttemptsResponse200
     */
    public function listPaymentAttempts(string|Model $invoice_id, array|Model|null $params = null, ?RequestOptions $options = null): InvoicesListPaymentAttemptsResponse200 { $input = ['invoice_id' => $invoice_id]; $params = $params instanceof Model ? $params->toInputArray() : $params; $rest = $params ?? []; if ($rest && array_is_list($rest)) throw new SdkError('validation', 'Expected associative params', 'not_sent'); if (array_key_exists('page_size', $rest)) { $input['page_size'] = $rest['page_size']; unset($rest['page_size']); } if (array_key_exists('page_token', $rest)) { $input['page_token'] = $rest['page_token']; unset($rest['page_token']); } if (array_key_exists('idempotency_key', $rest)) { $input['idempotency_key'] = $rest['idempotency_key']; unset($rest['idempotency_key']); } if (array_key_exists('Flint-Version', $rest)) { $input['Flint-Version'] = $rest['Flint-Version']; unset($rest['Flint-Version']); } foreach ($rest as $name => $value) { if (array_key_exists($name, $input)) throw new SdkError('validation', 'Path values belong in positional arguments', 'not_sent'); $input[$name] = $value; } return SdkResponse::payload($this->runtime->request('listInvoicePaymentAttempts', $input instanceof InvoicesListPaymentAttemptsInput ? $input->toInputArray() : (new InvoicesListPaymentAttemptsInput($input))->toInputArray(), $options), []); }
    /** @return SdkResponse<InvoicesListPaymentAttemptsResponse200> */
    public function listPaymentAttemptsWithResponse(string|Model $invoice_id, array|Model|null $params = null, ?RequestOptions $options = null): SdkResponse { $input = ['invoice_id' => $invoice_id]; $params = $params instanceof Model ? $params->toInputArray() : $params; $rest = $params ?? []; if ($rest && array_is_list($rest)) throw new SdkError('validation', 'Expected associative params', 'not_sent'); if (array_key_exists('page_size', $rest)) { $input['page_size'] = $rest['page_size']; unset($rest['page_size']); } if (array_key_exists('page_token', $rest)) { $input['page_token'] = $rest['page_token']; unset($rest['page_token']); } if (array_key_exists('idempotency_key', $rest)) { $input['idempotency_key'] = $rest['idempotency_key']; unset($rest['idempotency_key']); } if (array_key_exists('Flint-Version', $rest)) { $input['Flint-Version'] = $rest['Flint-Version']; unset($rest['Flint-Version']); } foreach ($rest as $name => $value) { if (array_key_exists($name, $input)) throw new SdkError('validation', 'Path values belong in positional arguments', 'not_sent'); $input[$name] = $value; } $result = $this->runtime->request('listInvoicePaymentAttempts', $input instanceof InvoicesListPaymentAttemptsInput ? $input->toInputArray() : (new InvoicesListPaymentAttemptsInput($input))->toInputArray(), $options); return new SdkResponse($result->data, $result->meta, $result->raw); }
    /** @return \Generator<int, InvoicesListPaymentAttemptsResponse200> */
    public function listPaymentAttemptsPages(string|Model $invoice_id, array|Model|null $params = null, ?RequestOptions $options = null): \Generator { $input = ['invoice_id' => $invoice_id]; $params = $params instanceof Model ? $params->toInputArray() : $params; $rest = $params ?? []; if ($rest && array_is_list($rest)) throw new SdkError('validation', 'Expected associative params', 'not_sent'); if (array_key_exists('page_size', $rest)) { $input['page_size'] = $rest['page_size']; unset($rest['page_size']); } if (array_key_exists('page_token', $rest)) { $input['page_token'] = $rest['page_token']; unset($rest['page_token']); } if (array_key_exists('idempotency_key', $rest)) { $input['idempotency_key'] = $rest['idempotency_key']; unset($rest['idempotency_key']); } if (array_key_exists('Flint-Version', $rest)) { $input['Flint-Version'] = $rest['Flint-Version']; unset($rest['Flint-Version']); } foreach ($rest as $name => $value) { if (array_key_exists($name, $input)) throw new SdkError('validation', 'Path values belong in positional arguments', 'not_sent'); $input[$name] = $value; } return SdkResponse::payloadPages($this->runtime->pages('listInvoicePaymentAttempts', $input instanceof InvoicesListPaymentAttemptsInput ? $input->toInputArray() : (new InvoicesListPaymentAttemptsInput($input))->toInputArray(), $options), []); }
    /** @return \Generator<int, SdkResponse<InvoicesListPaymentAttemptsResponse200>> */
    public function listPaymentAttemptsPagesWithResponse(string|Model $invoice_id, array|Model|null $params = null, ?RequestOptions $options = null): \Generator { $input = ['invoice_id' => $invoice_id]; $params = $params instanceof Model ? $params->toInputArray() : $params; $rest = $params ?? []; if ($rest && array_is_list($rest)) throw new SdkError('validation', 'Expected associative params', 'not_sent'); if (array_key_exists('page_size', $rest)) { $input['page_size'] = $rest['page_size']; unset($rest['page_size']); } if (array_key_exists('page_token', $rest)) { $input['page_token'] = $rest['page_token']; unset($rest['page_token']); } if (array_key_exists('idempotency_key', $rest)) { $input['idempotency_key'] = $rest['idempotency_key']; unset($rest['idempotency_key']); } if (array_key_exists('Flint-Version', $rest)) { $input['Flint-Version'] = $rest['Flint-Version']; unset($rest['Flint-Version']); } foreach ($rest as $name => $value) { if (array_key_exists($name, $input)) throw new SdkError('validation', 'Path values belong in positional arguments', 'not_sent'); $input[$name] = $value; } return SdkResponse::responsePages($this->runtime->pages('listInvoicePaymentAttempts', $input instanceof InvoicesListPaymentAttemptsInput ? $input->toInputArray() : (new InvoicesListPaymentAttemptsInput($input))->toInputArray(), $options)); }
    /** @return \Generator<int, InvoicePaymentAttempt> */
    public function listPaymentAttemptsItems(string|Model $invoice_id, array|Model|null $params = null, ?RequestOptions $options = null): \Generator { $input = ['invoice_id' => $invoice_id]; $params = $params instanceof Model ? $params->toInputArray() : $params; $rest = $params ?? []; if ($rest && array_is_list($rest)) throw new SdkError('validation', 'Expected associative params', 'not_sent'); if (array_key_exists('page_size', $rest)) { $input['page_size'] = $rest['page_size']; unset($rest['page_size']); } if (array_key_exists('page_token', $rest)) { $input['page_token'] = $rest['page_token']; unset($rest['page_token']); } if (array_key_exists('idempotency_key', $rest)) { $input['idempotency_key'] = $rest['idempotency_key']; unset($rest['idempotency_key']); } if (array_key_exists('Flint-Version', $rest)) { $input['Flint-Version'] = $rest['Flint-Version']; unset($rest['Flint-Version']); } foreach ($rest as $name => $value) { if (array_key_exists($name, $input)) throw new SdkError('validation', 'Path values belong in positional arguments', 'not_sent'); $input[$name] = $value; } return $this->runtime->items('listInvoicePaymentAttempts', $input instanceof InvoicesListPaymentAttemptsInput ? $input->toInputArray() : (new InvoicesListPaymentAttemptsInput($input))->toInputArray(), $options); }
    /** Returns a paginated list of invoices for the authenticated merchant.
     * @param array<array-key, mixed>|Model|null $params Flat body fields and query/header parameters; path arguments follow URL order.
     * @return InvoicesListResponse200
     */
    public function list(array|Model|null $params = null, ?RequestOptions $options = null): InvoicesListResponse200 { $input = []; $params = $params instanceof Model ? $params->toInputArray() : $params; $rest = $params ?? []; if ($rest && array_is_list($rest)) throw new SdkError('validation', 'Expected associative params', 'not_sent'); if (array_key_exists('page_size', $rest)) { $input['page_size'] = $rest['page_size']; unset($rest['page_size']); } if (array_key_exists('page_token', $rest)) { $input['page_token'] = $rest['page_token']; unset($rest['page_token']); } if (array_key_exists('status', $rest)) { $input['status'] = $rest['status']; unset($rest['status']); } if (array_key_exists('customer_id', $rest)) { $input['customer_id'] = $rest['customer_id']; unset($rest['customer_id']); } if (array_key_exists('order_id', $rest)) { $input['order_id'] = $rest['order_id']; unset($rest['order_id']); } if (array_key_exists('external_reference_id', $rest)) { $input['external_reference_id'] = $rest['external_reference_id']; unset($rest['external_reference_id']); } if (array_key_exists('created_after', $rest)) { $input['created_after'] = $rest['created_after']; unset($rest['created_after']); } if (array_key_exists('created_before', $rest)) { $input['created_before'] = $rest['created_before']; unset($rest['created_before']); } if (array_key_exists('due_after', $rest)) { $input['due_after'] = $rest['due_after']; unset($rest['due_after']); } if (array_key_exists('due_before', $rest)) { $input['due_before'] = $rest['due_before']; unset($rest['due_before']); } if (array_key_exists('is_overdue', $rest)) { $input['is_overdue'] = $rest['is_overdue']; unset($rest['is_overdue']); } if (array_key_exists('has_amount_due', $rest)) { $input['has_amount_due'] = $rest['has_amount_due']; unset($rest['has_amount_due']); } if (array_key_exists('sort_by', $rest)) { $input['sort_by'] = $rest['sort_by']; unset($rest['sort_by']); } if (array_key_exists('sort_direction', $rest)) { $input['sort_direction'] = $rest['sort_direction']; unset($rest['sort_direction']); } if (array_key_exists('query', $rest)) { $input['query'] = $rest['query']; unset($rest['query']); } if (array_key_exists('Flint-Version', $rest)) { $input['Flint-Version'] = $rest['Flint-Version']; unset($rest['Flint-Version']); } foreach ($rest as $name => $value) { if (array_key_exists($name, $input)) throw new SdkError('validation', 'Path values belong in positional arguments', 'not_sent'); $input[$name] = $value; } return SdkResponse::payload($this->runtime->request('listInvoices', $input instanceof InvoicesListInput ? $input->toInputArray() : (new InvoicesListInput($input))->toInputArray(), $options), []); }
    /** @return SdkResponse<InvoicesListResponse200> */
    public function listWithResponse(array|Model|null $params = null, ?RequestOptions $options = null): SdkResponse { $input = []; $params = $params instanceof Model ? $params->toInputArray() : $params; $rest = $params ?? []; if ($rest && array_is_list($rest)) throw new SdkError('validation', 'Expected associative params', 'not_sent'); if (array_key_exists('page_size', $rest)) { $input['page_size'] = $rest['page_size']; unset($rest['page_size']); } if (array_key_exists('page_token', $rest)) { $input['page_token'] = $rest['page_token']; unset($rest['page_token']); } if (array_key_exists('status', $rest)) { $input['status'] = $rest['status']; unset($rest['status']); } if (array_key_exists('customer_id', $rest)) { $input['customer_id'] = $rest['customer_id']; unset($rest['customer_id']); } if (array_key_exists('order_id', $rest)) { $input['order_id'] = $rest['order_id']; unset($rest['order_id']); } if (array_key_exists('external_reference_id', $rest)) { $input['external_reference_id'] = $rest['external_reference_id']; unset($rest['external_reference_id']); } if (array_key_exists('created_after', $rest)) { $input['created_after'] = $rest['created_after']; unset($rest['created_after']); } if (array_key_exists('created_before', $rest)) { $input['created_before'] = $rest['created_before']; unset($rest['created_before']); } if (array_key_exists('due_after', $rest)) { $input['due_after'] = $rest['due_after']; unset($rest['due_after']); } if (array_key_exists('due_before', $rest)) { $input['due_before'] = $rest['due_before']; unset($rest['due_before']); } if (array_key_exists('is_overdue', $rest)) { $input['is_overdue'] = $rest['is_overdue']; unset($rest['is_overdue']); } if (array_key_exists('has_amount_due', $rest)) { $input['has_amount_due'] = $rest['has_amount_due']; unset($rest['has_amount_due']); } if (array_key_exists('sort_by', $rest)) { $input['sort_by'] = $rest['sort_by']; unset($rest['sort_by']); } if (array_key_exists('sort_direction', $rest)) { $input['sort_direction'] = $rest['sort_direction']; unset($rest['sort_direction']); } if (array_key_exists('query', $rest)) { $input['query'] = $rest['query']; unset($rest['query']); } if (array_key_exists('Flint-Version', $rest)) { $input['Flint-Version'] = $rest['Flint-Version']; unset($rest['Flint-Version']); } foreach ($rest as $name => $value) { if (array_key_exists($name, $input)) throw new SdkError('validation', 'Path values belong in positional arguments', 'not_sent'); $input[$name] = $value; } $result = $this->runtime->request('listInvoices', $input instanceof InvoicesListInput ? $input->toInputArray() : (new InvoicesListInput($input))->toInputArray(), $options); return new SdkResponse($result->data, $result->meta, $result->raw); }
    /** @return \Generator<int, InvoicesListResponse200> */
    public function listPages(array|Model|null $params = null, ?RequestOptions $options = null): \Generator { $input = []; $params = $params instanceof Model ? $params->toInputArray() : $params; $rest = $params ?? []; if ($rest && array_is_list($rest)) throw new SdkError('validation', 'Expected associative params', 'not_sent'); if (array_key_exists('page_size', $rest)) { $input['page_size'] = $rest['page_size']; unset($rest['page_size']); } if (array_key_exists('page_token', $rest)) { $input['page_token'] = $rest['page_token']; unset($rest['page_token']); } if (array_key_exists('status', $rest)) { $input['status'] = $rest['status']; unset($rest['status']); } if (array_key_exists('customer_id', $rest)) { $input['customer_id'] = $rest['customer_id']; unset($rest['customer_id']); } if (array_key_exists('order_id', $rest)) { $input['order_id'] = $rest['order_id']; unset($rest['order_id']); } if (array_key_exists('external_reference_id', $rest)) { $input['external_reference_id'] = $rest['external_reference_id']; unset($rest['external_reference_id']); } if (array_key_exists('created_after', $rest)) { $input['created_after'] = $rest['created_after']; unset($rest['created_after']); } if (array_key_exists('created_before', $rest)) { $input['created_before'] = $rest['created_before']; unset($rest['created_before']); } if (array_key_exists('due_after', $rest)) { $input['due_after'] = $rest['due_after']; unset($rest['due_after']); } if (array_key_exists('due_before', $rest)) { $input['due_before'] = $rest['due_before']; unset($rest['due_before']); } if (array_key_exists('is_overdue', $rest)) { $input['is_overdue'] = $rest['is_overdue']; unset($rest['is_overdue']); } if (array_key_exists('has_amount_due', $rest)) { $input['has_amount_due'] = $rest['has_amount_due']; unset($rest['has_amount_due']); } if (array_key_exists('sort_by', $rest)) { $input['sort_by'] = $rest['sort_by']; unset($rest['sort_by']); } if (array_key_exists('sort_direction', $rest)) { $input['sort_direction'] = $rest['sort_direction']; unset($rest['sort_direction']); } if (array_key_exists('query', $rest)) { $input['query'] = $rest['query']; unset($rest['query']); } if (array_key_exists('Flint-Version', $rest)) { $input['Flint-Version'] = $rest['Flint-Version']; unset($rest['Flint-Version']); } foreach ($rest as $name => $value) { if (array_key_exists($name, $input)) throw new SdkError('validation', 'Path values belong in positional arguments', 'not_sent'); $input[$name] = $value; } return SdkResponse::payloadPages($this->runtime->pages('listInvoices', $input instanceof InvoicesListInput ? $input->toInputArray() : (new InvoicesListInput($input))->toInputArray(), $options), []); }
    /** @return \Generator<int, SdkResponse<InvoicesListResponse200>> */
    public function listPagesWithResponse(array|Model|null $params = null, ?RequestOptions $options = null): \Generator { $input = []; $params = $params instanceof Model ? $params->toInputArray() : $params; $rest = $params ?? []; if ($rest && array_is_list($rest)) throw new SdkError('validation', 'Expected associative params', 'not_sent'); if (array_key_exists('page_size', $rest)) { $input['page_size'] = $rest['page_size']; unset($rest['page_size']); } if (array_key_exists('page_token', $rest)) { $input['page_token'] = $rest['page_token']; unset($rest['page_token']); } if (array_key_exists('status', $rest)) { $input['status'] = $rest['status']; unset($rest['status']); } if (array_key_exists('customer_id', $rest)) { $input['customer_id'] = $rest['customer_id']; unset($rest['customer_id']); } if (array_key_exists('order_id', $rest)) { $input['order_id'] = $rest['order_id']; unset($rest['order_id']); } if (array_key_exists('external_reference_id', $rest)) { $input['external_reference_id'] = $rest['external_reference_id']; unset($rest['external_reference_id']); } if (array_key_exists('created_after', $rest)) { $input['created_after'] = $rest['created_after']; unset($rest['created_after']); } if (array_key_exists('created_before', $rest)) { $input['created_before'] = $rest['created_before']; unset($rest['created_before']); } if (array_key_exists('due_after', $rest)) { $input['due_after'] = $rest['due_after']; unset($rest['due_after']); } if (array_key_exists('due_before', $rest)) { $input['due_before'] = $rest['due_before']; unset($rest['due_before']); } if (array_key_exists('is_overdue', $rest)) { $input['is_overdue'] = $rest['is_overdue']; unset($rest['is_overdue']); } if (array_key_exists('has_amount_due', $rest)) { $input['has_amount_due'] = $rest['has_amount_due']; unset($rest['has_amount_due']); } if (array_key_exists('sort_by', $rest)) { $input['sort_by'] = $rest['sort_by']; unset($rest['sort_by']); } if (array_key_exists('sort_direction', $rest)) { $input['sort_direction'] = $rest['sort_direction']; unset($rest['sort_direction']); } if (array_key_exists('query', $rest)) { $input['query'] = $rest['query']; unset($rest['query']); } if (array_key_exists('Flint-Version', $rest)) { $input['Flint-Version'] = $rest['Flint-Version']; unset($rest['Flint-Version']); } foreach ($rest as $name => $value) { if (array_key_exists($name, $input)) throw new SdkError('validation', 'Path values belong in positional arguments', 'not_sent'); $input[$name] = $value; } return SdkResponse::responsePages($this->runtime->pages('listInvoices', $input instanceof InvoicesListInput ? $input->toInputArray() : (new InvoicesListInput($input))->toInputArray(), $options)); }
    /** @return \Generator<int, Invoice> */
    public function listItems(array|Model|null $params = null, ?RequestOptions $options = null): \Generator { $input = []; $params = $params instanceof Model ? $params->toInputArray() : $params; $rest = $params ?? []; if ($rest && array_is_list($rest)) throw new SdkError('validation', 'Expected associative params', 'not_sent'); if (array_key_exists('page_size', $rest)) { $input['page_size'] = $rest['page_size']; unset($rest['page_size']); } if (array_key_exists('page_token', $rest)) { $input['page_token'] = $rest['page_token']; unset($rest['page_token']); } if (array_key_exists('status', $rest)) { $input['status'] = $rest['status']; unset($rest['status']); } if (array_key_exists('customer_id', $rest)) { $input['customer_id'] = $rest['customer_id']; unset($rest['customer_id']); } if (array_key_exists('order_id', $rest)) { $input['order_id'] = $rest['order_id']; unset($rest['order_id']); } if (array_key_exists('external_reference_id', $rest)) { $input['external_reference_id'] = $rest['external_reference_id']; unset($rest['external_reference_id']); } if (array_key_exists('created_after', $rest)) { $input['created_after'] = $rest['created_after']; unset($rest['created_after']); } if (array_key_exists('created_before', $rest)) { $input['created_before'] = $rest['created_before']; unset($rest['created_before']); } if (array_key_exists('due_after', $rest)) { $input['due_after'] = $rest['due_after']; unset($rest['due_after']); } if (array_key_exists('due_before', $rest)) { $input['due_before'] = $rest['due_before']; unset($rest['due_before']); } if (array_key_exists('is_overdue', $rest)) { $input['is_overdue'] = $rest['is_overdue']; unset($rest['is_overdue']); } if (array_key_exists('has_amount_due', $rest)) { $input['has_amount_due'] = $rest['has_amount_due']; unset($rest['has_amount_due']); } if (array_key_exists('sort_by', $rest)) { $input['sort_by'] = $rest['sort_by']; unset($rest['sort_by']); } if (array_key_exists('sort_direction', $rest)) { $input['sort_direction'] = $rest['sort_direction']; unset($rest['sort_direction']); } if (array_key_exists('query', $rest)) { $input['query'] = $rest['query']; unset($rest['query']); } if (array_key_exists('Flint-Version', $rest)) { $input['Flint-Version'] = $rest['Flint-Version']; unset($rest['Flint-Version']); } foreach ($rest as $name => $value) { if (array_key_exists($name, $input)) throw new SdkError('validation', 'Path values belong in positional arguments', 'not_sent'); $input[$name] = $value; } return $this->runtime->items('listInvoices', $input instanceof InvoicesListInput ? $input->toInputArray() : (new InvoicesListInput($input))->toInputArray(), $options); }
    /** Closes the outstanding balance as a write-off and releases the order's invoice collection authority. Safe to retry with the same Idempotency-Key.
     * @param array<array-key, mixed>|Model|null $params Flat body fields and query/header parameters; path arguments follow URL order.
     * @return Invoice
     */
    public function markUncollectible(string|Model $invoice_id, array|Model|null $params = null, ?RequestOptions $options = null): Invoice { $input = ['invoice_id' => $invoice_id]; $params = $params instanceof Model ? $params->toInputArray() : $params; $rest = $params ?? []; if ($rest && array_is_list($rest)) throw new SdkError('validation', 'Expected associative params', 'not_sent'); if (array_key_exists('Idempotency-Key', $rest)) { $input['Idempotency-Key'] = $rest['Idempotency-Key']; unset($rest['Idempotency-Key']); } if (array_key_exists('X-Request-Id', $rest)) { $input['X-Request-Id'] = $rest['X-Request-Id']; unset($rest['X-Request-Id']); } if (array_key_exists('Flint-Version', $rest)) { $input['Flint-Version'] = $rest['Flint-Version']; unset($rest['Flint-Version']); } if ($params !== null && (!$params || $rest)) $input['body'] = (object) $rest; return SdkResponse::payload($this->runtime->request('markInvoiceUncollectible', $input instanceof InvoicesMarkUncollectibleInput ? $input->toInputArray() : (new InvoicesMarkUncollectibleInput($input))->toInputArray(), $options), ['data']); }
    /** @return SdkResponse<InvoicesMarkUncollectibleResponse200> */
    public function markUncollectibleWithResponse(string|Model $invoice_id, array|Model|null $params = null, ?RequestOptions $options = null): SdkResponse { $input = ['invoice_id' => $invoice_id]; $params = $params instanceof Model ? $params->toInputArray() : $params; $rest = $params ?? []; if ($rest && array_is_list($rest)) throw new SdkError('validation', 'Expected associative params', 'not_sent'); if (array_key_exists('Idempotency-Key', $rest)) { $input['Idempotency-Key'] = $rest['Idempotency-Key']; unset($rest['Idempotency-Key']); } if (array_key_exists('X-Request-Id', $rest)) { $input['X-Request-Id'] = $rest['X-Request-Id']; unset($rest['X-Request-Id']); } if (array_key_exists('Flint-Version', $rest)) { $input['Flint-Version'] = $rest['Flint-Version']; unset($rest['Flint-Version']); } if ($params !== null && (!$params || $rest)) $input['body'] = (object) $rest; $result = $this->runtime->request('markInvoiceUncollectible', $input instanceof InvoicesMarkUncollectibleInput ? $input->toInputArray() : (new InvoicesMarkUncollectibleInput($input))->toInputArray(), $options); return new SdkResponse($result->data, $result->meta, $result->raw); }
    /** Applies an offline/manual payment to an issued invoice. Recording is rejected with INVOICE_PAYMENT_RESOLVING while an online payment is still resolving; an idle open checkout does not block. A payment that clears the balance invalidates the open checkout session. Safe to retry with the same Idempotency-Key.
     * @param array<array-key, mixed>|Model $params Flat body fields and query/header parameters; path arguments follow URL order.
     * @return Invoice
     */
    public function recordManualPayment(string|Model $invoice_id, array|Model $params, ?RequestOptions $options = null): Invoice { $input = ['invoice_id' => $invoice_id]; $params = $params instanceof Model ? $params->toInputArray() : $params; $rest = $params ?? []; if ($rest && array_is_list($rest)) throw new SdkError('validation', 'Expected associative params', 'not_sent'); if (array_key_exists('Idempotency-Key', $rest)) { $input['Idempotency-Key'] = $rest['Idempotency-Key']; unset($rest['Idempotency-Key']); } if (array_key_exists('X-Request-Id', $rest)) { $input['X-Request-Id'] = $rest['X-Request-Id']; unset($rest['X-Request-Id']); } if (array_key_exists('Flint-Version', $rest)) { $input['Flint-Version'] = $rest['Flint-Version']; unset($rest['Flint-Version']); } if (true) $input['body'] = (object) $rest; return SdkResponse::payload($this->runtime->request('recordManualInvoicePayment', $input instanceof InvoicesRecordManualPaymentInput ? $input->toInputArray() : (new InvoicesRecordManualPaymentInput($input))->toInputArray(), $options), ['data']); }
    /** @return SdkResponse<InvoicesRecordManualPaymentResponse200> */
    public function recordManualPaymentWithResponse(string|Model $invoice_id, array|Model $params, ?RequestOptions $options = null): SdkResponse { $input = ['invoice_id' => $invoice_id]; $params = $params instanceof Model ? $params->toInputArray() : $params; $rest = $params ?? []; if ($rest && array_is_list($rest)) throw new SdkError('validation', 'Expected associative params', 'not_sent'); if (array_key_exists('Idempotency-Key', $rest)) { $input['Idempotency-Key'] = $rest['Idempotency-Key']; unset($rest['Idempotency-Key']); } if (array_key_exists('X-Request-Id', $rest)) { $input['X-Request-Id'] = $rest['X-Request-Id']; unset($rest['X-Request-Id']); } if (array_key_exists('Flint-Version', $rest)) { $input['Flint-Version'] = $rest['Flint-Version']; unset($rest['Flint-Version']); } if (true) $input['body'] = (object) $rest; $result = $this->runtime->request('recordManualInvoicePayment', $input instanceof InvoicesRecordManualPaymentInput ? $input->toInputArray() : (new InvoicesRecordManualPaymentInput($input))->toInputArray(), $options); return new SdkResponse($result->data, $result->meta, $result->raw); }
    /** Revokes the current buyer-access link and all checkout credentials derived from it, then returns a new public_url. The current checkout session and its payment lineage are preserved. Safe to retry with the same Idempotency-Key.
     * @param array<array-key, mixed>|Model|null $params Flat body fields and query/header parameters; path arguments follow URL order.
     * @return RegenerateInvoiceLinkResult
     */
    public function regeneratePublicLink(string|Model $invoice_id, array|Model|null $params = null, ?RequestOptions $options = null): RegenerateInvoiceLinkResult { $input = ['invoice_id' => $invoice_id]; $params = $params instanceof Model ? $params->toInputArray() : $params; $rest = $params ?? []; if ($rest && array_is_list($rest)) throw new SdkError('validation', 'Expected associative params', 'not_sent'); if (array_key_exists('Idempotency-Key', $rest)) { $input['Idempotency-Key'] = $rest['Idempotency-Key']; unset($rest['Idempotency-Key']); } if (array_key_exists('X-Request-Id', $rest)) { $input['X-Request-Id'] = $rest['X-Request-Id']; unset($rest['X-Request-Id']); } if (array_key_exists('Flint-Version', $rest)) { $input['Flint-Version'] = $rest['Flint-Version']; unset($rest['Flint-Version']); } if ($params !== null && (!$params || $rest)) $input['body'] = (object) $rest; return SdkResponse::payload($this->runtime->request('regenerateInvoicePublicLink', $input instanceof InvoicesRegeneratePublicLinkInput ? $input->toInputArray() : (new InvoicesRegeneratePublicLinkInput($input))->toInputArray(), $options), ['data']); }
    /** @return SdkResponse<InvoicesRegeneratePublicLinkResponse200> */
    public function regeneratePublicLinkWithResponse(string|Model $invoice_id, array|Model|null $params = null, ?RequestOptions $options = null): SdkResponse { $input = ['invoice_id' => $invoice_id]; $params = $params instanceof Model ? $params->toInputArray() : $params; $rest = $params ?? []; if ($rest && array_is_list($rest)) throw new SdkError('validation', 'Expected associative params', 'not_sent'); if (array_key_exists('Idempotency-Key', $rest)) { $input['Idempotency-Key'] = $rest['Idempotency-Key']; unset($rest['Idempotency-Key']); } if (array_key_exists('X-Request-Id', $rest)) { $input['X-Request-Id'] = $rest['X-Request-Id']; unset($rest['X-Request-Id']); } if (array_key_exists('Flint-Version', $rest)) { $input['Flint-Version'] = $rest['Flint-Version']; unset($rest['Flint-Version']); } if ($params !== null && (!$params || $rest)) $input['body'] = (object) $rest; $result = $this->runtime->request('regenerateInvoicePublicLink', $input instanceof InvoicesRegeneratePublicLinkInput ? $input->toInputArray() : (new InvoicesRegeneratePublicLinkInput($input))->toInputArray(), $options); return new SdkResponse($result->data, $result->meta, $result->raw); }
    /** Reverses previously applied manual/offline payment amount from an invoice. Safe to retry with the same Idempotency-Key.
     * @param array<array-key, mixed>|Model $params Flat body fields and query/header parameters; path arguments follow URL order.
     * @return Invoice
     */
    public function reverseManualPayment(string|Model $invoice_id, array|Model $params, ?RequestOptions $options = null): Invoice { $input = ['invoice_id' => $invoice_id]; $params = $params instanceof Model ? $params->toInputArray() : $params; $rest = $params ?? []; if ($rest && array_is_list($rest)) throw new SdkError('validation', 'Expected associative params', 'not_sent'); if (array_key_exists('Idempotency-Key', $rest)) { $input['Idempotency-Key'] = $rest['Idempotency-Key']; unset($rest['Idempotency-Key']); } if (array_key_exists('X-Request-Id', $rest)) { $input['X-Request-Id'] = $rest['X-Request-Id']; unset($rest['X-Request-Id']); } if (array_key_exists('Flint-Version', $rest)) { $input['Flint-Version'] = $rest['Flint-Version']; unset($rest['Flint-Version']); } if (true) $input['body'] = (object) $rest; return SdkResponse::payload($this->runtime->request('reverseManualInvoicePayment', $input instanceof InvoicesReverseManualPaymentInput ? $input->toInputArray() : (new InvoicesReverseManualPaymentInput($input))->toInputArray(), $options), ['data']); }
    /** @return SdkResponse<InvoicesReverseManualPaymentResponse200> */
    public function reverseManualPaymentWithResponse(string|Model $invoice_id, array|Model $params, ?RequestOptions $options = null): SdkResponse { $input = ['invoice_id' => $invoice_id]; $params = $params instanceof Model ? $params->toInputArray() : $params; $rest = $params ?? []; if ($rest && array_is_list($rest)) throw new SdkError('validation', 'Expected associative params', 'not_sent'); if (array_key_exists('Idempotency-Key', $rest)) { $input['Idempotency-Key'] = $rest['Idempotency-Key']; unset($rest['Idempotency-Key']); } if (array_key_exists('X-Request-Id', $rest)) { $input['X-Request-Id'] = $rest['X-Request-Id']; unset($rest['X-Request-Id']); } if (array_key_exists('Flint-Version', $rest)) { $input['Flint-Version'] = $rest['Flint-Version']; unset($rest['Flint-Version']); } if (true) $input['body'] = (object) $rest; $result = $this->runtime->request('reverseManualInvoicePayment', $input instanceof InvoicesReverseManualPaymentInput ? $input->toInputArray() : (new InvoicesReverseManualPaymentInput($input))->toInputArray(), $options); return new SdkResponse($result->data, $result->meta, $result->raw); }
    /** Attempts a reminder email for an already issued collectible invoice. Safe to retry with the same Idempotency-Key.
     * @param array<array-key, mixed>|Model|null $params Flat body fields and query/header parameters; path arguments follow URL order.
     * @return IssueInvoiceResult
     */
    public function sendReminder(string|Model $invoice_id, array|Model|null $params = null, ?RequestOptions $options = null): IssueInvoiceResult { $input = ['invoice_id' => $invoice_id]; $params = $params instanceof Model ? $params->toInputArray() : $params; $rest = $params ?? []; if ($rest && array_is_list($rest)) throw new SdkError('validation', 'Expected associative params', 'not_sent'); if (array_key_exists('Idempotency-Key', $rest)) { $input['Idempotency-Key'] = $rest['Idempotency-Key']; unset($rest['Idempotency-Key']); } if (array_key_exists('X-Request-Id', $rest)) { $input['X-Request-Id'] = $rest['X-Request-Id']; unset($rest['X-Request-Id']); } if (array_key_exists('Flint-Version', $rest)) { $input['Flint-Version'] = $rest['Flint-Version']; unset($rest['Flint-Version']); } foreach ($rest as $name => $value) { if (array_key_exists($name, $input)) throw new SdkError('validation', 'Path values belong in positional arguments', 'not_sent'); $input[$name] = $value; } return SdkResponse::payload($this->runtime->request('sendInvoiceReminder', $input instanceof InvoicesSendReminderInput ? $input->toInputArray() : (new InvoicesSendReminderInput($input))->toInputArray(), $options), ['data']); }
    /** @return SdkResponse<InvoicesSendReminderResponse200> */
    public function sendReminderWithResponse(string|Model $invoice_id, array|Model|null $params = null, ?RequestOptions $options = null): SdkResponse { $input = ['invoice_id' => $invoice_id]; $params = $params instanceof Model ? $params->toInputArray() : $params; $rest = $params ?? []; if ($rest && array_is_list($rest)) throw new SdkError('validation', 'Expected associative params', 'not_sent'); if (array_key_exists('Idempotency-Key', $rest)) { $input['Idempotency-Key'] = $rest['Idempotency-Key']; unset($rest['Idempotency-Key']); } if (array_key_exists('X-Request-Id', $rest)) { $input['X-Request-Id'] = $rest['X-Request-Id']; unset($rest['X-Request-Id']); } if (array_key_exists('Flint-Version', $rest)) { $input['Flint-Version'] = $rest['Flint-Version']; unset($rest['Flint-Version']); } foreach ($rest as $name => $value) { if (array_key_exists($name, $input)) throw new SdkError('validation', 'Path values belong in positional arguments', 'not_sent'); $input[$name] = $value; } $result = $this->runtime->request('sendInvoiceReminder', $input instanceof InvoicesSendReminderInput ? $input->toInputArray() : (new InvoicesSendReminderInput($input))->toInputArray(), $options); return new SdkResponse($result->data, $result->meta, $result->raw); }
    /** Updates mutable fields on a draft invoice. After issue, the only writable field is reminders_paused, which pauses or resumes automatic reminders on an open or partially paid invoice.
     * @param array<array-key, mixed>|Model $params Flat body fields and query/header parameters; path arguments follow URL order.
     * @return Invoice
     */
    public function update(string|Model $invoice_id, array|Model $params, ?RequestOptions $options = null): Invoice { $input = ['invoice_id' => $invoice_id]; $params = $params instanceof Model ? $params->toInputArray() : $params; $rest = $params ?? []; if ($rest && array_is_list($rest)) throw new SdkError('validation', 'Expected associative params', 'not_sent'); if (array_key_exists('Idempotency-Key', $rest)) { $input['Idempotency-Key'] = $rest['Idempotency-Key']; unset($rest['Idempotency-Key']); } if (array_key_exists('X-Request-Id', $rest)) { $input['X-Request-Id'] = $rest['X-Request-Id']; unset($rest['X-Request-Id']); } if (array_key_exists('Flint-Version', $rest)) { $input['Flint-Version'] = $rest['Flint-Version']; unset($rest['Flint-Version']); } if (true) $input['body'] = (object) $rest; return SdkResponse::payload($this->runtime->request('updateInvoice', $input instanceof InvoicesUpdateInput ? $input->toInputArray() : (new InvoicesUpdateInput($input))->toInputArray(), $options), ['data']); }
    /** @return SdkResponse<InvoicesUpdateResponse200> */
    public function updateWithResponse(string|Model $invoice_id, array|Model $params, ?RequestOptions $options = null): SdkResponse { $input = ['invoice_id' => $invoice_id]; $params = $params instanceof Model ? $params->toInputArray() : $params; $rest = $params ?? []; if ($rest && array_is_list($rest)) throw new SdkError('validation', 'Expected associative params', 'not_sent'); if (array_key_exists('Idempotency-Key', $rest)) { $input['Idempotency-Key'] = $rest['Idempotency-Key']; unset($rest['Idempotency-Key']); } if (array_key_exists('X-Request-Id', $rest)) { $input['X-Request-Id'] = $rest['X-Request-Id']; unset($rest['X-Request-Id']); } if (array_key_exists('Flint-Version', $rest)) { $input['Flint-Version'] = $rest['Flint-Version']; unset($rest['Flint-Version']); } if (true) $input['body'] = (object) $rest; $result = $this->runtime->request('updateInvoice', $input instanceof InvoicesUpdateInput ? $input->toInputArray() : (new InvoicesUpdateInput($input))->toInputArray(), $options); return new SdkResponse($result->data, $result->meta, $result->raw); }
    /** Voids an unpaid invoice so the associated order can be edited or collected again. An invoice with an issued credit note against it cannot be voided until that credit note is voided.
     * @param array<array-key, mixed>|Model|null $params Flat body fields and query/header parameters; path arguments follow URL order.
     * @return Invoice
     */
    public function voidResource(string|Model $invoice_id, array|Model|null $params = null, ?RequestOptions $options = null): Invoice { $input = ['invoice_id' => $invoice_id]; $params = $params instanceof Model ? $params->toInputArray() : $params; $rest = $params ?? []; if ($rest && array_is_list($rest)) throw new SdkError('validation', 'Expected associative params', 'not_sent'); if (array_key_exists('Idempotency-Key', $rest)) { $input['Idempotency-Key'] = $rest['Idempotency-Key']; unset($rest['Idempotency-Key']); } if (array_key_exists('X-Request-Id', $rest)) { $input['X-Request-Id'] = $rest['X-Request-Id']; unset($rest['X-Request-Id']); } if (array_key_exists('Flint-Version', $rest)) { $input['Flint-Version'] = $rest['Flint-Version']; unset($rest['Flint-Version']); } if ($params !== null && (!$params || $rest)) $input['body'] = (object) $rest; return SdkResponse::payload($this->runtime->request('voidInvoice', $input instanceof InvoicesVoidResourceInput ? $input->toInputArray() : (new InvoicesVoidResourceInput($input))->toInputArray(), $options), ['data']); }
    /** @return SdkResponse<InvoicesVoidResourceResponse200> */
    public function voidResourceWithResponse(string|Model $invoice_id, array|Model|null $params = null, ?RequestOptions $options = null): SdkResponse { $input = ['invoice_id' => $invoice_id]; $params = $params instanceof Model ? $params->toInputArray() : $params; $rest = $params ?? []; if ($rest && array_is_list($rest)) throw new SdkError('validation', 'Expected associative params', 'not_sent'); if (array_key_exists('Idempotency-Key', $rest)) { $input['Idempotency-Key'] = $rest['Idempotency-Key']; unset($rest['Idempotency-Key']); } if (array_key_exists('X-Request-Id', $rest)) { $input['X-Request-Id'] = $rest['X-Request-Id']; unset($rest['X-Request-Id']); } if (array_key_exists('Flint-Version', $rest)) { $input['Flint-Version'] = $rest['Flint-Version']; unset($rest['Flint-Version']); } if ($params !== null && (!$params || $rest)) $input['body'] = (object) $rest; $result = $this->runtime->request('voidInvoice', $input instanceof InvoicesVoidResourceInput ? $input->toInputArray() : (new InvoicesVoidResourceInput($input))->toInputArray(), $options); return new SdkResponse($result->data, $result->meta, $result->raw); }
    /** Waives the unpaid remainder of an assessed late fee. Collected money is not refunded. The reason is visible only to the merchant.
     * @param array<array-key, mixed>|Model $params Flat body fields and query/header parameters; path arguments follow URL order.
     * @return Invoice
     */
    public function waiveLateFee(string|Model $invoice_id, string|Model $invoice_late_fee_id, array|Model $params, ?RequestOptions $options = null): Invoice { $input = ['invoice_id' => $invoice_id, 'invoice_late_fee_id' => $invoice_late_fee_id]; $params = $params instanceof Model ? $params->toInputArray() : $params; $rest = $params ?? []; if ($rest && array_is_list($rest)) throw new SdkError('validation', 'Expected associative params', 'not_sent'); if (array_key_exists('Idempotency-Key', $rest)) { $input['Idempotency-Key'] = $rest['Idempotency-Key']; unset($rest['Idempotency-Key']); } if (array_key_exists('Flint-Version', $rest)) { $input['Flint-Version'] = $rest['Flint-Version']; unset($rest['Flint-Version']); } if (true) $input['body'] = (object) $rest; return SdkResponse::payload($this->runtime->request('waiveInvoiceLateFee', $input instanceof InvoicesWaiveLateFeeInput ? $input->toInputArray() : (new InvoicesWaiveLateFeeInput($input))->toInputArray(), $options), ['data']); }
    /** @return SdkResponse<InvoicesWaiveLateFeeResponse200> */
    public function waiveLateFeeWithResponse(string|Model $invoice_id, string|Model $invoice_late_fee_id, array|Model $params, ?RequestOptions $options = null): SdkResponse { $input = ['invoice_id' => $invoice_id, 'invoice_late_fee_id' => $invoice_late_fee_id]; $params = $params instanceof Model ? $params->toInputArray() : $params; $rest = $params ?? []; if ($rest && array_is_list($rest)) throw new SdkError('validation', 'Expected associative params', 'not_sent'); if (array_key_exists('Idempotency-Key', $rest)) { $input['Idempotency-Key'] = $rest['Idempotency-Key']; unset($rest['Idempotency-Key']); } if (array_key_exists('Flint-Version', $rest)) { $input['Flint-Version'] = $rest['Flint-Version']; unset($rest['Flint-Version']); } if (true) $input['body'] = (object) $rest; $result = $this->runtime->request('waiveInvoiceLateFee', $input instanceof InvoicesWaiveLateFeeInput ? $input->toInputArray() : (new InvoicesWaiveLateFeeInput($input))->toInputArray(), $options); return new SdkResponse($result->data, $result->meta, $result->raw); }
}
