<?php
declare(strict_types=1);
namespace Flint;
final class MerchantsResource {
    public function __construct(private readonly Runtime $runtime) {}
    /** Returns the authenticated merchant.
     * @param array<array-key, mixed>|Model|null $params Flat body fields and query/header parameters; path arguments follow URL order.
     * @return Merchant
     */
    public function get(array|Model|null $params = null, ?RequestOptions $options = null): Merchant { $input = []; $params = $params instanceof Model ? $params->toInputArray() : $params; $rest = $params ?? []; if ($rest && array_is_list($rest)) throw new SdkError('validation', 'Expected associative params', 'not_sent'); if (array_key_exists('expand', $rest)) { $input['expand'] = $rest['expand']; unset($rest['expand']); } if (array_key_exists('Flint-Version', $rest)) { $input['Flint-Version'] = $rest['Flint-Version']; unset($rest['Flint-Version']); } foreach ($rest as $name => $value) { if (array_key_exists($name, $input)) throw new SdkError('validation', 'Path values belong in positional arguments', 'not_sent'); $input[$name] = $value; } return SdkResponse::payload($this->runtime->request('getMerchant', $input instanceof MerchantsGetInput ? $input->toInputArray() : (new MerchantsGetInput($input))->toInputArray(), $options), ['data']); }
    /** @return SdkResponse<MerchantsGetResponse200> */
    public function getWithResponse(array|Model|null $params = null, ?RequestOptions $options = null): SdkResponse { $input = []; $params = $params instanceof Model ? $params->toInputArray() : $params; $rest = $params ?? []; if ($rest && array_is_list($rest)) throw new SdkError('validation', 'Expected associative params', 'not_sent'); if (array_key_exists('expand', $rest)) { $input['expand'] = $rest['expand']; unset($rest['expand']); } if (array_key_exists('Flint-Version', $rest)) { $input['Flint-Version'] = $rest['Flint-Version']; unset($rest['Flint-Version']); } foreach ($rest as $name => $value) { if (array_key_exists($name, $input)) throw new SdkError('validation', 'Path values belong in positional arguments', 'not_sent'); $input[$name] = $value; } $result = $this->runtime->request('getMerchant', $input instanceof MerchantsGetInput ? $input->toInputArray() : (new MerchantsGetInput($input))->toInputArray(), $options); return new SdkResponse($result->data, $result->meta, $result->raw); }
    /** Applies a sparse update to the authenticated merchant's public business profile fields.
     * @param array<array-key, mixed>|Model $params Flat body fields and query/header parameters; path arguments follow URL order.
     * @return Merchant
     */
    public function update(array|Model $params, ?RequestOptions $options = null): Merchant { $input = []; $params = $params instanceof Model ? $params->toInputArray() : $params; $rest = $params ?? []; if ($rest && array_is_list($rest)) throw new SdkError('validation', 'Expected associative params', 'not_sent'); if (array_key_exists('Idempotency-Key', $rest)) { $input['Idempotency-Key'] = $rest['Idempotency-Key']; unset($rest['Idempotency-Key']); } if (array_key_exists('X-Request-Id', $rest)) { $input['X-Request-Id'] = $rest['X-Request-Id']; unset($rest['X-Request-Id']); } if (array_key_exists('Flint-Version', $rest)) { $input['Flint-Version'] = $rest['Flint-Version']; unset($rest['Flint-Version']); } if (true) $input['body'] = (object) $rest; return SdkResponse::payload($this->runtime->request('updateMerchant', $input instanceof MerchantsUpdateInput ? $input->toInputArray() : (new MerchantsUpdateInput($input))->toInputArray(), $options), ['data']); }
    /** @return SdkResponse<MerchantsUpdateResponse200> */
    public function updateWithResponse(array|Model $params, ?RequestOptions $options = null): SdkResponse { $input = []; $params = $params instanceof Model ? $params->toInputArray() : $params; $rest = $params ?? []; if ($rest && array_is_list($rest)) throw new SdkError('validation', 'Expected associative params', 'not_sent'); if (array_key_exists('Idempotency-Key', $rest)) { $input['Idempotency-Key'] = $rest['Idempotency-Key']; unset($rest['Idempotency-Key']); } if (array_key_exists('X-Request-Id', $rest)) { $input['X-Request-Id'] = $rest['X-Request-Id']; unset($rest['X-Request-Id']); } if (array_key_exists('Flint-Version', $rest)) { $input['Flint-Version'] = $rest['Flint-Version']; unset($rest['Flint-Version']); } if (true) $input['body'] = (object) $rest; $result = $this->runtime->request('updateMerchant', $input instanceof MerchantsUpdateInput ? $input->toInputArray() : (new MerchantsUpdateInput($input))->toInputArray(), $options); return new SdkResponse($result->data, $result->meta, $result->raw); }
}
