<?php
declare(strict_types=1);
namespace Flint;
final class OrganizationsResource {
    public function __construct(private readonly Runtime $runtime) {}
    /** Creates a child organization within the caller's accessible organization hierarchy.
     * @param array<array-key, mixed>|Model $params Flat body fields and query/header parameters; path arguments follow URL order.
     * @return Organization
     */
    public function create(array|Model $params, ?RequestOptions $options = null): Organization { $input = []; $params = $params instanceof Model ? $params->toInputArray() : $params; $rest = $params ?? []; if ($rest && array_is_list($rest)) throw new SdkError('validation', 'Expected associative params', 'not_sent'); if (array_key_exists('Idempotency-Key', $rest)) { $input['Idempotency-Key'] = $rest['Idempotency-Key']; unset($rest['Idempotency-Key']); } if (array_key_exists('X-Request-Id', $rest)) { $input['X-Request-Id'] = $rest['X-Request-Id']; unset($rest['X-Request-Id']); } if (array_key_exists('Flint-Version', $rest)) { $input['Flint-Version'] = $rest['Flint-Version']; unset($rest['Flint-Version']); } if (true) $input['body'] = (object) $rest; return SdkResponse::payload($this->runtime->request('createOrganization', $input instanceof OrganizationsCreateInput ? $input->toInputArray() : (new OrganizationsCreateInput($input))->toInputArray(), $options), ['data']); }
    /** @return SdkResponse<OrganizationsCreateResponse201> */
    public function createWithResponse(array|Model $params, ?RequestOptions $options = null): SdkResponse { $input = []; $params = $params instanceof Model ? $params->toInputArray() : $params; $rest = $params ?? []; if ($rest && array_is_list($rest)) throw new SdkError('validation', 'Expected associative params', 'not_sent'); if (array_key_exists('Idempotency-Key', $rest)) { $input['Idempotency-Key'] = $rest['Idempotency-Key']; unset($rest['Idempotency-Key']); } if (array_key_exists('X-Request-Id', $rest)) { $input['X-Request-Id'] = $rest['X-Request-Id']; unset($rest['X-Request-Id']); } if (array_key_exists('Flint-Version', $rest)) { $input['Flint-Version'] = $rest['Flint-Version']; unset($rest['Flint-Version']); } if (true) $input['body'] = (object) $rest; $result = $this->runtime->request('createOrganization', $input instanceof OrganizationsCreateInput ? $input->toInputArray() : (new OrganizationsCreateInput($input))->toInputArray(), $options); return new SdkResponse($result->data, $result->meta, $result->raw); }
    /** Soft-deletes an organization when it has no active descendants or merchant links.
     * @param array<array-key, mixed>|Model|null $params Flat body fields and query/header parameters; path arguments follow URL order.
     * @return Organization
     */
    public function remove(string|Model $organization_id, array|Model|null $params = null, ?RequestOptions $options = null): Organization { $input = ['organization_id' => $organization_id]; $params = $params instanceof Model ? $params->toInputArray() : $params; $rest = $params ?? []; if ($rest && array_is_list($rest)) throw new SdkError('validation', 'Expected associative params', 'not_sent'); if (array_key_exists('Idempotency-Key', $rest)) { $input['Idempotency-Key'] = $rest['Idempotency-Key']; unset($rest['Idempotency-Key']); } if (array_key_exists('X-Request-Id', $rest)) { $input['X-Request-Id'] = $rest['X-Request-Id']; unset($rest['X-Request-Id']); } if (array_key_exists('Flint-Version', $rest)) { $input['Flint-Version'] = $rest['Flint-Version']; unset($rest['Flint-Version']); } foreach ($rest as $name => $value) { if (array_key_exists($name, $input)) throw new SdkError('validation', 'Path values belong in positional arguments', 'not_sent'); $input[$name] = $value; } return SdkResponse::payload($this->runtime->request('deleteOrganization', $input instanceof OrganizationsRemoveInput ? $input->toInputArray() : (new OrganizationsRemoveInput($input))->toInputArray(), $options), ['data']); }
    /** @return SdkResponse<OrganizationsRemoveResponse200> */
    public function removeWithResponse(string|Model $organization_id, array|Model|null $params = null, ?RequestOptions $options = null): SdkResponse { $input = ['organization_id' => $organization_id]; $params = $params instanceof Model ? $params->toInputArray() : $params; $rest = $params ?? []; if ($rest && array_is_list($rest)) throw new SdkError('validation', 'Expected associative params', 'not_sent'); if (array_key_exists('Idempotency-Key', $rest)) { $input['Idempotency-Key'] = $rest['Idempotency-Key']; unset($rest['Idempotency-Key']); } if (array_key_exists('X-Request-Id', $rest)) { $input['X-Request-Id'] = $rest['X-Request-Id']; unset($rest['X-Request-Id']); } if (array_key_exists('Flint-Version', $rest)) { $input['Flint-Version'] = $rest['Flint-Version']; unset($rest['Flint-Version']); } foreach ($rest as $name => $value) { if (array_key_exists($name, $input)) throw new SdkError('validation', 'Path values belong in positional arguments', 'not_sent'); $input[$name] = $value; } $result = $this->runtime->request('deleteOrganization', $input instanceof OrganizationsRemoveInput ? $input->toInputArray() : (new OrganizationsRemoveInput($input))->toInputArray(), $options); return new SdkResponse($result->data, $result->meta, $result->raw); }
    /** Returns an accessible organization by ID.
     * @param array<array-key, mixed>|Model|null $params Flat body fields and query/header parameters; path arguments follow URL order.
     * @return Organization
     */
    public function get(string|Model $organization_id, array|Model|null $params = null, ?RequestOptions $options = null): Organization { $input = ['organization_id' => $organization_id]; $params = $params instanceof Model ? $params->toInputArray() : $params; $rest = $params ?? []; if ($rest && array_is_list($rest)) throw new SdkError('validation', 'Expected associative params', 'not_sent'); if (array_key_exists('expand', $rest)) { $input['expand'] = $rest['expand']; unset($rest['expand']); } if (array_key_exists('Flint-Version', $rest)) { $input['Flint-Version'] = $rest['Flint-Version']; unset($rest['Flint-Version']); } foreach ($rest as $name => $value) { if (array_key_exists($name, $input)) throw new SdkError('validation', 'Path values belong in positional arguments', 'not_sent'); $input[$name] = $value; } return SdkResponse::payload($this->runtime->request('getOrganization', $input instanceof OrganizationsGetInput ? $input->toInputArray() : (new OrganizationsGetInput($input))->toInputArray(), $options), ['data']); }
    /** @return SdkResponse<OrganizationsGetResponse200> */
    public function getWithResponse(string|Model $organization_id, array|Model|null $params = null, ?RequestOptions $options = null): SdkResponse { $input = ['organization_id' => $organization_id]; $params = $params instanceof Model ? $params->toInputArray() : $params; $rest = $params ?? []; if ($rest && array_is_list($rest)) throw new SdkError('validation', 'Expected associative params', 'not_sent'); if (array_key_exists('expand', $rest)) { $input['expand'] = $rest['expand']; unset($rest['expand']); } if (array_key_exists('Flint-Version', $rest)) { $input['Flint-Version'] = $rest['Flint-Version']; unset($rest['Flint-Version']); } foreach ($rest as $name => $value) { if (array_key_exists($name, $input)) throw new SdkError('validation', 'Path values belong in positional arguments', 'not_sent'); $input[$name] = $value; } $result = $this->runtime->request('getOrganization', $input instanceof OrganizationsGetInput ? $input->toInputArray() : (new OrganizationsGetInput($input))->toInputArray(), $options); return new SdkResponse($result->data, $result->meta, $result->raw); }
    /** Adds or updates a direct organization membership for a user.
     * @param array<array-key, mixed>|Model $params Flat body fields and query/header parameters; path arguments follow URL order.
     * @return OrganizationMembership
     */
    public function grantMembership(string|Model $organization_id, array|Model $params, ?RequestOptions $options = null): OrganizationMembership { $input = ['organization_id' => $organization_id]; $params = $params instanceof Model ? $params->toInputArray() : $params; $rest = $params ?? []; if ($rest && array_is_list($rest)) throw new SdkError('validation', 'Expected associative params', 'not_sent'); if (array_key_exists('Idempotency-Key', $rest)) { $input['Idempotency-Key'] = $rest['Idempotency-Key']; unset($rest['Idempotency-Key']); } if (array_key_exists('X-Request-Id', $rest)) { $input['X-Request-Id'] = $rest['X-Request-Id']; unset($rest['X-Request-Id']); } if (array_key_exists('Flint-Version', $rest)) { $input['Flint-Version'] = $rest['Flint-Version']; unset($rest['Flint-Version']); } if (true) $input['body'] = (object) $rest; return SdkResponse::payload($this->runtime->request('grantOrganizationMembership', $input instanceof OrganizationsGrantMembershipInput ? $input->toInputArray() : (new OrganizationsGrantMembershipInput($input))->toInputArray(), $options), ['data']); }
    /** @return SdkResponse<OrganizationsGrantMembershipResponse200|OrganizationsGrantMembershipResponse201> */
    public function grantMembershipWithResponse(string|Model $organization_id, array|Model $params, ?RequestOptions $options = null): SdkResponse { $input = ['organization_id' => $organization_id]; $params = $params instanceof Model ? $params->toInputArray() : $params; $rest = $params ?? []; if ($rest && array_is_list($rest)) throw new SdkError('validation', 'Expected associative params', 'not_sent'); if (array_key_exists('Idempotency-Key', $rest)) { $input['Idempotency-Key'] = $rest['Idempotency-Key']; unset($rest['Idempotency-Key']); } if (array_key_exists('X-Request-Id', $rest)) { $input['X-Request-Id'] = $rest['X-Request-Id']; unset($rest['X-Request-Id']); } if (array_key_exists('Flint-Version', $rest)) { $input['Flint-Version'] = $rest['Flint-Version']; unset($rest['Flint-Version']); } if (true) $input['body'] = (object) $rest; $result = $this->runtime->request('grantOrganizationMembership', $input instanceof OrganizationsGrantMembershipInput ? $input->toInputArray() : (new OrganizationsGrantMembershipInput($input))->toInputArray(), $options); return new SdkResponse($result->data, $result->meta, $result->raw); }
    /** Returns the direct memberships for an organization.
     * @param array<array-key, mixed>|Model|null $params Flat body fields and query/header parameters; path arguments follow URL order.
     * @return OrganizationsListMembershipsResponse200
     */
    public function listMemberships(string|Model $organization_id, array|Model|null $params = null, ?RequestOptions $options = null): OrganizationsListMembershipsResponse200 { $input = ['organization_id' => $organization_id]; $params = $params instanceof Model ? $params->toInputArray() : $params; $rest = $params ?? []; if ($rest && array_is_list($rest)) throw new SdkError('validation', 'Expected associative params', 'not_sent'); if (array_key_exists('page_size', $rest)) { $input['page_size'] = $rest['page_size']; unset($rest['page_size']); } if (array_key_exists('page_token', $rest)) { $input['page_token'] = $rest['page_token']; unset($rest['page_token']); } if (array_key_exists('Flint-Version', $rest)) { $input['Flint-Version'] = $rest['Flint-Version']; unset($rest['Flint-Version']); } foreach ($rest as $name => $value) { if (array_key_exists($name, $input)) throw new SdkError('validation', 'Path values belong in positional arguments', 'not_sent'); $input[$name] = $value; } return SdkResponse::payload($this->runtime->request('listOrganizationMemberships', $input instanceof OrganizationsListMembershipsInput ? $input->toInputArray() : (new OrganizationsListMembershipsInput($input))->toInputArray(), $options), []); }
    /** @return SdkResponse<OrganizationsListMembershipsResponse200> */
    public function listMembershipsWithResponse(string|Model $organization_id, array|Model|null $params = null, ?RequestOptions $options = null): SdkResponse { $input = ['organization_id' => $organization_id]; $params = $params instanceof Model ? $params->toInputArray() : $params; $rest = $params ?? []; if ($rest && array_is_list($rest)) throw new SdkError('validation', 'Expected associative params', 'not_sent'); if (array_key_exists('page_size', $rest)) { $input['page_size'] = $rest['page_size']; unset($rest['page_size']); } if (array_key_exists('page_token', $rest)) { $input['page_token'] = $rest['page_token']; unset($rest['page_token']); } if (array_key_exists('Flint-Version', $rest)) { $input['Flint-Version'] = $rest['Flint-Version']; unset($rest['Flint-Version']); } foreach ($rest as $name => $value) { if (array_key_exists($name, $input)) throw new SdkError('validation', 'Path values belong in positional arguments', 'not_sent'); $input[$name] = $value; } $result = $this->runtime->request('listOrganizationMemberships', $input instanceof OrganizationsListMembershipsInput ? $input->toInputArray() : (new OrganizationsListMembershipsInput($input))->toInputArray(), $options); return new SdkResponse($result->data, $result->meta, $result->raw); }
    /** @return \Generator<int, OrganizationsListMembershipsResponse200> */
    public function listMembershipsPages(string|Model $organization_id, array|Model|null $params = null, ?RequestOptions $options = null): \Generator { $input = ['organization_id' => $organization_id]; $params = $params instanceof Model ? $params->toInputArray() : $params; $rest = $params ?? []; if ($rest && array_is_list($rest)) throw new SdkError('validation', 'Expected associative params', 'not_sent'); if (array_key_exists('page_size', $rest)) { $input['page_size'] = $rest['page_size']; unset($rest['page_size']); } if (array_key_exists('page_token', $rest)) { $input['page_token'] = $rest['page_token']; unset($rest['page_token']); } if (array_key_exists('Flint-Version', $rest)) { $input['Flint-Version'] = $rest['Flint-Version']; unset($rest['Flint-Version']); } foreach ($rest as $name => $value) { if (array_key_exists($name, $input)) throw new SdkError('validation', 'Path values belong in positional arguments', 'not_sent'); $input[$name] = $value; } return SdkResponse::payloadPages($this->runtime->pages('listOrganizationMemberships', $input instanceof OrganizationsListMembershipsInput ? $input->toInputArray() : (new OrganizationsListMembershipsInput($input))->toInputArray(), $options), []); }
    /** @return \Generator<int, SdkResponse<OrganizationsListMembershipsResponse200>> */
    public function listMembershipsPagesWithResponse(string|Model $organization_id, array|Model|null $params = null, ?RequestOptions $options = null): \Generator { $input = ['organization_id' => $organization_id]; $params = $params instanceof Model ? $params->toInputArray() : $params; $rest = $params ?? []; if ($rest && array_is_list($rest)) throw new SdkError('validation', 'Expected associative params', 'not_sent'); if (array_key_exists('page_size', $rest)) { $input['page_size'] = $rest['page_size']; unset($rest['page_size']); } if (array_key_exists('page_token', $rest)) { $input['page_token'] = $rest['page_token']; unset($rest['page_token']); } if (array_key_exists('Flint-Version', $rest)) { $input['Flint-Version'] = $rest['Flint-Version']; unset($rest['Flint-Version']); } foreach ($rest as $name => $value) { if (array_key_exists($name, $input)) throw new SdkError('validation', 'Path values belong in positional arguments', 'not_sent'); $input[$name] = $value; } return SdkResponse::responsePages($this->runtime->pages('listOrganizationMemberships', $input instanceof OrganizationsListMembershipsInput ? $input->toInputArray() : (new OrganizationsListMembershipsInput($input))->toInputArray(), $options)); }
    /** @return \Generator<int, OrganizationMembership> */
    public function listMembershipsItems(string|Model $organization_id, array|Model|null $params = null, ?RequestOptions $options = null): \Generator { $input = ['organization_id' => $organization_id]; $params = $params instanceof Model ? $params->toInputArray() : $params; $rest = $params ?? []; if ($rest && array_is_list($rest)) throw new SdkError('validation', 'Expected associative params', 'not_sent'); if (array_key_exists('page_size', $rest)) { $input['page_size'] = $rest['page_size']; unset($rest['page_size']); } if (array_key_exists('page_token', $rest)) { $input['page_token'] = $rest['page_token']; unset($rest['page_token']); } if (array_key_exists('Flint-Version', $rest)) { $input['Flint-Version'] = $rest['Flint-Version']; unset($rest['Flint-Version']); } foreach ($rest as $name => $value) { if (array_key_exists($name, $input)) throw new SdkError('validation', 'Path values belong in positional arguments', 'not_sent'); $input[$name] = $value; } return $this->runtime->items('listOrganizationMemberships', $input instanceof OrganizationsListMembershipsInput ? $input->toInputArray() : (new OrganizationsListMembershipsInput($input))->toInputArray(), $options); }
    /** Returns the organizations accessible to the caller, filtered to the authenticated merchant's organization subtree for external API keys.
     * @param array<array-key, mixed>|Model|null $params Flat body fields and query/header parameters; path arguments follow URL order.
     * @return OrganizationsListResponse200
     */
    public function list(array|Model|null $params = null, ?RequestOptions $options = null): OrganizationsListResponse200 { $input = []; $params = $params instanceof Model ? $params->toInputArray() : $params; $rest = $params ?? []; if ($rest && array_is_list($rest)) throw new SdkError('validation', 'Expected associative params', 'not_sent'); if (array_key_exists('parent_organization_id', $rest)) { $input['parent_organization_id'] = $rest['parent_organization_id']; unset($rest['parent_organization_id']); } if (array_key_exists('status', $rest)) { $input['status'] = $rest['status']; unset($rest['status']); } if (array_key_exists('page_size', $rest)) { $input['page_size'] = $rest['page_size']; unset($rest['page_size']); } if (array_key_exists('page_token', $rest)) { $input['page_token'] = $rest['page_token']; unset($rest['page_token']); } if (array_key_exists('sort_by', $rest)) { $input['sort_by'] = $rest['sort_by']; unset($rest['sort_by']); } if (array_key_exists('sort_direction', $rest)) { $input['sort_direction'] = $rest['sort_direction']; unset($rest['sort_direction']); } if (array_key_exists('created_after', $rest)) { $input['created_after'] = $rest['created_after']; unset($rest['created_after']); } if (array_key_exists('created_before', $rest)) { $input['created_before'] = $rest['created_before']; unset($rest['created_before']); } if (array_key_exists('updated_after', $rest)) { $input['updated_after'] = $rest['updated_after']; unset($rest['updated_after']); } if (array_key_exists('updated_before', $rest)) { $input['updated_before'] = $rest['updated_before']; unset($rest['updated_before']); } if (array_key_exists('Flint-Version', $rest)) { $input['Flint-Version'] = $rest['Flint-Version']; unset($rest['Flint-Version']); } foreach ($rest as $name => $value) { if (array_key_exists($name, $input)) throw new SdkError('validation', 'Path values belong in positional arguments', 'not_sent'); $input[$name] = $value; } return SdkResponse::payload($this->runtime->request('listOrganizations', $input instanceof OrganizationsListInput ? $input->toInputArray() : (new OrganizationsListInput($input))->toInputArray(), $options), []); }
    /** @return SdkResponse<OrganizationsListResponse200> */
    public function listWithResponse(array|Model|null $params = null, ?RequestOptions $options = null): SdkResponse { $input = []; $params = $params instanceof Model ? $params->toInputArray() : $params; $rest = $params ?? []; if ($rest && array_is_list($rest)) throw new SdkError('validation', 'Expected associative params', 'not_sent'); if (array_key_exists('parent_organization_id', $rest)) { $input['parent_organization_id'] = $rest['parent_organization_id']; unset($rest['parent_organization_id']); } if (array_key_exists('status', $rest)) { $input['status'] = $rest['status']; unset($rest['status']); } if (array_key_exists('page_size', $rest)) { $input['page_size'] = $rest['page_size']; unset($rest['page_size']); } if (array_key_exists('page_token', $rest)) { $input['page_token'] = $rest['page_token']; unset($rest['page_token']); } if (array_key_exists('sort_by', $rest)) { $input['sort_by'] = $rest['sort_by']; unset($rest['sort_by']); } if (array_key_exists('sort_direction', $rest)) { $input['sort_direction'] = $rest['sort_direction']; unset($rest['sort_direction']); } if (array_key_exists('created_after', $rest)) { $input['created_after'] = $rest['created_after']; unset($rest['created_after']); } if (array_key_exists('created_before', $rest)) { $input['created_before'] = $rest['created_before']; unset($rest['created_before']); } if (array_key_exists('updated_after', $rest)) { $input['updated_after'] = $rest['updated_after']; unset($rest['updated_after']); } if (array_key_exists('updated_before', $rest)) { $input['updated_before'] = $rest['updated_before']; unset($rest['updated_before']); } if (array_key_exists('Flint-Version', $rest)) { $input['Flint-Version'] = $rest['Flint-Version']; unset($rest['Flint-Version']); } foreach ($rest as $name => $value) { if (array_key_exists($name, $input)) throw new SdkError('validation', 'Path values belong in positional arguments', 'not_sent'); $input[$name] = $value; } $result = $this->runtime->request('listOrganizations', $input instanceof OrganizationsListInput ? $input->toInputArray() : (new OrganizationsListInput($input))->toInputArray(), $options); return new SdkResponse($result->data, $result->meta, $result->raw); }
    /** @return \Generator<int, OrganizationsListResponse200> */
    public function listPages(array|Model|null $params = null, ?RequestOptions $options = null): \Generator { $input = []; $params = $params instanceof Model ? $params->toInputArray() : $params; $rest = $params ?? []; if ($rest && array_is_list($rest)) throw new SdkError('validation', 'Expected associative params', 'not_sent'); if (array_key_exists('parent_organization_id', $rest)) { $input['parent_organization_id'] = $rest['parent_organization_id']; unset($rest['parent_organization_id']); } if (array_key_exists('status', $rest)) { $input['status'] = $rest['status']; unset($rest['status']); } if (array_key_exists('page_size', $rest)) { $input['page_size'] = $rest['page_size']; unset($rest['page_size']); } if (array_key_exists('page_token', $rest)) { $input['page_token'] = $rest['page_token']; unset($rest['page_token']); } if (array_key_exists('sort_by', $rest)) { $input['sort_by'] = $rest['sort_by']; unset($rest['sort_by']); } if (array_key_exists('sort_direction', $rest)) { $input['sort_direction'] = $rest['sort_direction']; unset($rest['sort_direction']); } if (array_key_exists('created_after', $rest)) { $input['created_after'] = $rest['created_after']; unset($rest['created_after']); } if (array_key_exists('created_before', $rest)) { $input['created_before'] = $rest['created_before']; unset($rest['created_before']); } if (array_key_exists('updated_after', $rest)) { $input['updated_after'] = $rest['updated_after']; unset($rest['updated_after']); } if (array_key_exists('updated_before', $rest)) { $input['updated_before'] = $rest['updated_before']; unset($rest['updated_before']); } if (array_key_exists('Flint-Version', $rest)) { $input['Flint-Version'] = $rest['Flint-Version']; unset($rest['Flint-Version']); } foreach ($rest as $name => $value) { if (array_key_exists($name, $input)) throw new SdkError('validation', 'Path values belong in positional arguments', 'not_sent'); $input[$name] = $value; } return SdkResponse::payloadPages($this->runtime->pages('listOrganizations', $input instanceof OrganizationsListInput ? $input->toInputArray() : (new OrganizationsListInput($input))->toInputArray(), $options), []); }
    /** @return \Generator<int, SdkResponse<OrganizationsListResponse200>> */
    public function listPagesWithResponse(array|Model|null $params = null, ?RequestOptions $options = null): \Generator { $input = []; $params = $params instanceof Model ? $params->toInputArray() : $params; $rest = $params ?? []; if ($rest && array_is_list($rest)) throw new SdkError('validation', 'Expected associative params', 'not_sent'); if (array_key_exists('parent_organization_id', $rest)) { $input['parent_organization_id'] = $rest['parent_organization_id']; unset($rest['parent_organization_id']); } if (array_key_exists('status', $rest)) { $input['status'] = $rest['status']; unset($rest['status']); } if (array_key_exists('page_size', $rest)) { $input['page_size'] = $rest['page_size']; unset($rest['page_size']); } if (array_key_exists('page_token', $rest)) { $input['page_token'] = $rest['page_token']; unset($rest['page_token']); } if (array_key_exists('sort_by', $rest)) { $input['sort_by'] = $rest['sort_by']; unset($rest['sort_by']); } if (array_key_exists('sort_direction', $rest)) { $input['sort_direction'] = $rest['sort_direction']; unset($rest['sort_direction']); } if (array_key_exists('created_after', $rest)) { $input['created_after'] = $rest['created_after']; unset($rest['created_after']); } if (array_key_exists('created_before', $rest)) { $input['created_before'] = $rest['created_before']; unset($rest['created_before']); } if (array_key_exists('updated_after', $rest)) { $input['updated_after'] = $rest['updated_after']; unset($rest['updated_after']); } if (array_key_exists('updated_before', $rest)) { $input['updated_before'] = $rest['updated_before']; unset($rest['updated_before']); } if (array_key_exists('Flint-Version', $rest)) { $input['Flint-Version'] = $rest['Flint-Version']; unset($rest['Flint-Version']); } foreach ($rest as $name => $value) { if (array_key_exists($name, $input)) throw new SdkError('validation', 'Path values belong in positional arguments', 'not_sent'); $input[$name] = $value; } return SdkResponse::responsePages($this->runtime->pages('listOrganizations', $input instanceof OrganizationsListInput ? $input->toInputArray() : (new OrganizationsListInput($input))->toInputArray(), $options)); }
    /** @return \Generator<int, Organization> */
    public function listItems(array|Model|null $params = null, ?RequestOptions $options = null): \Generator { $input = []; $params = $params instanceof Model ? $params->toInputArray() : $params; $rest = $params ?? []; if ($rest && array_is_list($rest)) throw new SdkError('validation', 'Expected associative params', 'not_sent'); if (array_key_exists('parent_organization_id', $rest)) { $input['parent_organization_id'] = $rest['parent_organization_id']; unset($rest['parent_organization_id']); } if (array_key_exists('status', $rest)) { $input['status'] = $rest['status']; unset($rest['status']); } if (array_key_exists('page_size', $rest)) { $input['page_size'] = $rest['page_size']; unset($rest['page_size']); } if (array_key_exists('page_token', $rest)) { $input['page_token'] = $rest['page_token']; unset($rest['page_token']); } if (array_key_exists('sort_by', $rest)) { $input['sort_by'] = $rest['sort_by']; unset($rest['sort_by']); } if (array_key_exists('sort_direction', $rest)) { $input['sort_direction'] = $rest['sort_direction']; unset($rest['sort_direction']); } if (array_key_exists('created_after', $rest)) { $input['created_after'] = $rest['created_after']; unset($rest['created_after']); } if (array_key_exists('created_before', $rest)) { $input['created_before'] = $rest['created_before']; unset($rest['created_before']); } if (array_key_exists('updated_after', $rest)) { $input['updated_after'] = $rest['updated_after']; unset($rest['updated_after']); } if (array_key_exists('updated_before', $rest)) { $input['updated_before'] = $rest['updated_before']; unset($rest['updated_before']); } if (array_key_exists('Flint-Version', $rest)) { $input['Flint-Version'] = $rest['Flint-Version']; unset($rest['Flint-Version']); } foreach ($rest as $name => $value) { if (array_key_exists($name, $input)) throw new SdkError('validation', 'Path values belong in positional arguments', 'not_sent'); $input[$name] = $value; } return $this->runtime->items('listOrganizations', $input instanceof OrganizationsListInput ? $input->toInputArray() : (new OrganizationsListInput($input))->toInputArray(), $options); }
    /** Revokes a direct organization membership for a user.
     * @param array<array-key, mixed>|Model|null $params Flat body fields and query/header parameters; path arguments follow URL order.
     * @return RevokeOrganizationMembershipResult
     */
    public function revokeMembership(string|Model $organization_id, string|Model $user_id, array|Model|null $params = null, ?RequestOptions $options = null): RevokeOrganizationMembershipResult { $input = ['organization_id' => $organization_id, 'user_id' => $user_id]; $params = $params instanceof Model ? $params->toInputArray() : $params; $rest = $params ?? []; if ($rest && array_is_list($rest)) throw new SdkError('validation', 'Expected associative params', 'not_sent'); if (array_key_exists('Idempotency-Key', $rest)) { $input['Idempotency-Key'] = $rest['Idempotency-Key']; unset($rest['Idempotency-Key']); } if (array_key_exists('X-Request-Id', $rest)) { $input['X-Request-Id'] = $rest['X-Request-Id']; unset($rest['X-Request-Id']); } if (array_key_exists('Flint-Version', $rest)) { $input['Flint-Version'] = $rest['Flint-Version']; unset($rest['Flint-Version']); } foreach ($rest as $name => $value) { if (array_key_exists($name, $input)) throw new SdkError('validation', 'Path values belong in positional arguments', 'not_sent'); $input[$name] = $value; } return SdkResponse::payload($this->runtime->request('revokeOrganizationMembership', $input instanceof OrganizationsRevokeMembershipInput ? $input->toInputArray() : (new OrganizationsRevokeMembershipInput($input))->toInputArray(), $options), ['data']); }
    /** @return SdkResponse<OrganizationsRevokeMembershipResponse200> */
    public function revokeMembershipWithResponse(string|Model $organization_id, string|Model $user_id, array|Model|null $params = null, ?RequestOptions $options = null): SdkResponse { $input = ['organization_id' => $organization_id, 'user_id' => $user_id]; $params = $params instanceof Model ? $params->toInputArray() : $params; $rest = $params ?? []; if ($rest && array_is_list($rest)) throw new SdkError('validation', 'Expected associative params', 'not_sent'); if (array_key_exists('Idempotency-Key', $rest)) { $input['Idempotency-Key'] = $rest['Idempotency-Key']; unset($rest['Idempotency-Key']); } if (array_key_exists('X-Request-Id', $rest)) { $input['X-Request-Id'] = $rest['X-Request-Id']; unset($rest['X-Request-Id']); } if (array_key_exists('Flint-Version', $rest)) { $input['Flint-Version'] = $rest['Flint-Version']; unset($rest['Flint-Version']); } foreach ($rest as $name => $value) { if (array_key_exists($name, $input)) throw new SdkError('validation', 'Path values belong in positional arguments', 'not_sent'); $input[$name] = $value; } $result = $this->runtime->request('revokeOrganizationMembership', $input instanceof OrganizationsRevokeMembershipInput ? $input->toInputArray() : (new OrganizationsRevokeMembershipInput($input))->toInputArray(), $options); return new SdkResponse($result->data, $result->meta, $result->raw); }
    /** Transfers the organization owner role to another user.
     * @param array<array-key, mixed>|Model $params Flat body fields and query/header parameters; path arguments follow URL order.
     * @return TransferOrganizationOwnershipResult
     */
    public function transferOwnership(string|Model $organization_id, array|Model $params, ?RequestOptions $options = null): TransferOrganizationOwnershipResult { $input = ['organization_id' => $organization_id]; $params = $params instanceof Model ? $params->toInputArray() : $params; $rest = $params ?? []; if ($rest && array_is_list($rest)) throw new SdkError('validation', 'Expected associative params', 'not_sent'); if (array_key_exists('Idempotency-Key', $rest)) { $input['Idempotency-Key'] = $rest['Idempotency-Key']; unset($rest['Idempotency-Key']); } if (array_key_exists('X-Request-Id', $rest)) { $input['X-Request-Id'] = $rest['X-Request-Id']; unset($rest['X-Request-Id']); } if (array_key_exists('Flint-Version', $rest)) { $input['Flint-Version'] = $rest['Flint-Version']; unset($rest['Flint-Version']); } if (true) $input['body'] = (object) $rest; return SdkResponse::payload($this->runtime->request('transferOrganizationOwnership', $input instanceof OrganizationsTransferOwnershipInput ? $input->toInputArray() : (new OrganizationsTransferOwnershipInput($input))->toInputArray(), $options), ['data']); }
    /** @return SdkResponse<OrganizationsTransferOwnershipResponse200> */
    public function transferOwnershipWithResponse(string|Model $organization_id, array|Model $params, ?RequestOptions $options = null): SdkResponse { $input = ['organization_id' => $organization_id]; $params = $params instanceof Model ? $params->toInputArray() : $params; $rest = $params ?? []; if ($rest && array_is_list($rest)) throw new SdkError('validation', 'Expected associative params', 'not_sent'); if (array_key_exists('Idempotency-Key', $rest)) { $input['Idempotency-Key'] = $rest['Idempotency-Key']; unset($rest['Idempotency-Key']); } if (array_key_exists('X-Request-Id', $rest)) { $input['X-Request-Id'] = $rest['X-Request-Id']; unset($rest['X-Request-Id']); } if (array_key_exists('Flint-Version', $rest)) { $input['Flint-Version'] = $rest['Flint-Version']; unset($rest['Flint-Version']); } if (true) $input['body'] = (object) $rest; $result = $this->runtime->request('transferOrganizationOwnership', $input instanceof OrganizationsTransferOwnershipInput ? $input->toInputArray() : (new OrganizationsTransferOwnershipInput($input))->toInputArray(), $options); return new SdkResponse($result->data, $result->meta, $result->raw); }
    /** Applies a sparse update to an accessible organization.
     * @param array<array-key, mixed>|Model $params Flat body fields and query/header parameters; path arguments follow URL order.
     * @return Organization
     */
    public function update(string|Model $organization_id, array|Model $params, ?RequestOptions $options = null): Organization { $input = ['organization_id' => $organization_id]; $params = $params instanceof Model ? $params->toInputArray() : $params; $rest = $params ?? []; if ($rest && array_is_list($rest)) throw new SdkError('validation', 'Expected associative params', 'not_sent'); if (array_key_exists('Idempotency-Key', $rest)) { $input['Idempotency-Key'] = $rest['Idempotency-Key']; unset($rest['Idempotency-Key']); } if (array_key_exists('X-Request-Id', $rest)) { $input['X-Request-Id'] = $rest['X-Request-Id']; unset($rest['X-Request-Id']); } if (array_key_exists('Flint-Version', $rest)) { $input['Flint-Version'] = $rest['Flint-Version']; unset($rest['Flint-Version']); } if (true) $input['body'] = (object) $rest; return SdkResponse::payload($this->runtime->request('updateOrganization', $input instanceof OrganizationsUpdateInput ? $input->toInputArray() : (new OrganizationsUpdateInput($input))->toInputArray(), $options), ['data']); }
    /** @return SdkResponse<OrganizationsUpdateResponse200> */
    public function updateWithResponse(string|Model $organization_id, array|Model $params, ?RequestOptions $options = null): SdkResponse { $input = ['organization_id' => $organization_id]; $params = $params instanceof Model ? $params->toInputArray() : $params; $rest = $params ?? []; if ($rest && array_is_list($rest)) throw new SdkError('validation', 'Expected associative params', 'not_sent'); if (array_key_exists('Idempotency-Key', $rest)) { $input['Idempotency-Key'] = $rest['Idempotency-Key']; unset($rest['Idempotency-Key']); } if (array_key_exists('X-Request-Id', $rest)) { $input['X-Request-Id'] = $rest['X-Request-Id']; unset($rest['X-Request-Id']); } if (array_key_exists('Flint-Version', $rest)) { $input['Flint-Version'] = $rest['Flint-Version']; unset($rest['Flint-Version']); } if (true) $input['body'] = (object) $rest; $result = $this->runtime->request('updateOrganization', $input instanceof OrganizationsUpdateInput ? $input->toInputArray() : (new OrganizationsUpdateInput($input))->toInputArray(), $options); return new SdkResponse($result->data, $result->meta, $result->raw); }
}
