<?php
declare(strict_types=1);
namespace Flint;
final class ReturnPoliciesResource {
    public function __construct(private readonly Runtime $runtime) {}
    /** Create a Return policy with its first revision. The policy ID is stable across revisions, and each published revision is immutable.
     * @param array<array-key, mixed>|Model $params Flat body fields and query/header parameters; path arguments follow URL order.
     * @return ReturnPolicy
     */
    public function create(array|Model $params, ?RequestOptions $options = null): ReturnPolicy { $input = []; $params = $params instanceof Model ? $params->toInputArray() : $params; $rest = $params ?? []; if ($rest && array_is_list($rest)) throw new SdkError('validation', 'Expected associative params', 'not_sent'); if (array_key_exists('Idempotency-Key', $rest)) { $input['Idempotency-Key'] = $rest['Idempotency-Key']; unset($rest['Idempotency-Key']); } if (array_key_exists('Flint-Version', $rest)) { $input['Flint-Version'] = $rest['Flint-Version']; unset($rest['Flint-Version']); } if (true) $input['body'] = (object) $rest; return SdkResponse::payload($this->runtime->request('createReturnPolicy', $input instanceof ReturnPoliciesCreateInput ? $input->toInputArray() : (new ReturnPoliciesCreateInput($input))->toInputArray(), $options), ['data']); }
    /** @return SdkResponse<ReturnPoliciesCreateResponse201> */
    public function createWithResponse(array|Model $params, ?RequestOptions $options = null): SdkResponse { $input = []; $params = $params instanceof Model ? $params->toInputArray() : $params; $rest = $params ?? []; if ($rest && array_is_list($rest)) throw new SdkError('validation', 'Expected associative params', 'not_sent'); if (array_key_exists('Idempotency-Key', $rest)) { $input['Idempotency-Key'] = $rest['Idempotency-Key']; unset($rest['Idempotency-Key']); } if (array_key_exists('Flint-Version', $rest)) { $input['Flint-Version'] = $rest['Flint-Version']; unset($rest['Flint-Version']); } if (true) $input['body'] = (object) $rest; $result = $this->runtime->request('createReturnPolicy', $input instanceof ReturnPoliciesCreateInput ? $input->toInputArray() : (new ReturnPoliciesCreateInput($input))->toInputArray(), $options); return new SdkResponse($result->data, $result->meta, $result->raw); }
    /** Retire a Return policy so it is no longer evaluated and no longer appears as an active choice.
     * @param array<array-key, mixed>|Model|null $params Flat body fields and query/header parameters; path arguments follow URL order.
     * @return ReturnPolicy
     */
    public function remove(string|Model $return_policy_id, array|Model|null $params = null, ?RequestOptions $options = null): ReturnPolicy { $input = ['return_policy_id' => $return_policy_id]; $params = $params instanceof Model ? $params->toInputArray() : $params; $rest = $params ?? []; if ($rest && array_is_list($rest)) throw new SdkError('validation', 'Expected associative params', 'not_sent'); if (array_key_exists('expected_version', $rest)) { $input['expected_version'] = $rest['expected_version']; unset($rest['expected_version']); } if (array_key_exists('Idempotency-Key', $rest)) { $input['Idempotency-Key'] = $rest['Idempotency-Key']; unset($rest['Idempotency-Key']); } if (array_key_exists('Flint-Version', $rest)) { $input['Flint-Version'] = $rest['Flint-Version']; unset($rest['Flint-Version']); } foreach ($rest as $name => $value) { if (array_key_exists($name, $input)) throw new SdkError('validation', 'Path values belong in positional arguments', 'not_sent'); $input[$name] = $value; } return SdkResponse::payload($this->runtime->request('deleteReturnPolicy', $input instanceof ReturnPoliciesRemoveInput ? $input->toInputArray() : (new ReturnPoliciesRemoveInput($input))->toInputArray(), $options), ['data']); }
    /** @return SdkResponse<ReturnPoliciesRemoveResponse200> */
    public function removeWithResponse(string|Model $return_policy_id, array|Model|null $params = null, ?RequestOptions $options = null): SdkResponse { $input = ['return_policy_id' => $return_policy_id]; $params = $params instanceof Model ? $params->toInputArray() : $params; $rest = $params ?? []; if ($rest && array_is_list($rest)) throw new SdkError('validation', 'Expected associative params', 'not_sent'); if (array_key_exists('expected_version', $rest)) { $input['expected_version'] = $rest['expected_version']; unset($rest['expected_version']); } if (array_key_exists('Idempotency-Key', $rest)) { $input['Idempotency-Key'] = $rest['Idempotency-Key']; unset($rest['Idempotency-Key']); } if (array_key_exists('Flint-Version', $rest)) { $input['Flint-Version'] = $rest['Flint-Version']; unset($rest['Flint-Version']); } foreach ($rest as $name => $value) { if (array_key_exists($name, $input)) throw new SdkError('validation', 'Path values belong in positional arguments', 'not_sent'); $input[$name] = $value; } $result = $this->runtime->request('deleteReturnPolicy', $input instanceof ReturnPoliciesRemoveInput ? $input->toInputArray() : (new ReturnPoliciesRemoveInput($input))->toInputArray(), $options); return new SdkResponse($result->data, $result->meta, $result->raw); }
    /** Retrieve one Return policy. Supports expand for current_revision.
     * @param array<array-key, mixed>|Model|null $params Flat body fields and query/header parameters; path arguments follow URL order.
     * @return ReturnPolicy
     */
    public function get(string|Model $return_policy_id, array|Model|null $params = null, ?RequestOptions $options = null): ReturnPolicy { $input = ['return_policy_id' => $return_policy_id]; $params = $params instanceof Model ? $params->toInputArray() : $params; $rest = $params ?? []; if ($rest && array_is_list($rest)) throw new SdkError('validation', 'Expected associative params', 'not_sent'); if (array_key_exists('expand', $rest)) { $input['expand'] = $rest['expand']; unset($rest['expand']); } if (array_key_exists('Flint-Version', $rest)) { $input['Flint-Version'] = $rest['Flint-Version']; unset($rest['Flint-Version']); } foreach ($rest as $name => $value) { if (array_key_exists($name, $input)) throw new SdkError('validation', 'Path values belong in positional arguments', 'not_sent'); $input[$name] = $value; } return SdkResponse::payload($this->runtime->request('getReturnPolicy', $input instanceof ReturnPoliciesGetInput ? $input->toInputArray() : (new ReturnPoliciesGetInput($input))->toInputArray(), $options), ['data']); }
    /** @return SdkResponse<ReturnPoliciesGetResponse200> */
    public function getWithResponse(string|Model $return_policy_id, array|Model|null $params = null, ?RequestOptions $options = null): SdkResponse { $input = ['return_policy_id' => $return_policy_id]; $params = $params instanceof Model ? $params->toInputArray() : $params; $rest = $params ?? []; if ($rest && array_is_list($rest)) throw new SdkError('validation', 'Expected associative params', 'not_sent'); if (array_key_exists('expand', $rest)) { $input['expand'] = $rest['expand']; unset($rest['expand']); } if (array_key_exists('Flint-Version', $rest)) { $input['Flint-Version'] = $rest['Flint-Version']; unset($rest['Flint-Version']); } foreach ($rest as $name => $value) { if (array_key_exists($name, $input)) throw new SdkError('validation', 'Path values belong in positional arguments', 'not_sent'); $input[$name] = $value; } $result = $this->runtime->request('getReturnPolicy', $input instanceof ReturnPoliciesGetInput ? $input->toInputArray() : (new ReturnPoliciesGetInput($input))->toInputArray(), $options); return new SdkResponse($result->data, $result->meta, $result->raw); }
    /** Retrieve one immutable policy revision, including the exact rules a Return was evaluated against.
     * @param array<array-key, mixed>|Model|null $params Flat body fields and query/header parameters; path arguments follow URL order.
     * @return ReturnPolicyRevision
     */
    public function getRevision(string|Model $return_policy_id, string|Model $return_policy_revision_id, array|Model|null $params = null, ?RequestOptions $options = null): ReturnPolicyRevision { $input = ['return_policy_id' => $return_policy_id, 'return_policy_revision_id' => $return_policy_revision_id]; $params = $params instanceof Model ? $params->toInputArray() : $params; $rest = $params ?? []; if ($rest && array_is_list($rest)) throw new SdkError('validation', 'Expected associative params', 'not_sent'); if (array_key_exists('Flint-Version', $rest)) { $input['Flint-Version'] = $rest['Flint-Version']; unset($rest['Flint-Version']); } foreach ($rest as $name => $value) { if (array_key_exists($name, $input)) throw new SdkError('validation', 'Path values belong in positional arguments', 'not_sent'); $input[$name] = $value; } return SdkResponse::payload($this->runtime->request('getReturnPolicyRevision', $input instanceof ReturnPoliciesGetRevisionInput ? $input->toInputArray() : (new ReturnPoliciesGetRevisionInput($input))->toInputArray(), $options), ['data']); }
    /** @return SdkResponse<ReturnPoliciesGetRevisionResponse200> */
    public function getRevisionWithResponse(string|Model $return_policy_id, string|Model $return_policy_revision_id, array|Model|null $params = null, ?RequestOptions $options = null): SdkResponse { $input = ['return_policy_id' => $return_policy_id, 'return_policy_revision_id' => $return_policy_revision_id]; $params = $params instanceof Model ? $params->toInputArray() : $params; $rest = $params ?? []; if ($rest && array_is_list($rest)) throw new SdkError('validation', 'Expected associative params', 'not_sent'); if (array_key_exists('Flint-Version', $rest)) { $input['Flint-Version'] = $rest['Flint-Version']; unset($rest['Flint-Version']); } foreach ($rest as $name => $value) { if (array_key_exists($name, $input)) throw new SdkError('validation', 'Path values belong in positional arguments', 'not_sent'); $input[$name] = $value; } $result = $this->runtime->request('getReturnPolicyRevision', $input instanceof ReturnPoliciesGetRevisionInput ? $input->toInputArray() : (new ReturnPoliciesGetRevisionInput($input))->toInputArray(), $options); return new SdkResponse($result->data, $result->meta, $result->raw); }
    /** List Return policies with their status and current revision.
     * @param array<array-key, mixed>|Model|null $params Flat body fields and query/header parameters; path arguments follow URL order.
     * @return ReturnPoliciesListResponse200
     */
    public function list(array|Model|null $params = null, ?RequestOptions $options = null): ReturnPoliciesListResponse200 { $input = []; $params = $params instanceof Model ? $params->toInputArray() : $params; $rest = $params ?? []; if ($rest && array_is_list($rest)) throw new SdkError('validation', 'Expected associative params', 'not_sent'); if (array_key_exists('external_reference_id', $rest)) { $input['external_reference_id'] = $rest['external_reference_id']; unset($rest['external_reference_id']); } if (array_key_exists('page_size', $rest)) { $input['page_size'] = $rest['page_size']; unset($rest['page_size']); } if (array_key_exists('page_token', $rest)) { $input['page_token'] = $rest['page_token']; unset($rest['page_token']); } if (array_key_exists('query', $rest)) { $input['query'] = $rest['query']; unset($rest['query']); } if (array_key_exists('status', $rest)) { $input['status'] = $rest['status']; unset($rest['status']); } if (array_key_exists('Flint-Version', $rest)) { $input['Flint-Version'] = $rest['Flint-Version']; unset($rest['Flint-Version']); } foreach ($rest as $name => $value) { if (array_key_exists($name, $input)) throw new SdkError('validation', 'Path values belong in positional arguments', 'not_sent'); $input[$name] = $value; } return SdkResponse::payload($this->runtime->request('listReturnPolicies', $input instanceof ReturnPoliciesListInput ? $input->toInputArray() : (new ReturnPoliciesListInput($input))->toInputArray(), $options), []); }
    /** @return SdkResponse<ReturnPoliciesListResponse200> */
    public function listWithResponse(array|Model|null $params = null, ?RequestOptions $options = null): SdkResponse { $input = []; $params = $params instanceof Model ? $params->toInputArray() : $params; $rest = $params ?? []; if ($rest && array_is_list($rest)) throw new SdkError('validation', 'Expected associative params', 'not_sent'); if (array_key_exists('external_reference_id', $rest)) { $input['external_reference_id'] = $rest['external_reference_id']; unset($rest['external_reference_id']); } if (array_key_exists('page_size', $rest)) { $input['page_size'] = $rest['page_size']; unset($rest['page_size']); } if (array_key_exists('page_token', $rest)) { $input['page_token'] = $rest['page_token']; unset($rest['page_token']); } if (array_key_exists('query', $rest)) { $input['query'] = $rest['query']; unset($rest['query']); } if (array_key_exists('status', $rest)) { $input['status'] = $rest['status']; unset($rest['status']); } if (array_key_exists('Flint-Version', $rest)) { $input['Flint-Version'] = $rest['Flint-Version']; unset($rest['Flint-Version']); } foreach ($rest as $name => $value) { if (array_key_exists($name, $input)) throw new SdkError('validation', 'Path values belong in positional arguments', 'not_sent'); $input[$name] = $value; } $result = $this->runtime->request('listReturnPolicies', $input instanceof ReturnPoliciesListInput ? $input->toInputArray() : (new ReturnPoliciesListInput($input))->toInputArray(), $options); return new SdkResponse($result->data, $result->meta, $result->raw); }
    /** @return \Generator<int, ReturnPoliciesListResponse200> */
    public function listPages(array|Model|null $params = null, ?RequestOptions $options = null): \Generator { $input = []; $params = $params instanceof Model ? $params->toInputArray() : $params; $rest = $params ?? []; if ($rest && array_is_list($rest)) throw new SdkError('validation', 'Expected associative params', 'not_sent'); if (array_key_exists('external_reference_id', $rest)) { $input['external_reference_id'] = $rest['external_reference_id']; unset($rest['external_reference_id']); } if (array_key_exists('page_size', $rest)) { $input['page_size'] = $rest['page_size']; unset($rest['page_size']); } if (array_key_exists('page_token', $rest)) { $input['page_token'] = $rest['page_token']; unset($rest['page_token']); } if (array_key_exists('query', $rest)) { $input['query'] = $rest['query']; unset($rest['query']); } if (array_key_exists('status', $rest)) { $input['status'] = $rest['status']; unset($rest['status']); } if (array_key_exists('Flint-Version', $rest)) { $input['Flint-Version'] = $rest['Flint-Version']; unset($rest['Flint-Version']); } foreach ($rest as $name => $value) { if (array_key_exists($name, $input)) throw new SdkError('validation', 'Path values belong in positional arguments', 'not_sent'); $input[$name] = $value; } return SdkResponse::payloadPages($this->runtime->pages('listReturnPolicies', $input instanceof ReturnPoliciesListInput ? $input->toInputArray() : (new ReturnPoliciesListInput($input))->toInputArray(), $options), []); }
    /** @return \Generator<int, SdkResponse<ReturnPoliciesListResponse200>> */
    public function listPagesWithResponse(array|Model|null $params = null, ?RequestOptions $options = null): \Generator { $input = []; $params = $params instanceof Model ? $params->toInputArray() : $params; $rest = $params ?? []; if ($rest && array_is_list($rest)) throw new SdkError('validation', 'Expected associative params', 'not_sent'); if (array_key_exists('external_reference_id', $rest)) { $input['external_reference_id'] = $rest['external_reference_id']; unset($rest['external_reference_id']); } if (array_key_exists('page_size', $rest)) { $input['page_size'] = $rest['page_size']; unset($rest['page_size']); } if (array_key_exists('page_token', $rest)) { $input['page_token'] = $rest['page_token']; unset($rest['page_token']); } if (array_key_exists('query', $rest)) { $input['query'] = $rest['query']; unset($rest['query']); } if (array_key_exists('status', $rest)) { $input['status'] = $rest['status']; unset($rest['status']); } if (array_key_exists('Flint-Version', $rest)) { $input['Flint-Version'] = $rest['Flint-Version']; unset($rest['Flint-Version']); } foreach ($rest as $name => $value) { if (array_key_exists($name, $input)) throw new SdkError('validation', 'Path values belong in positional arguments', 'not_sent'); $input[$name] = $value; } return SdkResponse::responsePages($this->runtime->pages('listReturnPolicies', $input instanceof ReturnPoliciesListInput ? $input->toInputArray() : (new ReturnPoliciesListInput($input))->toInputArray(), $options)); }
    /** @return \Generator<int, ReturnPolicy> */
    public function listItems(array|Model|null $params = null, ?RequestOptions $options = null): \Generator { $input = []; $params = $params instanceof Model ? $params->toInputArray() : $params; $rest = $params ?? []; if ($rest && array_is_list($rest)) throw new SdkError('validation', 'Expected associative params', 'not_sent'); if (array_key_exists('external_reference_id', $rest)) { $input['external_reference_id'] = $rest['external_reference_id']; unset($rest['external_reference_id']); } if (array_key_exists('page_size', $rest)) { $input['page_size'] = $rest['page_size']; unset($rest['page_size']); } if (array_key_exists('page_token', $rest)) { $input['page_token'] = $rest['page_token']; unset($rest['page_token']); } if (array_key_exists('query', $rest)) { $input['query'] = $rest['query']; unset($rest['query']); } if (array_key_exists('status', $rest)) { $input['status'] = $rest['status']; unset($rest['status']); } if (array_key_exists('Flint-Version', $rest)) { $input['Flint-Version'] = $rest['Flint-Version']; unset($rest['Flint-Version']); } foreach ($rest as $name => $value) { if (array_key_exists($name, $input)) throw new SdkError('validation', 'Path values belong in positional arguments', 'not_sent'); $input[$name] = $value; } return $this->runtime->items('listReturnPolicies', $input instanceof ReturnPoliciesListInput ? $input->toInputArray() : (new ReturnPoliciesListInput($input))->toInputArray(), $options); }
    /** List every published revision of a Return policy.
     * @param array<array-key, mixed>|Model|null $params Flat body fields and query/header parameters; path arguments follow URL order.
     * @return ReturnPoliciesListRevisionsResponse200
     */
    public function listRevisions(string|Model $return_policy_id, array|Model|null $params = null, ?RequestOptions $options = null): ReturnPoliciesListRevisionsResponse200 { $input = ['return_policy_id' => $return_policy_id]; $params = $params instanceof Model ? $params->toInputArray() : $params; $rest = $params ?? []; if ($rest && array_is_list($rest)) throw new SdkError('validation', 'Expected associative params', 'not_sent'); if (array_key_exists('page_size', $rest)) { $input['page_size'] = $rest['page_size']; unset($rest['page_size']); } if (array_key_exists('page_token', $rest)) { $input['page_token'] = $rest['page_token']; unset($rest['page_token']); } if (array_key_exists('Flint-Version', $rest)) { $input['Flint-Version'] = $rest['Flint-Version']; unset($rest['Flint-Version']); } foreach ($rest as $name => $value) { if (array_key_exists($name, $input)) throw new SdkError('validation', 'Path values belong in positional arguments', 'not_sent'); $input[$name] = $value; } return SdkResponse::payload($this->runtime->request('listReturnPolicyRevisions', $input instanceof ReturnPoliciesListRevisionsInput ? $input->toInputArray() : (new ReturnPoliciesListRevisionsInput($input))->toInputArray(), $options), []); }
    /** @return SdkResponse<ReturnPoliciesListRevisionsResponse200> */
    public function listRevisionsWithResponse(string|Model $return_policy_id, array|Model|null $params = null, ?RequestOptions $options = null): SdkResponse { $input = ['return_policy_id' => $return_policy_id]; $params = $params instanceof Model ? $params->toInputArray() : $params; $rest = $params ?? []; if ($rest && array_is_list($rest)) throw new SdkError('validation', 'Expected associative params', 'not_sent'); if (array_key_exists('page_size', $rest)) { $input['page_size'] = $rest['page_size']; unset($rest['page_size']); } if (array_key_exists('page_token', $rest)) { $input['page_token'] = $rest['page_token']; unset($rest['page_token']); } if (array_key_exists('Flint-Version', $rest)) { $input['Flint-Version'] = $rest['Flint-Version']; unset($rest['Flint-Version']); } foreach ($rest as $name => $value) { if (array_key_exists($name, $input)) throw new SdkError('validation', 'Path values belong in positional arguments', 'not_sent'); $input[$name] = $value; } $result = $this->runtime->request('listReturnPolicyRevisions', $input instanceof ReturnPoliciesListRevisionsInput ? $input->toInputArray() : (new ReturnPoliciesListRevisionsInput($input))->toInputArray(), $options); return new SdkResponse($result->data, $result->meta, $result->raw); }
    /** @return \Generator<int, ReturnPoliciesListRevisionsResponse200> */
    public function listRevisionsPages(string|Model $return_policy_id, array|Model|null $params = null, ?RequestOptions $options = null): \Generator { $input = ['return_policy_id' => $return_policy_id]; $params = $params instanceof Model ? $params->toInputArray() : $params; $rest = $params ?? []; if ($rest && array_is_list($rest)) throw new SdkError('validation', 'Expected associative params', 'not_sent'); if (array_key_exists('page_size', $rest)) { $input['page_size'] = $rest['page_size']; unset($rest['page_size']); } if (array_key_exists('page_token', $rest)) { $input['page_token'] = $rest['page_token']; unset($rest['page_token']); } if (array_key_exists('Flint-Version', $rest)) { $input['Flint-Version'] = $rest['Flint-Version']; unset($rest['Flint-Version']); } foreach ($rest as $name => $value) { if (array_key_exists($name, $input)) throw new SdkError('validation', 'Path values belong in positional arguments', 'not_sent'); $input[$name] = $value; } return SdkResponse::payloadPages($this->runtime->pages('listReturnPolicyRevisions', $input instanceof ReturnPoliciesListRevisionsInput ? $input->toInputArray() : (new ReturnPoliciesListRevisionsInput($input))->toInputArray(), $options), []); }
    /** @return \Generator<int, SdkResponse<ReturnPoliciesListRevisionsResponse200>> */
    public function listRevisionsPagesWithResponse(string|Model $return_policy_id, array|Model|null $params = null, ?RequestOptions $options = null): \Generator { $input = ['return_policy_id' => $return_policy_id]; $params = $params instanceof Model ? $params->toInputArray() : $params; $rest = $params ?? []; if ($rest && array_is_list($rest)) throw new SdkError('validation', 'Expected associative params', 'not_sent'); if (array_key_exists('page_size', $rest)) { $input['page_size'] = $rest['page_size']; unset($rest['page_size']); } if (array_key_exists('page_token', $rest)) { $input['page_token'] = $rest['page_token']; unset($rest['page_token']); } if (array_key_exists('Flint-Version', $rest)) { $input['Flint-Version'] = $rest['Flint-Version']; unset($rest['Flint-Version']); } foreach ($rest as $name => $value) { if (array_key_exists($name, $input)) throw new SdkError('validation', 'Path values belong in positional arguments', 'not_sent'); $input[$name] = $value; } return SdkResponse::responsePages($this->runtime->pages('listReturnPolicyRevisions', $input instanceof ReturnPoliciesListRevisionsInput ? $input->toInputArray() : (new ReturnPoliciesListRevisionsInput($input))->toInputArray(), $options)); }
    /** @return \Generator<int, ReturnPolicyRevision> */
    public function listRevisionsItems(string|Model $return_policy_id, array|Model|null $params = null, ?RequestOptions $options = null): \Generator { $input = ['return_policy_id' => $return_policy_id]; $params = $params instanceof Model ? $params->toInputArray() : $params; $rest = $params ?? []; if ($rest && array_is_list($rest)) throw new SdkError('validation', 'Expected associative params', 'not_sent'); if (array_key_exists('page_size', $rest)) { $input['page_size'] = $rest['page_size']; unset($rest['page_size']); } if (array_key_exists('page_token', $rest)) { $input['page_token'] = $rest['page_token']; unset($rest['page_token']); } if (array_key_exists('Flint-Version', $rest)) { $input['Flint-Version'] = $rest['Flint-Version']; unset($rest['Flint-Version']); } foreach ($rest as $name => $value) { if (array_key_exists($name, $input)) throw new SdkError('validation', 'Path values belong in positional arguments', 'not_sent'); $input[$name] = $value; } return $this->runtime->items('listReturnPolicyRevisions', $input instanceof ReturnPoliciesListRevisionsInput ? $input->toInputArray() : (new ReturnPoliciesListRevisionsInput($input))->toInputArray(), $options); }
    /** Publish a new immutable Return policy revision while preserving the stable policy identity.
     * @param array<array-key, mixed>|Model $params Flat body fields and query/header parameters; path arguments follow URL order.
     * @return ReturnPolicy
     */
    public function publishRevision(string|Model $return_policy_id, array|Model $params, ?RequestOptions $options = null): ReturnPolicy { $input = ['return_policy_id' => $return_policy_id]; $params = $params instanceof Model ? $params->toInputArray() : $params; $rest = $params ?? []; if ($rest && array_is_list($rest)) throw new SdkError('validation', 'Expected associative params', 'not_sent'); if (array_key_exists('Idempotency-Key', $rest)) { $input['Idempotency-Key'] = $rest['Idempotency-Key']; unset($rest['Idempotency-Key']); } if (array_key_exists('Flint-Version', $rest)) { $input['Flint-Version'] = $rest['Flint-Version']; unset($rest['Flint-Version']); } if (true) $input['body'] = (object) $rest; return SdkResponse::payload($this->runtime->request('publishReturnPolicyRevision', $input instanceof ReturnPoliciesPublishRevisionInput ? $input->toInputArray() : (new ReturnPoliciesPublishRevisionInput($input))->toInputArray(), $options), ['data']); }
    /** @return SdkResponse<ReturnPoliciesPublishRevisionResponse200> */
    public function publishRevisionWithResponse(string|Model $return_policy_id, array|Model $params, ?RequestOptions $options = null): SdkResponse { $input = ['return_policy_id' => $return_policy_id]; $params = $params instanceof Model ? $params->toInputArray() : $params; $rest = $params ?? []; if ($rest && array_is_list($rest)) throw new SdkError('validation', 'Expected associative params', 'not_sent'); if (array_key_exists('Idempotency-Key', $rest)) { $input['Idempotency-Key'] = $rest['Idempotency-Key']; unset($rest['Idempotency-Key']); } if (array_key_exists('Flint-Version', $rest)) { $input['Flint-Version'] = $rest['Flint-Version']; unset($rest['Flint-Version']); } if (true) $input['body'] = (object) $rest; $result = $this->runtime->request('publishReturnPolicyRevision', $input instanceof ReturnPoliciesPublishRevisionInput ? $input->toInputArray() : (new ReturnPoliciesPublishRevisionInput($input))->toInputArray(), $options); return new SdkResponse($result->data, $result->meta, $result->raw); }
    /** Update policy identity fields or set status to active or inactive. Rules live on revisions, so changing a window, fee, or scope means publishing a new revision.
     * @param array<array-key, mixed>|Model $params Flat body fields and query/header parameters; path arguments follow URL order.
     * @return ReturnPolicy
     */
    public function update(string|Model $return_policy_id, array|Model $params, ?RequestOptions $options = null): ReturnPolicy { $input = ['return_policy_id' => $return_policy_id]; $params = $params instanceof Model ? $params->toInputArray() : $params; $rest = $params ?? []; if ($rest && array_is_list($rest)) throw new SdkError('validation', 'Expected associative params', 'not_sent'); if (array_key_exists('Idempotency-Key', $rest)) { $input['Idempotency-Key'] = $rest['Idempotency-Key']; unset($rest['Idempotency-Key']); } if (array_key_exists('Flint-Version', $rest)) { $input['Flint-Version'] = $rest['Flint-Version']; unset($rest['Flint-Version']); } if (true) $input['body'] = (object) $rest; return SdkResponse::payload($this->runtime->request('updateReturnPolicy', $input instanceof ReturnPoliciesUpdateInput ? $input->toInputArray() : (new ReturnPoliciesUpdateInput($input))->toInputArray(), $options), ['data']); }
    /** @return SdkResponse<ReturnPoliciesUpdateResponse200> */
    public function updateWithResponse(string|Model $return_policy_id, array|Model $params, ?RequestOptions $options = null): SdkResponse { $input = ['return_policy_id' => $return_policy_id]; $params = $params instanceof Model ? $params->toInputArray() : $params; $rest = $params ?? []; if ($rest && array_is_list($rest)) throw new SdkError('validation', 'Expected associative params', 'not_sent'); if (array_key_exists('Idempotency-Key', $rest)) { $input['Idempotency-Key'] = $rest['Idempotency-Key']; unset($rest['Idempotency-Key']); } if (array_key_exists('Flint-Version', $rest)) { $input['Flint-Version'] = $rest['Flint-Version']; unset($rest['Flint-Version']); } if (true) $input['body'] = (object) $rest; $result = $this->runtime->request('updateReturnPolicy', $input instanceof ReturnPoliciesUpdateInput ? $input->toInputArray() : (new ReturnPoliciesUpdateInput($input))->toInputArray(), $options); return new SdkResponse($result->data, $result->meta, $result->raw); }
}
