<?php
declare(strict_types=1);
namespace Flint;
final class ShipmentsResource {
    public function __construct(private readonly Runtime $runtime) {}
    /** Creates a package record under a shipment. Change package status with POST /v1/packages/{package_id}/transitions; this endpoint records package-level carrier, tracking, label, measurement, and external correlation fields.
     * @param array<array-key, mixed>|Model $params Flat body fields and query/header parameters; path arguments follow URL order.
     * @return CreatePackageResult
     */
    public function createPackage(string|Model $shipment_id, array|Model $params, ?RequestOptions $options = null): CreatePackageResult { $input = ['shipment_id' => $shipment_id]; $params = $params instanceof Model ? $params->toInputArray() : $params; $rest = $params ?? []; if ($rest && array_is_list($rest)) throw new SdkError('validation', 'Expected associative params', 'not_sent'); if (array_key_exists('Idempotency-Key', $rest)) { $input['Idempotency-Key'] = $rest['Idempotency-Key']; unset($rest['Idempotency-Key']); } if (array_key_exists('X-Request-Id', $rest)) { $input['X-Request-Id'] = $rest['X-Request-Id']; unset($rest['X-Request-Id']); } if (array_key_exists('Flint-Version', $rest)) { $input['Flint-Version'] = $rest['Flint-Version']; unset($rest['Flint-Version']); } if (true) $input['body'] = (object) $rest; return SdkResponse::payload($this->runtime->request('createPackage', $input instanceof ShipmentsCreatePackageInput ? $input->toInputArray() : (new ShipmentsCreatePackageInput($input))->toInputArray(), $options), ['data']); }
    /** @return SdkResponse<ShipmentsCreatePackageResponse200|ShipmentsCreatePackageResponse201> */
    public function createPackageWithResponse(string|Model $shipment_id, array|Model $params, ?RequestOptions $options = null): SdkResponse { $input = ['shipment_id' => $shipment_id]; $params = $params instanceof Model ? $params->toInputArray() : $params; $rest = $params ?? []; if ($rest && array_is_list($rest)) throw new SdkError('validation', 'Expected associative params', 'not_sent'); if (array_key_exists('Idempotency-Key', $rest)) { $input['Idempotency-Key'] = $rest['Idempotency-Key']; unset($rest['Idempotency-Key']); } if (array_key_exists('X-Request-Id', $rest)) { $input['X-Request-Id'] = $rest['X-Request-Id']; unset($rest['X-Request-Id']); } if (array_key_exists('Flint-Version', $rest)) { $input['Flint-Version'] = $rest['Flint-Version']; unset($rest['Flint-Version']); } if (true) $input['body'] = (object) $rest; $result = $this->runtime->request('createPackage', $input instanceof ShipmentsCreatePackageInput ? $input->toInputArray() : (new ShipmentsCreatePackageInput($input))->toInputArray(), $options); return new SdkResponse($result->data, $result->meta, $result->raw); }
    /** Retrieves one shipment execution record by ID.
     * @param array<array-key, mixed>|Model|null $params Flat body fields and query/header parameters; path arguments follow URL order.
     * @return Shipment
     */
    public function get(string|Model $shipment_id, array|Model|null $params = null, ?RequestOptions $options = null): Shipment { $input = ['shipment_id' => $shipment_id]; $params = $params instanceof Model ? $params->toInputArray() : $params; $rest = $params ?? []; if ($rest && array_is_list($rest)) throw new SdkError('validation', 'Expected associative params', 'not_sent'); if (array_key_exists('expand', $rest)) { $input['expand'] = $rest['expand']; unset($rest['expand']); } if (array_key_exists('X-Request-Id', $rest)) { $input['X-Request-Id'] = $rest['X-Request-Id']; unset($rest['X-Request-Id']); } if (array_key_exists('Flint-Version', $rest)) { $input['Flint-Version'] = $rest['Flint-Version']; unset($rest['Flint-Version']); } foreach ($rest as $name => $value) { if (array_key_exists($name, $input)) throw new SdkError('validation', 'Path values belong in positional arguments', 'not_sent'); $input[$name] = $value; } return SdkResponse::payload($this->runtime->request('getShipment', $input instanceof ShipmentsGetInput ? $input->toInputArray() : (new ShipmentsGetInput($input))->toInputArray(), $options), ['data']); }
    /** @return SdkResponse<ShipmentsGetResponse200> */
    public function getWithResponse(string|Model $shipment_id, array|Model|null $params = null, ?RequestOptions $options = null): SdkResponse { $input = ['shipment_id' => $shipment_id]; $params = $params instanceof Model ? $params->toInputArray() : $params; $rest = $params ?? []; if ($rest && array_is_list($rest)) throw new SdkError('validation', 'Expected associative params', 'not_sent'); if (array_key_exists('expand', $rest)) { $input['expand'] = $rest['expand']; unset($rest['expand']); } if (array_key_exists('X-Request-Id', $rest)) { $input['X-Request-Id'] = $rest['X-Request-Id']; unset($rest['X-Request-Id']); } if (array_key_exists('Flint-Version', $rest)) { $input['Flint-Version'] = $rest['Flint-Version']; unset($rest['Flint-Version']); } foreach ($rest as $name => $value) { if (array_key_exists($name, $input)) throw new SdkError('validation', 'Path values belong in positional arguments', 'not_sent'); $input[$name] = $value; } $result = $this->runtime->request('getShipment', $input instanceof ShipmentsGetInput ? $input->toInputArray() : (new ShipmentsGetInput($input))->toInputArray(), $options); return new SdkResponse($result->data, $result->meta, $result->raw); }
    /** Lists shipment execution records, newest created first.
     * @param array<array-key, mixed>|Model|null $params Flat body fields and query/header parameters; path arguments follow URL order.
     * @return ShipmentsListResponse200
     */
    public function list(array|Model|null $params = null, ?RequestOptions $options = null): ShipmentsListResponse200 { $input = []; $params = $params instanceof Model ? $params->toInputArray() : $params; $rest = $params ?? []; if ($rest && array_is_list($rest)) throw new SdkError('validation', 'Expected associative params', 'not_sent'); if (array_key_exists('order_id', $rest)) { $input['order_id'] = $rest['order_id']; unset($rest['order_id']); } if (array_key_exists('fulfillment_id', $rest)) { $input['fulfillment_id'] = $rest['fulfillment_id']; unset($rest['fulfillment_id']); } if (array_key_exists('page_size', $rest)) { $input['page_size'] = $rest['page_size']; unset($rest['page_size']); } if (array_key_exists('page_token', $rest)) { $input['page_token'] = $rest['page_token']; unset($rest['page_token']); } if (array_key_exists('external_system', $rest)) { $input['external_system'] = $rest['external_system']; unset($rest['external_system']); } if (array_key_exists('external_reference_id', $rest)) { $input['external_reference_id'] = $rest['external_reference_id']; unset($rest['external_reference_id']); } if (array_key_exists('query', $rest)) { $input['query'] = $rest['query']; unset($rest['query']); } if (array_key_exists('return_id', $rest)) { $input['return_id'] = $rest['return_id']; unset($rest['return_id']); } if (array_key_exists('handed_off_after', $rest)) { $input['handed_off_after'] = $rest['handed_off_after']; unset($rest['handed_off_after']); } if (array_key_exists('handed_off_before', $rest)) { $input['handed_off_before'] = $rest['handed_off_before']; unset($rest['handed_off_before']); } if (array_key_exists('created_after', $rest)) { $input['created_after'] = $rest['created_after']; unset($rest['created_after']); } if (array_key_exists('created_before', $rest)) { $input['created_before'] = $rest['created_before']; unset($rest['created_before']); } if (array_key_exists('X-Request-Id', $rest)) { $input['X-Request-Id'] = $rest['X-Request-Id']; unset($rest['X-Request-Id']); } if (array_key_exists('Flint-Version', $rest)) { $input['Flint-Version'] = $rest['Flint-Version']; unset($rest['Flint-Version']); } foreach ($rest as $name => $value) { if (array_key_exists($name, $input)) throw new SdkError('validation', 'Path values belong in positional arguments', 'not_sent'); $input[$name] = $value; } return SdkResponse::payload($this->runtime->request('listShipments', $input instanceof ShipmentsListInput ? $input->toInputArray() : (new ShipmentsListInput($input))->toInputArray(), $options), []); }
    /** @return SdkResponse<ShipmentsListResponse200> */
    public function listWithResponse(array|Model|null $params = null, ?RequestOptions $options = null): SdkResponse { $input = []; $params = $params instanceof Model ? $params->toInputArray() : $params; $rest = $params ?? []; if ($rest && array_is_list($rest)) throw new SdkError('validation', 'Expected associative params', 'not_sent'); if (array_key_exists('order_id', $rest)) { $input['order_id'] = $rest['order_id']; unset($rest['order_id']); } if (array_key_exists('fulfillment_id', $rest)) { $input['fulfillment_id'] = $rest['fulfillment_id']; unset($rest['fulfillment_id']); } if (array_key_exists('page_size', $rest)) { $input['page_size'] = $rest['page_size']; unset($rest['page_size']); } if (array_key_exists('page_token', $rest)) { $input['page_token'] = $rest['page_token']; unset($rest['page_token']); } if (array_key_exists('external_system', $rest)) { $input['external_system'] = $rest['external_system']; unset($rest['external_system']); } if (array_key_exists('external_reference_id', $rest)) { $input['external_reference_id'] = $rest['external_reference_id']; unset($rest['external_reference_id']); } if (array_key_exists('query', $rest)) { $input['query'] = $rest['query']; unset($rest['query']); } if (array_key_exists('return_id', $rest)) { $input['return_id'] = $rest['return_id']; unset($rest['return_id']); } if (array_key_exists('handed_off_after', $rest)) { $input['handed_off_after'] = $rest['handed_off_after']; unset($rest['handed_off_after']); } if (array_key_exists('handed_off_before', $rest)) { $input['handed_off_before'] = $rest['handed_off_before']; unset($rest['handed_off_before']); } if (array_key_exists('created_after', $rest)) { $input['created_after'] = $rest['created_after']; unset($rest['created_after']); } if (array_key_exists('created_before', $rest)) { $input['created_before'] = $rest['created_before']; unset($rest['created_before']); } if (array_key_exists('X-Request-Id', $rest)) { $input['X-Request-Id'] = $rest['X-Request-Id']; unset($rest['X-Request-Id']); } if (array_key_exists('Flint-Version', $rest)) { $input['Flint-Version'] = $rest['Flint-Version']; unset($rest['Flint-Version']); } foreach ($rest as $name => $value) { if (array_key_exists($name, $input)) throw new SdkError('validation', 'Path values belong in positional arguments', 'not_sent'); $input[$name] = $value; } $result = $this->runtime->request('listShipments', $input instanceof ShipmentsListInput ? $input->toInputArray() : (new ShipmentsListInput($input))->toInputArray(), $options); return new SdkResponse($result->data, $result->meta, $result->raw); }
    /** @return \Generator<int, ShipmentsListResponse200> */
    public function listPages(array|Model|null $params = null, ?RequestOptions $options = null): \Generator { $input = []; $params = $params instanceof Model ? $params->toInputArray() : $params; $rest = $params ?? []; if ($rest && array_is_list($rest)) throw new SdkError('validation', 'Expected associative params', 'not_sent'); if (array_key_exists('order_id', $rest)) { $input['order_id'] = $rest['order_id']; unset($rest['order_id']); } if (array_key_exists('fulfillment_id', $rest)) { $input['fulfillment_id'] = $rest['fulfillment_id']; unset($rest['fulfillment_id']); } if (array_key_exists('page_size', $rest)) { $input['page_size'] = $rest['page_size']; unset($rest['page_size']); } if (array_key_exists('page_token', $rest)) { $input['page_token'] = $rest['page_token']; unset($rest['page_token']); } if (array_key_exists('external_system', $rest)) { $input['external_system'] = $rest['external_system']; unset($rest['external_system']); } if (array_key_exists('external_reference_id', $rest)) { $input['external_reference_id'] = $rest['external_reference_id']; unset($rest['external_reference_id']); } if (array_key_exists('query', $rest)) { $input['query'] = $rest['query']; unset($rest['query']); } if (array_key_exists('return_id', $rest)) { $input['return_id'] = $rest['return_id']; unset($rest['return_id']); } if (array_key_exists('handed_off_after', $rest)) { $input['handed_off_after'] = $rest['handed_off_after']; unset($rest['handed_off_after']); } if (array_key_exists('handed_off_before', $rest)) { $input['handed_off_before'] = $rest['handed_off_before']; unset($rest['handed_off_before']); } if (array_key_exists('created_after', $rest)) { $input['created_after'] = $rest['created_after']; unset($rest['created_after']); } if (array_key_exists('created_before', $rest)) { $input['created_before'] = $rest['created_before']; unset($rest['created_before']); } if (array_key_exists('X-Request-Id', $rest)) { $input['X-Request-Id'] = $rest['X-Request-Id']; unset($rest['X-Request-Id']); } if (array_key_exists('Flint-Version', $rest)) { $input['Flint-Version'] = $rest['Flint-Version']; unset($rest['Flint-Version']); } foreach ($rest as $name => $value) { if (array_key_exists($name, $input)) throw new SdkError('validation', 'Path values belong in positional arguments', 'not_sent'); $input[$name] = $value; } return SdkResponse::payloadPages($this->runtime->pages('listShipments', $input instanceof ShipmentsListInput ? $input->toInputArray() : (new ShipmentsListInput($input))->toInputArray(), $options), []); }
    /** @return \Generator<int, SdkResponse<ShipmentsListResponse200>> */
    public function listPagesWithResponse(array|Model|null $params = null, ?RequestOptions $options = null): \Generator { $input = []; $params = $params instanceof Model ? $params->toInputArray() : $params; $rest = $params ?? []; if ($rest && array_is_list($rest)) throw new SdkError('validation', 'Expected associative params', 'not_sent'); if (array_key_exists('order_id', $rest)) { $input['order_id'] = $rest['order_id']; unset($rest['order_id']); } if (array_key_exists('fulfillment_id', $rest)) { $input['fulfillment_id'] = $rest['fulfillment_id']; unset($rest['fulfillment_id']); } if (array_key_exists('page_size', $rest)) { $input['page_size'] = $rest['page_size']; unset($rest['page_size']); } if (array_key_exists('page_token', $rest)) { $input['page_token'] = $rest['page_token']; unset($rest['page_token']); } if (array_key_exists('external_system', $rest)) { $input['external_system'] = $rest['external_system']; unset($rest['external_system']); } if (array_key_exists('external_reference_id', $rest)) { $input['external_reference_id'] = $rest['external_reference_id']; unset($rest['external_reference_id']); } if (array_key_exists('query', $rest)) { $input['query'] = $rest['query']; unset($rest['query']); } if (array_key_exists('return_id', $rest)) { $input['return_id'] = $rest['return_id']; unset($rest['return_id']); } if (array_key_exists('handed_off_after', $rest)) { $input['handed_off_after'] = $rest['handed_off_after']; unset($rest['handed_off_after']); } if (array_key_exists('handed_off_before', $rest)) { $input['handed_off_before'] = $rest['handed_off_before']; unset($rest['handed_off_before']); } if (array_key_exists('created_after', $rest)) { $input['created_after'] = $rest['created_after']; unset($rest['created_after']); } if (array_key_exists('created_before', $rest)) { $input['created_before'] = $rest['created_before']; unset($rest['created_before']); } if (array_key_exists('X-Request-Id', $rest)) { $input['X-Request-Id'] = $rest['X-Request-Id']; unset($rest['X-Request-Id']); } if (array_key_exists('Flint-Version', $rest)) { $input['Flint-Version'] = $rest['Flint-Version']; unset($rest['Flint-Version']); } foreach ($rest as $name => $value) { if (array_key_exists($name, $input)) throw new SdkError('validation', 'Path values belong in positional arguments', 'not_sent'); $input[$name] = $value; } return SdkResponse::responsePages($this->runtime->pages('listShipments', $input instanceof ShipmentsListInput ? $input->toInputArray() : (new ShipmentsListInput($input))->toInputArray(), $options)); }
    /** @return \Generator<int, Shipment> */
    public function listItems(array|Model|null $params = null, ?RequestOptions $options = null): \Generator { $input = []; $params = $params instanceof Model ? $params->toInputArray() : $params; $rest = $params ?? []; if ($rest && array_is_list($rest)) throw new SdkError('validation', 'Expected associative params', 'not_sent'); if (array_key_exists('order_id', $rest)) { $input['order_id'] = $rest['order_id']; unset($rest['order_id']); } if (array_key_exists('fulfillment_id', $rest)) { $input['fulfillment_id'] = $rest['fulfillment_id']; unset($rest['fulfillment_id']); } if (array_key_exists('page_size', $rest)) { $input['page_size'] = $rest['page_size']; unset($rest['page_size']); } if (array_key_exists('page_token', $rest)) { $input['page_token'] = $rest['page_token']; unset($rest['page_token']); } if (array_key_exists('external_system', $rest)) { $input['external_system'] = $rest['external_system']; unset($rest['external_system']); } if (array_key_exists('external_reference_id', $rest)) { $input['external_reference_id'] = $rest['external_reference_id']; unset($rest['external_reference_id']); } if (array_key_exists('query', $rest)) { $input['query'] = $rest['query']; unset($rest['query']); } if (array_key_exists('return_id', $rest)) { $input['return_id'] = $rest['return_id']; unset($rest['return_id']); } if (array_key_exists('handed_off_after', $rest)) { $input['handed_off_after'] = $rest['handed_off_after']; unset($rest['handed_off_after']); } if (array_key_exists('handed_off_before', $rest)) { $input['handed_off_before'] = $rest['handed_off_before']; unset($rest['handed_off_before']); } if (array_key_exists('created_after', $rest)) { $input['created_after'] = $rest['created_after']; unset($rest['created_after']); } if (array_key_exists('created_before', $rest)) { $input['created_before'] = $rest['created_before']; unset($rest['created_before']); } if (array_key_exists('X-Request-Id', $rest)) { $input['X-Request-Id'] = $rest['X-Request-Id']; unset($rest['X-Request-Id']); } if (array_key_exists('Flint-Version', $rest)) { $input['Flint-Version'] = $rest['Flint-Version']; unset($rest['Flint-Version']); } foreach ($rest as $name => $value) { if (array_key_exists($name, $input)) throw new SdkError('validation', 'Path values belong in positional arguments', 'not_sent'); $input[$name] = $value; } return $this->runtime->items('listShipments', $input instanceof ShipmentsListInput ? $input->toInputArray() : (new ShipmentsListInput($input))->toInputArray(), $options); }
    /** Updates shipment metadata and caller-owned external references. Shipment status is derived from package statuses and cannot be patched directly. expected_version is optional and rejects a stale resource version when supplied.
     * @param array<array-key, mixed>|Model $params Flat body fields and query/header parameters; path arguments follow URL order.
     * @return UpdateShipmentResult
     */
    public function update(string|Model $shipment_id, array|Model $params, ?RequestOptions $options = null): UpdateShipmentResult { $input = ['shipment_id' => $shipment_id]; $params = $params instanceof Model ? $params->toInputArray() : $params; $rest = $params ?? []; if ($rest && array_is_list($rest)) throw new SdkError('validation', 'Expected associative params', 'not_sent'); if (array_key_exists('Idempotency-Key', $rest)) { $input['Idempotency-Key'] = $rest['Idempotency-Key']; unset($rest['Idempotency-Key']); } if (array_key_exists('X-Request-Id', $rest)) { $input['X-Request-Id'] = $rest['X-Request-Id']; unset($rest['X-Request-Id']); } if (array_key_exists('Flint-Version', $rest)) { $input['Flint-Version'] = $rest['Flint-Version']; unset($rest['Flint-Version']); } if (true) $input['body'] = (object) $rest; return SdkResponse::payload($this->runtime->request('updateShipment', $input instanceof ShipmentsUpdateInput ? $input->toInputArray() : (new ShipmentsUpdateInput($input))->toInputArray(), $options), ['data']); }
    /** @return SdkResponse<ShipmentsUpdateResponse200> */
    public function updateWithResponse(string|Model $shipment_id, array|Model $params, ?RequestOptions $options = null): SdkResponse { $input = ['shipment_id' => $shipment_id]; $params = $params instanceof Model ? $params->toInputArray() : $params; $rest = $params ?? []; if ($rest && array_is_list($rest)) throw new SdkError('validation', 'Expected associative params', 'not_sent'); if (array_key_exists('Idempotency-Key', $rest)) { $input['Idempotency-Key'] = $rest['Idempotency-Key']; unset($rest['Idempotency-Key']); } if (array_key_exists('X-Request-Id', $rest)) { $input['X-Request-Id'] = $rest['X-Request-Id']; unset($rest['X-Request-Id']); } if (array_key_exists('Flint-Version', $rest)) { $input['Flint-Version'] = $rest['Flint-Version']; unset($rest['Flint-Version']); } if (true) $input['body'] = (object) $rest; $result = $this->runtime->request('updateShipment', $input instanceof ShipmentsUpdateInput ? $input->toInputArray() : (new ShipmentsUpdateInput($input))->toInputArray(), $options); return new SdkResponse($result->data, $result->meta, $result->raw); }
    /** Voids a shipment before carrier handoff and voids all child packages that have not shipped. The action appends timeline events for the shipment and affected packages. expected_version is optional and rejects a stale resource version when supplied.
     * @param array<array-key, mixed>|Model|null $params Flat body fields and query/header parameters; path arguments follow URL order.
     * @return VoidShipmentResult
     */
    public function voidResource(string|Model $shipment_id, array|Model|null $params = null, ?RequestOptions $options = null): VoidShipmentResult { $input = ['shipment_id' => $shipment_id]; $params = $params instanceof Model ? $params->toInputArray() : $params; $rest = $params ?? []; if ($rest && array_is_list($rest)) throw new SdkError('validation', 'Expected associative params', 'not_sent'); if (array_key_exists('Idempotency-Key', $rest)) { $input['Idempotency-Key'] = $rest['Idempotency-Key']; unset($rest['Idempotency-Key']); } if (array_key_exists('X-Request-Id', $rest)) { $input['X-Request-Id'] = $rest['X-Request-Id']; unset($rest['X-Request-Id']); } if (array_key_exists('Flint-Version', $rest)) { $input['Flint-Version'] = $rest['Flint-Version']; unset($rest['Flint-Version']); } if ($params !== null && (!$params || $rest)) $input['body'] = (object) $rest; return SdkResponse::payload($this->runtime->request('voidShipment', $input instanceof ShipmentsVoidResourceInput ? $input->toInputArray() : (new ShipmentsVoidResourceInput($input))->toInputArray(), $options), ['data']); }
    /** @return SdkResponse<ShipmentsVoidResourceResponse200> */
    public function voidResourceWithResponse(string|Model $shipment_id, array|Model|null $params = null, ?RequestOptions $options = null): SdkResponse { $input = ['shipment_id' => $shipment_id]; $params = $params instanceof Model ? $params->toInputArray() : $params; $rest = $params ?? []; if ($rest && array_is_list($rest)) throw new SdkError('validation', 'Expected associative params', 'not_sent'); if (array_key_exists('Idempotency-Key', $rest)) { $input['Idempotency-Key'] = $rest['Idempotency-Key']; unset($rest['Idempotency-Key']); } if (array_key_exists('X-Request-Id', $rest)) { $input['X-Request-Id'] = $rest['X-Request-Id']; unset($rest['X-Request-Id']); } if (array_key_exists('Flint-Version', $rest)) { $input['Flint-Version'] = $rest['Flint-Version']; unset($rest['Flint-Version']); } if ($params !== null && (!$params || $rest)) $input['body'] = (object) $rest; $result = $this->runtime->request('voidShipment', $input instanceof ShipmentsVoidResourceInput ? $input->toInputArray() : (new ShipmentsVoidResourceInput($input))->toInputArray(), $options); return new SdkResponse($result->data, $result->meta, $result->raw); }
}
