<?php
declare(strict_types=1);
namespace Flint;
final class SubscriptionDeliveryMigrationsResource {
    public function __construct(private readonly Runtime $runtime) {}
    /** Each subscription is previewed before its delivery method changes. Progress and per-subscription failures remain available after completion.
     * @param array<array-key, mixed>|Model $params Flat body fields and query/header parameters; path arguments follow URL order.
     * @return SubscriptionDeliveryMigration
     */
    public function create(array|Model $params, ?RequestOptions $options = null): SubscriptionDeliveryMigration { $input = []; $params = $params instanceof Model ? $params->toInputArray() : $params; $rest = $params ?? []; if ($rest && array_is_list($rest)) throw new SdkError('validation', 'Expected associative params', 'not_sent'); if (array_key_exists('Idempotency-Key', $rest)) { $input['Idempotency-Key'] = $rest['Idempotency-Key']; unset($rest['Idempotency-Key']); } if (array_key_exists('Flint-Version', $rest)) { $input['Flint-Version'] = $rest['Flint-Version']; unset($rest['Flint-Version']); } if (true) $input['body'] = (object) $rest; return SdkResponse::payload($this->runtime->request('createSubscriptionDeliveryMigration', $input instanceof SubscriptionDeliveryMigrationsCreateInput ? $input->toInputArray() : (new SubscriptionDeliveryMigrationsCreateInput($input))->toInputArray(), $options), ['data']); }
    /** @return SdkResponse<SubscriptionDeliveryMigrationsCreateResponse202> */
    public function createWithResponse(array|Model $params, ?RequestOptions $options = null): SdkResponse { $input = []; $params = $params instanceof Model ? $params->toInputArray() : $params; $rest = $params ?? []; if ($rest && array_is_list($rest)) throw new SdkError('validation', 'Expected associative params', 'not_sent'); if (array_key_exists('Idempotency-Key', $rest)) { $input['Idempotency-Key'] = $rest['Idempotency-Key']; unset($rest['Idempotency-Key']); } if (array_key_exists('Flint-Version', $rest)) { $input['Flint-Version'] = $rest['Flint-Version']; unset($rest['Flint-Version']); } if (true) $input['body'] = (object) $rest; $result = $this->runtime->request('createSubscriptionDeliveryMigration', $input instanceof SubscriptionDeliveryMigrationsCreateInput ? $input->toInputArray() : (new SubscriptionDeliveryMigrationsCreateInput($input))->toInputArray(), $options); return new SdkResponse($result->data, $result->meta, $result->raw); }
    /** Each subscription is previewed before its delivery method changes. Progress and per-subscription failures remain available after completion.
     * @param array<array-key, mixed>|Model|null $params Flat body fields and query/header parameters; path arguments follow URL order.
     * @return SubscriptionDeliveryMigration
     */
    public function get(string|Model $subscription_delivery_migration_id, array|Model|null $params = null, ?RequestOptions $options = null): SubscriptionDeliveryMigration { $input = ['subscription_delivery_migration_id' => $subscription_delivery_migration_id]; $params = $params instanceof Model ? $params->toInputArray() : $params; $rest = $params ?? []; if ($rest && array_is_list($rest)) throw new SdkError('validation', 'Expected associative params', 'not_sent'); if (array_key_exists('Flint-Version', $rest)) { $input['Flint-Version'] = $rest['Flint-Version']; unset($rest['Flint-Version']); } foreach ($rest as $name => $value) { if (array_key_exists($name, $input)) throw new SdkError('validation', 'Path values belong in positional arguments', 'not_sent'); $input[$name] = $value; } return SdkResponse::payload($this->runtime->request('getSubscriptionDeliveryMigration', $input instanceof SubscriptionDeliveryMigrationsGetInput ? $input->toInputArray() : (new SubscriptionDeliveryMigrationsGetInput($input))->toInputArray(), $options), ['data']); }
    /** @return SdkResponse<SubscriptionDeliveryMigrationsGetResponse200> */
    public function getWithResponse(string|Model $subscription_delivery_migration_id, array|Model|null $params = null, ?RequestOptions $options = null): SdkResponse { $input = ['subscription_delivery_migration_id' => $subscription_delivery_migration_id]; $params = $params instanceof Model ? $params->toInputArray() : $params; $rest = $params ?? []; if ($rest && array_is_list($rest)) throw new SdkError('validation', 'Expected associative params', 'not_sent'); if (array_key_exists('Flint-Version', $rest)) { $input['Flint-Version'] = $rest['Flint-Version']; unset($rest['Flint-Version']); } foreach ($rest as $name => $value) { if (array_key_exists($name, $input)) throw new SdkError('validation', 'Path values belong in positional arguments', 'not_sent'); $input[$name] = $value; } $result = $this->runtime->request('getSubscriptionDeliveryMigration', $input instanceof SubscriptionDeliveryMigrationsGetInput ? $input->toInputArray() : (new SubscriptionDeliveryMigrationsGetInput($input))->toInputArray(), $options); return new SdkResponse($result->data, $result->meta, $result->raw); }
    /** Each subscription is previewed before its delivery method changes. Progress and per-subscription failures remain available after completion.
     * @param array<array-key, mixed>|Model|null $params Flat body fields and query/header parameters; path arguments follow URL order.
     * @return SubscriptionDeliveryMigrationsListFailuresResponse200
     */
    public function listFailures(string|Model $subscription_delivery_migration_id, array|Model|null $params = null, ?RequestOptions $options = null): SubscriptionDeliveryMigrationsListFailuresResponse200 { $input = ['subscription_delivery_migration_id' => $subscription_delivery_migration_id]; $params = $params instanceof Model ? $params->toInputArray() : $params; $rest = $params ?? []; if ($rest && array_is_list($rest)) throw new SdkError('validation', 'Expected associative params', 'not_sent'); if (array_key_exists('page_size', $rest)) { $input['page_size'] = $rest['page_size']; unset($rest['page_size']); } if (array_key_exists('page_token', $rest)) { $input['page_token'] = $rest['page_token']; unset($rest['page_token']); } if (array_key_exists('reason', $rest)) { $input['reason'] = $rest['reason']; unset($rest['reason']); } if (array_key_exists('Flint-Version', $rest)) { $input['Flint-Version'] = $rest['Flint-Version']; unset($rest['Flint-Version']); } foreach ($rest as $name => $value) { if (array_key_exists($name, $input)) throw new SdkError('validation', 'Path values belong in positional arguments', 'not_sent'); $input[$name] = $value; } return SdkResponse::payload($this->runtime->request('listSubscriptionDeliveryMigrationFailures', $input instanceof SubscriptionDeliveryMigrationsListFailuresInput ? $input->toInputArray() : (new SubscriptionDeliveryMigrationsListFailuresInput($input))->toInputArray(), $options), []); }
    /** @return SdkResponse<SubscriptionDeliveryMigrationsListFailuresResponse200> */
    public function listFailuresWithResponse(string|Model $subscription_delivery_migration_id, array|Model|null $params = null, ?RequestOptions $options = null): SdkResponse { $input = ['subscription_delivery_migration_id' => $subscription_delivery_migration_id]; $params = $params instanceof Model ? $params->toInputArray() : $params; $rest = $params ?? []; if ($rest && array_is_list($rest)) throw new SdkError('validation', 'Expected associative params', 'not_sent'); if (array_key_exists('page_size', $rest)) { $input['page_size'] = $rest['page_size']; unset($rest['page_size']); } if (array_key_exists('page_token', $rest)) { $input['page_token'] = $rest['page_token']; unset($rest['page_token']); } if (array_key_exists('reason', $rest)) { $input['reason'] = $rest['reason']; unset($rest['reason']); } if (array_key_exists('Flint-Version', $rest)) { $input['Flint-Version'] = $rest['Flint-Version']; unset($rest['Flint-Version']); } foreach ($rest as $name => $value) { if (array_key_exists($name, $input)) throw new SdkError('validation', 'Path values belong in positional arguments', 'not_sent'); $input[$name] = $value; } $result = $this->runtime->request('listSubscriptionDeliveryMigrationFailures', $input instanceof SubscriptionDeliveryMigrationsListFailuresInput ? $input->toInputArray() : (new SubscriptionDeliveryMigrationsListFailuresInput($input))->toInputArray(), $options); return new SdkResponse($result->data, $result->meta, $result->raw); }
    /** @return \Generator<int, SubscriptionDeliveryMigrationsListFailuresResponse200> */
    public function listFailuresPages(string|Model $subscription_delivery_migration_id, array|Model|null $params = null, ?RequestOptions $options = null): \Generator { $input = ['subscription_delivery_migration_id' => $subscription_delivery_migration_id]; $params = $params instanceof Model ? $params->toInputArray() : $params; $rest = $params ?? []; if ($rest && array_is_list($rest)) throw new SdkError('validation', 'Expected associative params', 'not_sent'); if (array_key_exists('page_size', $rest)) { $input['page_size'] = $rest['page_size']; unset($rest['page_size']); } if (array_key_exists('page_token', $rest)) { $input['page_token'] = $rest['page_token']; unset($rest['page_token']); } if (array_key_exists('reason', $rest)) { $input['reason'] = $rest['reason']; unset($rest['reason']); } if (array_key_exists('Flint-Version', $rest)) { $input['Flint-Version'] = $rest['Flint-Version']; unset($rest['Flint-Version']); } foreach ($rest as $name => $value) { if (array_key_exists($name, $input)) throw new SdkError('validation', 'Path values belong in positional arguments', 'not_sent'); $input[$name] = $value; } return SdkResponse::payloadPages($this->runtime->pages('listSubscriptionDeliveryMigrationFailures', $input instanceof SubscriptionDeliveryMigrationsListFailuresInput ? $input->toInputArray() : (new SubscriptionDeliveryMigrationsListFailuresInput($input))->toInputArray(), $options), []); }
    /** @return \Generator<int, SdkResponse<SubscriptionDeliveryMigrationsListFailuresResponse200>> */
    public function listFailuresPagesWithResponse(string|Model $subscription_delivery_migration_id, array|Model|null $params = null, ?RequestOptions $options = null): \Generator { $input = ['subscription_delivery_migration_id' => $subscription_delivery_migration_id]; $params = $params instanceof Model ? $params->toInputArray() : $params; $rest = $params ?? []; if ($rest && array_is_list($rest)) throw new SdkError('validation', 'Expected associative params', 'not_sent'); if (array_key_exists('page_size', $rest)) { $input['page_size'] = $rest['page_size']; unset($rest['page_size']); } if (array_key_exists('page_token', $rest)) { $input['page_token'] = $rest['page_token']; unset($rest['page_token']); } if (array_key_exists('reason', $rest)) { $input['reason'] = $rest['reason']; unset($rest['reason']); } if (array_key_exists('Flint-Version', $rest)) { $input['Flint-Version'] = $rest['Flint-Version']; unset($rest['Flint-Version']); } foreach ($rest as $name => $value) { if (array_key_exists($name, $input)) throw new SdkError('validation', 'Path values belong in positional arguments', 'not_sent'); $input[$name] = $value; } return SdkResponse::responsePages($this->runtime->pages('listSubscriptionDeliveryMigrationFailures', $input instanceof SubscriptionDeliveryMigrationsListFailuresInput ? $input->toInputArray() : (new SubscriptionDeliveryMigrationsListFailuresInput($input))->toInputArray(), $options)); }
    /** @return \Generator<int, SubscriptionDeliveryMigrationFailure> */
    public function listFailuresItems(string|Model $subscription_delivery_migration_id, array|Model|null $params = null, ?RequestOptions $options = null): \Generator { $input = ['subscription_delivery_migration_id' => $subscription_delivery_migration_id]; $params = $params instanceof Model ? $params->toInputArray() : $params; $rest = $params ?? []; if ($rest && array_is_list($rest)) throw new SdkError('validation', 'Expected associative params', 'not_sent'); if (array_key_exists('page_size', $rest)) { $input['page_size'] = $rest['page_size']; unset($rest['page_size']); } if (array_key_exists('page_token', $rest)) { $input['page_token'] = $rest['page_token']; unset($rest['page_token']); } if (array_key_exists('reason', $rest)) { $input['reason'] = $rest['reason']; unset($rest['reason']); } if (array_key_exists('Flint-Version', $rest)) { $input['Flint-Version'] = $rest['Flint-Version']; unset($rest['Flint-Version']); } foreach ($rest as $name => $value) { if (array_key_exists($name, $input)) throw new SdkError('validation', 'Path values belong in positional arguments', 'not_sent'); $input[$name] = $value; } return $this->runtime->items('listSubscriptionDeliveryMigrationFailures', $input instanceof SubscriptionDeliveryMigrationsListFailuresInput ? $input->toInputArray() : (new SubscriptionDeliveryMigrationsListFailuresInput($input))->toInputArray(), $options); }
    /** Each subscription is previewed before its delivery method changes. Progress and per-subscription failures remain available after completion.
     * @param array<array-key, mixed>|Model|null $params Flat body fields and query/header parameters; path arguments follow URL order.
     * @return SubscriptionDeliveryMigrationsListResponse200
     */
    public function list(array|Model|null $params = null, ?RequestOptions $options = null): SubscriptionDeliveryMigrationsListResponse200 { $input = []; $params = $params instanceof Model ? $params->toInputArray() : $params; $rest = $params ?? []; if ($rest && array_is_list($rest)) throw new SdkError('validation', 'Expected associative params', 'not_sent'); if (array_key_exists('page_size', $rest)) { $input['page_size'] = $rest['page_size']; unset($rest['page_size']); } if (array_key_exists('page_token', $rest)) { $input['page_token'] = $rest['page_token']; unset($rest['page_token']); } if (array_key_exists('from_delivery_method_id', $rest)) { $input['from_delivery_method_id'] = $rest['from_delivery_method_id']; unset($rest['from_delivery_method_id']); } if (array_key_exists('status', $rest)) { $input['status'] = $rest['status']; unset($rest['status']); } if (array_key_exists('Flint-Version', $rest)) { $input['Flint-Version'] = $rest['Flint-Version']; unset($rest['Flint-Version']); } foreach ($rest as $name => $value) { if (array_key_exists($name, $input)) throw new SdkError('validation', 'Path values belong in positional arguments', 'not_sent'); $input[$name] = $value; } return SdkResponse::payload($this->runtime->request('listSubscriptionDeliveryMigrations', $input instanceof SubscriptionDeliveryMigrationsListInput ? $input->toInputArray() : (new SubscriptionDeliveryMigrationsListInput($input))->toInputArray(), $options), []); }
    /** @return SdkResponse<SubscriptionDeliveryMigrationsListResponse200> */
    public function listWithResponse(array|Model|null $params = null, ?RequestOptions $options = null): SdkResponse { $input = []; $params = $params instanceof Model ? $params->toInputArray() : $params; $rest = $params ?? []; if ($rest && array_is_list($rest)) throw new SdkError('validation', 'Expected associative params', 'not_sent'); if (array_key_exists('page_size', $rest)) { $input['page_size'] = $rest['page_size']; unset($rest['page_size']); } if (array_key_exists('page_token', $rest)) { $input['page_token'] = $rest['page_token']; unset($rest['page_token']); } if (array_key_exists('from_delivery_method_id', $rest)) { $input['from_delivery_method_id'] = $rest['from_delivery_method_id']; unset($rest['from_delivery_method_id']); } if (array_key_exists('status', $rest)) { $input['status'] = $rest['status']; unset($rest['status']); } if (array_key_exists('Flint-Version', $rest)) { $input['Flint-Version'] = $rest['Flint-Version']; unset($rest['Flint-Version']); } foreach ($rest as $name => $value) { if (array_key_exists($name, $input)) throw new SdkError('validation', 'Path values belong in positional arguments', 'not_sent'); $input[$name] = $value; } $result = $this->runtime->request('listSubscriptionDeliveryMigrations', $input instanceof SubscriptionDeliveryMigrationsListInput ? $input->toInputArray() : (new SubscriptionDeliveryMigrationsListInput($input))->toInputArray(), $options); return new SdkResponse($result->data, $result->meta, $result->raw); }
    /** @return \Generator<int, SubscriptionDeliveryMigrationsListResponse200> */
    public function listPages(array|Model|null $params = null, ?RequestOptions $options = null): \Generator { $input = []; $params = $params instanceof Model ? $params->toInputArray() : $params; $rest = $params ?? []; if ($rest && array_is_list($rest)) throw new SdkError('validation', 'Expected associative params', 'not_sent'); if (array_key_exists('page_size', $rest)) { $input['page_size'] = $rest['page_size']; unset($rest['page_size']); } if (array_key_exists('page_token', $rest)) { $input['page_token'] = $rest['page_token']; unset($rest['page_token']); } if (array_key_exists('from_delivery_method_id', $rest)) { $input['from_delivery_method_id'] = $rest['from_delivery_method_id']; unset($rest['from_delivery_method_id']); } if (array_key_exists('status', $rest)) { $input['status'] = $rest['status']; unset($rest['status']); } if (array_key_exists('Flint-Version', $rest)) { $input['Flint-Version'] = $rest['Flint-Version']; unset($rest['Flint-Version']); } foreach ($rest as $name => $value) { if (array_key_exists($name, $input)) throw new SdkError('validation', 'Path values belong in positional arguments', 'not_sent'); $input[$name] = $value; } return SdkResponse::payloadPages($this->runtime->pages('listSubscriptionDeliveryMigrations', $input instanceof SubscriptionDeliveryMigrationsListInput ? $input->toInputArray() : (new SubscriptionDeliveryMigrationsListInput($input))->toInputArray(), $options), []); }
    /** @return \Generator<int, SdkResponse<SubscriptionDeliveryMigrationsListResponse200>> */
    public function listPagesWithResponse(array|Model|null $params = null, ?RequestOptions $options = null): \Generator { $input = []; $params = $params instanceof Model ? $params->toInputArray() : $params; $rest = $params ?? []; if ($rest && array_is_list($rest)) throw new SdkError('validation', 'Expected associative params', 'not_sent'); if (array_key_exists('page_size', $rest)) { $input['page_size'] = $rest['page_size']; unset($rest['page_size']); } if (array_key_exists('page_token', $rest)) { $input['page_token'] = $rest['page_token']; unset($rest['page_token']); } if (array_key_exists('from_delivery_method_id', $rest)) { $input['from_delivery_method_id'] = $rest['from_delivery_method_id']; unset($rest['from_delivery_method_id']); } if (array_key_exists('status', $rest)) { $input['status'] = $rest['status']; unset($rest['status']); } if (array_key_exists('Flint-Version', $rest)) { $input['Flint-Version'] = $rest['Flint-Version']; unset($rest['Flint-Version']); } foreach ($rest as $name => $value) { if (array_key_exists($name, $input)) throw new SdkError('validation', 'Path values belong in positional arguments', 'not_sent'); $input[$name] = $value; } return SdkResponse::responsePages($this->runtime->pages('listSubscriptionDeliveryMigrations', $input instanceof SubscriptionDeliveryMigrationsListInput ? $input->toInputArray() : (new SubscriptionDeliveryMigrationsListInput($input))->toInputArray(), $options)); }
    /** @return \Generator<int, SubscriptionDeliveryMigration> */
    public function listItems(array|Model|null $params = null, ?RequestOptions $options = null): \Generator { $input = []; $params = $params instanceof Model ? $params->toInputArray() : $params; $rest = $params ?? []; if ($rest && array_is_list($rest)) throw new SdkError('validation', 'Expected associative params', 'not_sent'); if (array_key_exists('page_size', $rest)) { $input['page_size'] = $rest['page_size']; unset($rest['page_size']); } if (array_key_exists('page_token', $rest)) { $input['page_token'] = $rest['page_token']; unset($rest['page_token']); } if (array_key_exists('from_delivery_method_id', $rest)) { $input['from_delivery_method_id'] = $rest['from_delivery_method_id']; unset($rest['from_delivery_method_id']); } if (array_key_exists('status', $rest)) { $input['status'] = $rest['status']; unset($rest['status']); } if (array_key_exists('Flint-Version', $rest)) { $input['Flint-Version'] = $rest['Flint-Version']; unset($rest['Flint-Version']); } foreach ($rest as $name => $value) { if (array_key_exists($name, $input)) throw new SdkError('validation', 'Path values belong in positional arguments', 'not_sent'); $input[$name] = $value; } return $this->runtime->items('listSubscriptionDeliveryMigrations', $input instanceof SubscriptionDeliveryMigrationsListInput ? $input->toInputArray() : (new SubscriptionDeliveryMigrationsListInput($input))->toInputArray(), $options); }
}
