<?php
declare(strict_types=1);
namespace Flint;
final class WebhookEndpointsResource {
    public function __construct(private readonly Runtime $runtime) {}
    /** Creates a webhook endpoint and returns the signing secret once.
     * @param array<array-key, mixed>|Model $params Flat body fields and query/header parameters; path arguments follow URL order.
     * @return WebhookEndpoint
     */
    public function create(array|Model $params, ?RequestOptions $options = null): WebhookEndpoint { $input = []; $params = $params instanceof Model ? $params->toInputArray() : $params; $rest = $params ?? []; if ($rest && array_is_list($rest)) throw new SdkError('validation', 'Expected associative params', 'not_sent'); if (array_key_exists('Idempotency-Key', $rest)) { $input['Idempotency-Key'] = $rest['Idempotency-Key']; unset($rest['Idempotency-Key']); } if (array_key_exists('X-Request-Id', $rest)) { $input['X-Request-Id'] = $rest['X-Request-Id']; unset($rest['X-Request-Id']); } if (array_key_exists('Flint-Version', $rest)) { $input['Flint-Version'] = $rest['Flint-Version']; unset($rest['Flint-Version']); } if (true) $input['body'] = (object) $rest; return SdkResponse::payload($this->runtime->request('createWebhookEndpoint', $input instanceof WebhookEndpointsCreateInput ? $input->toInputArray() : (new WebhookEndpointsCreateInput($input))->toInputArray(), $options), ['data']); }
    /** @return SdkResponse<WebhookEndpointsCreateResponse201> */
    public function createWithResponse(array|Model $params, ?RequestOptions $options = null): SdkResponse { $input = []; $params = $params instanceof Model ? $params->toInputArray() : $params; $rest = $params ?? []; if ($rest && array_is_list($rest)) throw new SdkError('validation', 'Expected associative params', 'not_sent'); if (array_key_exists('Idempotency-Key', $rest)) { $input['Idempotency-Key'] = $rest['Idempotency-Key']; unset($rest['Idempotency-Key']); } if (array_key_exists('X-Request-Id', $rest)) { $input['X-Request-Id'] = $rest['X-Request-Id']; unset($rest['X-Request-Id']); } if (array_key_exists('Flint-Version', $rest)) { $input['Flint-Version'] = $rest['Flint-Version']; unset($rest['Flint-Version']); } if (true) $input['body'] = (object) $rest; $result = $this->runtime->request('createWebhookEndpoint', $input instanceof WebhookEndpointsCreateInput ? $input->toInputArray() : (new WebhookEndpointsCreateInput($input))->toInputArray(), $options); return new SdkResponse($result->data, $result->meta, $result->raw); }
    /** Creates and delivers a synthetic test webhook event to one active webhook endpoint. Safe to retry with the same Idempotency-Key.
     * @param array<array-key, mixed>|Model $params Flat body fields and query/header parameters; path arguments follow URL order.
     * @return WebhookDeliveryAction
     */
    public function createWebhookTestEvent(string|Model $webhook_endpoint_id, array|Model $params, ?RequestOptions $options = null): WebhookDeliveryAction { $input = ['webhook_endpoint_id' => $webhook_endpoint_id]; $params = $params instanceof Model ? $params->toInputArray() : $params; $rest = $params ?? []; if ($rest && array_is_list($rest)) throw new SdkError('validation', 'Expected associative params', 'not_sent'); if (array_key_exists('Idempotency-Key', $rest)) { $input['Idempotency-Key'] = $rest['Idempotency-Key']; unset($rest['Idempotency-Key']); } if (array_key_exists('Flint-Version', $rest)) { $input['Flint-Version'] = $rest['Flint-Version']; unset($rest['Flint-Version']); } if (true) $input['body'] = (object) $rest; return SdkResponse::payload($this->runtime->request('createWebhookTestEvent', $input instanceof WebhookEndpointsCreateWebhookTestEventInput ? $input->toInputArray() : (new WebhookEndpointsCreateWebhookTestEventInput($input))->toInputArray(), $options), ['data']); }
    /** @return SdkResponse<WebhookEndpointsCreateWebhookTestEventResponse201> */
    public function createWebhookTestEventWithResponse(string|Model $webhook_endpoint_id, array|Model $params, ?RequestOptions $options = null): SdkResponse { $input = ['webhook_endpoint_id' => $webhook_endpoint_id]; $params = $params instanceof Model ? $params->toInputArray() : $params; $rest = $params ?? []; if ($rest && array_is_list($rest)) throw new SdkError('validation', 'Expected associative params', 'not_sent'); if (array_key_exists('Idempotency-Key', $rest)) { $input['Idempotency-Key'] = $rest['Idempotency-Key']; unset($rest['Idempotency-Key']); } if (array_key_exists('Flint-Version', $rest)) { $input['Flint-Version'] = $rest['Flint-Version']; unset($rest['Flint-Version']); } if (true) $input['body'] = (object) $rest; $result = $this->runtime->request('createWebhookTestEvent', $input instanceof WebhookEndpointsCreateWebhookTestEventInput ? $input->toInputArray() : (new WebhookEndpointsCreateWebhookTestEventInput($input))->toInputArray(), $options); return new SdkResponse($result->data, $result->meta, $result->raw); }
    /** Marks a webhook endpoint as deleted so it no longer receives events.
     * @param array<array-key, mixed>|Model|null $params Flat body fields and query/header parameters; path arguments follow URL order.
     * @return ActionResult
     */
    public function remove(string|Model $webhook_endpoint_id, array|Model|null $params = null, ?RequestOptions $options = null): ActionResult { $input = ['webhook_endpoint_id' => $webhook_endpoint_id]; $params = $params instanceof Model ? $params->toInputArray() : $params; $rest = $params ?? []; if ($rest && array_is_list($rest)) throw new SdkError('validation', 'Expected associative params', 'not_sent'); if (array_key_exists('Idempotency-Key', $rest)) { $input['Idempotency-Key'] = $rest['Idempotency-Key']; unset($rest['Idempotency-Key']); } if (array_key_exists('X-Request-Id', $rest)) { $input['X-Request-Id'] = $rest['X-Request-Id']; unset($rest['X-Request-Id']); } if (array_key_exists('Flint-Version', $rest)) { $input['Flint-Version'] = $rest['Flint-Version']; unset($rest['Flint-Version']); } foreach ($rest as $name => $value) { if (array_key_exists($name, $input)) throw new SdkError('validation', 'Path values belong in positional arguments', 'not_sent'); $input[$name] = $value; } return SdkResponse::payload($this->runtime->request('deleteWebhookEndpoint', $input instanceof WebhookEndpointsRemoveInput ? $input->toInputArray() : (new WebhookEndpointsRemoveInput($input))->toInputArray(), $options), ['data']); }
    /** @return SdkResponse<WebhookEndpointsRemoveResponse200> */
    public function removeWithResponse(string|Model $webhook_endpoint_id, array|Model|null $params = null, ?RequestOptions $options = null): SdkResponse { $input = ['webhook_endpoint_id' => $webhook_endpoint_id]; $params = $params instanceof Model ? $params->toInputArray() : $params; $rest = $params ?? []; if ($rest && array_is_list($rest)) throw new SdkError('validation', 'Expected associative params', 'not_sent'); if (array_key_exists('Idempotency-Key', $rest)) { $input['Idempotency-Key'] = $rest['Idempotency-Key']; unset($rest['Idempotency-Key']); } if (array_key_exists('X-Request-Id', $rest)) { $input['X-Request-Id'] = $rest['X-Request-Id']; unset($rest['X-Request-Id']); } if (array_key_exists('Flint-Version', $rest)) { $input['Flint-Version'] = $rest['Flint-Version']; unset($rest['Flint-Version']); } foreach ($rest as $name => $value) { if (array_key_exists($name, $input)) throw new SdkError('validation', 'Path values belong in positional arguments', 'not_sent'); $input[$name] = $value; } $result = $this->runtime->request('deleteWebhookEndpoint', $input instanceof WebhookEndpointsRemoveInput ? $input->toInputArray() : (new WebhookEndpointsRemoveInput($input))->toInputArray(), $options); return new SdkResponse($result->data, $result->meta, $result->raw); }
    /** Returns a single webhook endpoint by ID. The signing secret is omitted after creation.
     * @param array<array-key, mixed>|Model|null $params Flat body fields and query/header parameters; path arguments follow URL order.
     * @return WebhookEndpoint
     */
    public function get(string|Model $webhook_endpoint_id, array|Model|null $params = null, ?RequestOptions $options = null): WebhookEndpoint { $input = ['webhook_endpoint_id' => $webhook_endpoint_id]; $params = $params instanceof Model ? $params->toInputArray() : $params; $rest = $params ?? []; if ($rest && array_is_list($rest)) throw new SdkError('validation', 'Expected associative params', 'not_sent'); if (array_key_exists('Flint-Version', $rest)) { $input['Flint-Version'] = $rest['Flint-Version']; unset($rest['Flint-Version']); } foreach ($rest as $name => $value) { if (array_key_exists($name, $input)) throw new SdkError('validation', 'Path values belong in positional arguments', 'not_sent'); $input[$name] = $value; } return SdkResponse::payload($this->runtime->request('getWebhookEndpoint', $input instanceof WebhookEndpointsGetInput ? $input->toInputArray() : (new WebhookEndpointsGetInput($input))->toInputArray(), $options), ['data']); }
    /** @return SdkResponse<WebhookEndpointsGetResponse200> */
    public function getWithResponse(string|Model $webhook_endpoint_id, array|Model|null $params = null, ?RequestOptions $options = null): SdkResponse { $input = ['webhook_endpoint_id' => $webhook_endpoint_id]; $params = $params instanceof Model ? $params->toInputArray() : $params; $rest = $params ?? []; if ($rest && array_is_list($rest)) throw new SdkError('validation', 'Expected associative params', 'not_sent'); if (array_key_exists('Flint-Version', $rest)) { $input['Flint-Version'] = $rest['Flint-Version']; unset($rest['Flint-Version']); } foreach ($rest as $name => $value) { if (array_key_exists($name, $input)) throw new SdkError('validation', 'Path values belong in positional arguments', 'not_sent'); $input[$name] = $value; } $result = $this->runtime->request('getWebhookEndpoint', $input instanceof WebhookEndpointsGetInput ? $input->toInputArray() : (new WebhookEndpointsGetInput($input))->toInputArray(), $options); return new SdkResponse($result->data, $result->meta, $result->raw); }
    /** Returns a page of webhook endpoints for the authenticated merchant.
     * @param array<array-key, mixed>|Model|null $params Flat body fields and query/header parameters; path arguments follow URL order.
     * @return WebhookEndpointsListResponse200
     */
    public function list(array|Model|null $params = null, ?RequestOptions $options = null): WebhookEndpointsListResponse200 { $input = []; $params = $params instanceof Model ? $params->toInputArray() : $params; $rest = $params ?? []; if ($rest && array_is_list($rest)) throw new SdkError('validation', 'Expected associative params', 'not_sent'); if (array_key_exists('page_size', $rest)) { $input['page_size'] = $rest['page_size']; unset($rest['page_size']); } if (array_key_exists('page_token', $rest)) { $input['page_token'] = $rest['page_token']; unset($rest['page_token']); } if (array_key_exists('event_sources', $rest)) { $input['event_sources'] = $rest['event_sources']; unset($rest['event_sources']); } if (array_key_exists('partner_app_id', $rest)) { $input['partner_app_id'] = $rest['partner_app_id']; unset($rest['partner_app_id']); } if (array_key_exists('Flint-Version', $rest)) { $input['Flint-Version'] = $rest['Flint-Version']; unset($rest['Flint-Version']); } foreach ($rest as $name => $value) { if (array_key_exists($name, $input)) throw new SdkError('validation', 'Path values belong in positional arguments', 'not_sent'); $input[$name] = $value; } return SdkResponse::payload($this->runtime->request('listWebhookEndpoints', $input instanceof WebhookEndpointsListInput ? $input->toInputArray() : (new WebhookEndpointsListInput($input))->toInputArray(), $options), []); }
    /** @return SdkResponse<WebhookEndpointsListResponse200> */
    public function listWithResponse(array|Model|null $params = null, ?RequestOptions $options = null): SdkResponse { $input = []; $params = $params instanceof Model ? $params->toInputArray() : $params; $rest = $params ?? []; if ($rest && array_is_list($rest)) throw new SdkError('validation', 'Expected associative params', 'not_sent'); if (array_key_exists('page_size', $rest)) { $input['page_size'] = $rest['page_size']; unset($rest['page_size']); } if (array_key_exists('page_token', $rest)) { $input['page_token'] = $rest['page_token']; unset($rest['page_token']); } if (array_key_exists('event_sources', $rest)) { $input['event_sources'] = $rest['event_sources']; unset($rest['event_sources']); } if (array_key_exists('partner_app_id', $rest)) { $input['partner_app_id'] = $rest['partner_app_id']; unset($rest['partner_app_id']); } if (array_key_exists('Flint-Version', $rest)) { $input['Flint-Version'] = $rest['Flint-Version']; unset($rest['Flint-Version']); } foreach ($rest as $name => $value) { if (array_key_exists($name, $input)) throw new SdkError('validation', 'Path values belong in positional arguments', 'not_sent'); $input[$name] = $value; } $result = $this->runtime->request('listWebhookEndpoints', $input instanceof WebhookEndpointsListInput ? $input->toInputArray() : (new WebhookEndpointsListInput($input))->toInputArray(), $options); return new SdkResponse($result->data, $result->meta, $result->raw); }
    /** @return \Generator<int, WebhookEndpointsListResponse200> */
    public function listPages(array|Model|null $params = null, ?RequestOptions $options = null): \Generator { $input = []; $params = $params instanceof Model ? $params->toInputArray() : $params; $rest = $params ?? []; if ($rest && array_is_list($rest)) throw new SdkError('validation', 'Expected associative params', 'not_sent'); if (array_key_exists('page_size', $rest)) { $input['page_size'] = $rest['page_size']; unset($rest['page_size']); } if (array_key_exists('page_token', $rest)) { $input['page_token'] = $rest['page_token']; unset($rest['page_token']); } if (array_key_exists('event_sources', $rest)) { $input['event_sources'] = $rest['event_sources']; unset($rest['event_sources']); } if (array_key_exists('partner_app_id', $rest)) { $input['partner_app_id'] = $rest['partner_app_id']; unset($rest['partner_app_id']); } if (array_key_exists('Flint-Version', $rest)) { $input['Flint-Version'] = $rest['Flint-Version']; unset($rest['Flint-Version']); } foreach ($rest as $name => $value) { if (array_key_exists($name, $input)) throw new SdkError('validation', 'Path values belong in positional arguments', 'not_sent'); $input[$name] = $value; } return SdkResponse::payloadPages($this->runtime->pages('listWebhookEndpoints', $input instanceof WebhookEndpointsListInput ? $input->toInputArray() : (new WebhookEndpointsListInput($input))->toInputArray(), $options), []); }
    /** @return \Generator<int, SdkResponse<WebhookEndpointsListResponse200>> */
    public function listPagesWithResponse(array|Model|null $params = null, ?RequestOptions $options = null): \Generator { $input = []; $params = $params instanceof Model ? $params->toInputArray() : $params; $rest = $params ?? []; if ($rest && array_is_list($rest)) throw new SdkError('validation', 'Expected associative params', 'not_sent'); if (array_key_exists('page_size', $rest)) { $input['page_size'] = $rest['page_size']; unset($rest['page_size']); } if (array_key_exists('page_token', $rest)) { $input['page_token'] = $rest['page_token']; unset($rest['page_token']); } if (array_key_exists('event_sources', $rest)) { $input['event_sources'] = $rest['event_sources']; unset($rest['event_sources']); } if (array_key_exists('partner_app_id', $rest)) { $input['partner_app_id'] = $rest['partner_app_id']; unset($rest['partner_app_id']); } if (array_key_exists('Flint-Version', $rest)) { $input['Flint-Version'] = $rest['Flint-Version']; unset($rest['Flint-Version']); } foreach ($rest as $name => $value) { if (array_key_exists($name, $input)) throw new SdkError('validation', 'Path values belong in positional arguments', 'not_sent'); $input[$name] = $value; } return SdkResponse::responsePages($this->runtime->pages('listWebhookEndpoints', $input instanceof WebhookEndpointsListInput ? $input->toInputArray() : (new WebhookEndpointsListInput($input))->toInputArray(), $options)); }
    /** @return \Generator<int, WebhookEndpoint> */
    public function listItems(array|Model|null $params = null, ?RequestOptions $options = null): \Generator { $input = []; $params = $params instanceof Model ? $params->toInputArray() : $params; $rest = $params ?? []; if ($rest && array_is_list($rest)) throw new SdkError('validation', 'Expected associative params', 'not_sent'); if (array_key_exists('page_size', $rest)) { $input['page_size'] = $rest['page_size']; unset($rest['page_size']); } if (array_key_exists('page_token', $rest)) { $input['page_token'] = $rest['page_token']; unset($rest['page_token']); } if (array_key_exists('event_sources', $rest)) { $input['event_sources'] = $rest['event_sources']; unset($rest['event_sources']); } if (array_key_exists('partner_app_id', $rest)) { $input['partner_app_id'] = $rest['partner_app_id']; unset($rest['partner_app_id']); } if (array_key_exists('Flint-Version', $rest)) { $input['Flint-Version'] = $rest['Flint-Version']; unset($rest['Flint-Version']); } foreach ($rest as $name => $value) { if (array_key_exists($name, $input)) throw new SdkError('validation', 'Path values belong in positional arguments', 'not_sent'); $input[$name] = $value; } return $this->runtime->items('listWebhookEndpoints', $input instanceof WebhookEndpointsListInput ? $input->toInputArray() : (new WebhookEndpointsListInput($input))->toInputArray(), $options); }
    /** Rotates the signing secret for a webhook endpoint and returns the new secret once.
     * @param array<array-key, mixed>|Model|null $params Flat body fields and query/header parameters; path arguments follow URL order.
     * @return WebhookSecret
     */
    public function rotateWebhookSecret(string|Model $webhook_endpoint_id, array|Model|null $params = null, ?RequestOptions $options = null): WebhookSecret { $input = ['webhook_endpoint_id' => $webhook_endpoint_id]; $params = $params instanceof Model ? $params->toInputArray() : $params; $rest = $params ?? []; if ($rest && array_is_list($rest)) throw new SdkError('validation', 'Expected associative params', 'not_sent'); if (array_key_exists('Idempotency-Key', $rest)) { $input['Idempotency-Key'] = $rest['Idempotency-Key']; unset($rest['Idempotency-Key']); } if (array_key_exists('X-Request-Id', $rest)) { $input['X-Request-Id'] = $rest['X-Request-Id']; unset($rest['X-Request-Id']); } if (array_key_exists('Flint-Version', $rest)) { $input['Flint-Version'] = $rest['Flint-Version']; unset($rest['Flint-Version']); } foreach ($rest as $name => $value) { if (array_key_exists($name, $input)) throw new SdkError('validation', 'Path values belong in positional arguments', 'not_sent'); $input[$name] = $value; } return SdkResponse::payload($this->runtime->request('rotateWebhookSecret', $input instanceof WebhookEndpointsRotateWebhookSecretInput ? $input->toInputArray() : (new WebhookEndpointsRotateWebhookSecretInput($input))->toInputArray(), $options), ['data']); }
    /** @return SdkResponse<WebhookEndpointsRotateWebhookSecretResponse200> */
    public function rotateWebhookSecretWithResponse(string|Model $webhook_endpoint_id, array|Model|null $params = null, ?RequestOptions $options = null): SdkResponse { $input = ['webhook_endpoint_id' => $webhook_endpoint_id]; $params = $params instanceof Model ? $params->toInputArray() : $params; $rest = $params ?? []; if ($rest && array_is_list($rest)) throw new SdkError('validation', 'Expected associative params', 'not_sent'); if (array_key_exists('Idempotency-Key', $rest)) { $input['Idempotency-Key'] = $rest['Idempotency-Key']; unset($rest['Idempotency-Key']); } if (array_key_exists('X-Request-Id', $rest)) { $input['X-Request-Id'] = $rest['X-Request-Id']; unset($rest['X-Request-Id']); } if (array_key_exists('Flint-Version', $rest)) { $input['Flint-Version'] = $rest['Flint-Version']; unset($rest['Flint-Version']); } foreach ($rest as $name => $value) { if (array_key_exists($name, $input)) throw new SdkError('validation', 'Path values belong in positional arguments', 'not_sent'); $input[$name] = $value; } $result = $this->runtime->request('rotateWebhookSecret', $input instanceof WebhookEndpointsRotateWebhookSecretInput ? $input->toInputArray() : (new WebhookEndpointsRotateWebhookSecretInput($input))->toInputArray(), $options); return new SdkResponse($result->data, $result->meta, $result->raw); }
    /** Updates the mutable fields on a webhook endpoint.
     * @param array<array-key, mixed>|Model $params Flat body fields and query/header parameters; path arguments follow URL order.
     * @return WebhookEndpoint
     */
    public function update(string|Model $webhook_endpoint_id, array|Model $params, ?RequestOptions $options = null): WebhookEndpoint { $input = ['webhook_endpoint_id' => $webhook_endpoint_id]; $params = $params instanceof Model ? $params->toInputArray() : $params; $rest = $params ?? []; if ($rest && array_is_list($rest)) throw new SdkError('validation', 'Expected associative params', 'not_sent'); if (array_key_exists('Idempotency-Key', $rest)) { $input['Idempotency-Key'] = $rest['Idempotency-Key']; unset($rest['Idempotency-Key']); } if (array_key_exists('X-Request-Id', $rest)) { $input['X-Request-Id'] = $rest['X-Request-Id']; unset($rest['X-Request-Id']); } if (array_key_exists('Flint-Version', $rest)) { $input['Flint-Version'] = $rest['Flint-Version']; unset($rest['Flint-Version']); } if (true) $input['body'] = (object) $rest; return SdkResponse::payload($this->runtime->request('updateWebhookEndpoint', $input instanceof WebhookEndpointsUpdateInput ? $input->toInputArray() : (new WebhookEndpointsUpdateInput($input))->toInputArray(), $options), ['data']); }
    /** @return SdkResponse<WebhookEndpointsUpdateResponse200> */
    public function updateWithResponse(string|Model $webhook_endpoint_id, array|Model $params, ?RequestOptions $options = null): SdkResponse { $input = ['webhook_endpoint_id' => $webhook_endpoint_id]; $params = $params instanceof Model ? $params->toInputArray() : $params; $rest = $params ?? []; if ($rest && array_is_list($rest)) throw new SdkError('validation', 'Expected associative params', 'not_sent'); if (array_key_exists('Idempotency-Key', $rest)) { $input['Idempotency-Key'] = $rest['Idempotency-Key']; unset($rest['Idempotency-Key']); } if (array_key_exists('X-Request-Id', $rest)) { $input['X-Request-Id'] = $rest['X-Request-Id']; unset($rest['X-Request-Id']); } if (array_key_exists('Flint-Version', $rest)) { $input['Flint-Version'] = $rest['Flint-Version']; unset($rest['Flint-Version']); } if (true) $input['body'] = (object) $rest; $result = $this->runtime->request('updateWebhookEndpoint', $input instanceof WebhookEndpointsUpdateInput ? $input->toInputArray() : (new WebhookEndpointsUpdateInput($input))->toInputArray(), $options); return new SdkResponse($result->data, $result->meta, $result->raw); }
}
