
import type { CheckoutCustomerVerificationConfirmationResponse } from './CheckoutCustomerVerificationConfirmationResponse.js';

export type CheckoutSessionsConfirmCustomerVerificationResponse = CheckoutCustomerVerificationConfirmationResponse;
