
import type { CreateDeliveryFulfillmentDetailsInput } from './CreateDeliveryFulfillmentDetailsInput.js';
import type { CreateDigitalFulfillmentDetailsInput } from './CreateDigitalFulfillmentDetailsInput.js';
import type { CreatePickupFulfillmentDetailsInput } from './CreatePickupFulfillmentDetailsInput.js';
import type { CreateServiceFulfillmentDetailsInput } from './CreateServiceFulfillmentDetailsInput.js';
import type { FulfillmentLineItemRequestInput } from './FulfillmentLineItemRequestInput.js';
import type { FulfillmentPackagingRequestInput } from './FulfillmentPackagingRequestInput.js';
import type { FulfillmentRecipientInput } from './FulfillmentRecipientInput.js';

/** Provide at most one fulfillment details object: pickup_details, local_delivery_details, digital_details, or service_details. Shipment execution details belong to shipments and packages. */ export type CreateFulfillmentRequestInput = ({ "customer_id"?: string; "device_id"?: string; "digital_details"?: CreateDigitalFulfillmentDetailsInput; /** Caller-owned identifier for this resource in an external system. minLength: 1. maxLength: 255. */ "external_reference_id"?: string; /** minItems: 1. */ "line_items": Array<FulfillmentLineItemRequestInput>; "local_delivery_details"?: CreateDeliveryFulfillmentDetailsInput; "location_id"?: string; "metadata"?: Record<string, string>; "pickup_details"?: CreatePickupFulfillmentDetailsInput; "recipient"?: FulfillmentRecipientInput; "service_details"?: CreateServiceFulfillmentDetailsInput; /** Creates one outbound shipment and one package atomically with the fulfillment. packaging must be single_package. The package receives the full quantities of only the submitted line_items. Requires type shipment. Omission creates no shipment or package. Tracking does not mark the package shipped. Package tracking notifications are requested when buyer_notification_behavior is omitted; use suppress to prevent buyer messages from this creation. */ "shipment"?: FulfillmentPackagingRequestInput; "type": "shipment" | "pickup" | "local_delivery" | "digital" | "service"; }) & (((({ "shipment"?: never })) | ({ "type"?: "shipment"; }))) & (((({ "pickup_details"?: never }) & ({ "local_delivery_details"?: never }) & ({ "digital_details"?: never }) & ({ "service_details"?: never }))) | ({ "pickup_details": unknown; }) | ({ "local_delivery_details": unknown; }) | ({ "digital_details": unknown; }) | ({ "service_details": unknown; }));
