
import type { ExpandedPaymentIntentSummaryInput } from './ExpandedPaymentIntentSummaryInput.js';
import type { MoneyValueInput } from './MoneyValueInput.js';
import type { PricingAmountsInput } from './PricingAmountsInput.js';
import type { RefundInput } from './RefundInput.js';
import type { ReturnActorInput } from './ReturnActorInput.js';
import type { ReturnReplacementLineItemInput } from './ReturnReplacementLineItemInput.js';
import type { ReturnResolutionAdjustmentInput } from './ReturnResolutionAdjustmentInput.js';
import type { ReturnResolutionExecutionBlockerInput } from './ReturnResolutionExecutionBlockerInput.js';
import type { ReturnResolutionLineItemInput } from './ReturnResolutionLineItemInput.js';
import type { SettlementAmountsInput } from './SettlementAmountsInput.js';

export type ReturnResolutionInput = { "action_reason"?: "buyer_payment" | "buyer_selection" | "merchant_review" | "manual_release" | "linked_effect_retry" | "other"; "action_required_by"?: "buyer" | "merchant" | "integration"; "adjustments": Array<ReturnResolutionAdjustmentInput>; "buyer_payment_amount_money": MoneyValueInput; "buyer_refund_amount_money": MoneyValueInput; /** RFC3339 timestamp. Format: date-time. */ "canceled_at"?: string | globalThis.Date; /** RFC3339 timestamp. Format: date-time. */ "confirmed_at"?: string | globalThis.Date; "confirmed_by"?: ReturnActorInput; "corrects_return_resolution_id"?: string; /** RFC3339 timestamp. Format: date-time. */ "created_at": string | globalThis.Date; "created_by": ReturnActorInput; "credit_money": MoneyValueInput; "deduction_money": MoneyValueInput; "execution_blockers": Array<ReturnResolutionExecutionBlockerInput>; /** Caller-owned identifier for this resource in an external system. maxLength: 255. */ "external_reference_id"?: string; /** Reason code for a failed Return resolution, when available. */ "failure_code"?: string; /** Explanation of a failed Return resolution, when available. */ "failure_message"?: string; /** RFC3339 timestamp. Format: date-time. */ "fulfilled_at"?: string | globalThis.Date; "line_items": Array<ReturnResolutionLineItemInput>; "metadata": Record<string, string>; "payment_intent_ids": Array<string>; "payment_intents"?: Array<ExpandedPaymentIntentSummaryInput>; "pricing_basis"?: "original_price" | "current_price" | "merchant_agreed_price"; "refund_ids": Array<string>; "refunds"?: Array<RefundInput>; "replacement_line_items": Array<ReturnReplacementLineItemInput>; "replacement_order"?: (({ /** RFC3339 timestamp. Format: date-time. */ "created_at"?: string | globalThis.Date; "customer_id"?: string; "fulfillment_status"?: "not_fulfilled" | "partially_fulfilled" | "fulfilled" | "canceled" | "not_applicable" | "closed"; "order_id": string; "order_number"?: string; "payment_intent_ids"?: Array<string>; "payment_status": "unpaid" | "partially_paid" | "paid"; "pricing_amounts": PricingAmountsInput; "refund_status": "none" | "partially_refunded" | "refunded"; "settlement_amounts": SettlementAmountsInput; "status": "open" | "closed"; /** RFC3339 timestamp. Format: date-time. */ "updated_at"?: string | globalThis.Date; }) | (null)); "replacement_order_id"?: string; "replacement_total_money": MoneyValueInput; "resolution_type": "refund" | "exchange" | "replacement" | "no_monetary_action" | "correction"; "return_id": string; "return_policy_revision_id"?: string; "return_resolution_id": string; "returned_total_money": MoneyValueInput; "status": "proposed" | "pending" | "requires_action" | "partially_fulfilled" | "fulfilled" | "failed" | "canceled"; "supported_actions": Array<string>; /** RFC3339 timestamp. Format: date-time. */ "updated_at": string | globalThis.Date; /** Use an exact numeric string, not a floating-point number. Format: int64. minimum: 0. */ "version": string; };
