
import type { Webhook_subscription_activated_installed_merchants } from './Webhook_subscription_activated_installed_merchants.js';

export type Webhook_subscription_trial_ending_installed_merchants = Webhook_subscription_activated_installed_merchants;
