
import type { Webhook_delivery_location_set_activated_installed_merchants } from './Webhook_delivery_location_set_activated_installed_merchants.js';

export type Webhook_delivery_method_deactivated_installed_merchants = Webhook_delivery_location_set_activated_installed_merchants;
