
import type { Webhook_subscription_payment_retry_created_installed_merchants } from './Webhook_subscription_payment_retry_created_installed_merchants.js';

export type Webhook_subscription_payment_retry_succeeded_installed_merchants = Webhook_subscription_payment_retry_created_installed_merchants;
