
import type { Webhook_subscription_payment_retry_created_merchant } from './Webhook_subscription_payment_retry_created_merchant.js';

export type Webhook_subscription_payment_retry_failed_merchant = Webhook_subscription_payment_retry_created_merchant;
