import type { ServiceConfig } from "./types-generator";

/**
 * Generate the index.ts re-export file for the generated/ directory.
 */
export function generateRegistryIndex(configs: ServiceConfig[]): string {
  const lines: string[] = [];

  lines.push(`// Auto-generated by scripts/generate.ts — do not edit manually`);
  lines.push("");

  // Re-export common types
  lines.push(`export * from "./types/common";`);
  lines.push("");

  // Re-export each service's types and service class
  for (const config of configs) {
    const kebab = kebabCase(config.sdk);
    lines.push(`export * from "./types/${kebab}";`);
    lines.push(`export { ${config.entity}Service } from "./services/${kebab}";`);
  }

  lines.push("");
  return lines.join("\n");
}

/**
 * Generate the service registry that client.ts imports.
 */
export function generateServiceRegistry(configs: ServiceConfig[]): string {
  const lines: string[] = [];

  lines.push(`// Auto-generated by scripts/generate.ts — do not edit manually`);
  lines.push(`import type { RequestConfig } from "../services/base";`);

  for (const config of configs) {
    const kebab = kebabCase(config.sdk);
    lines.push(`import { ${config.entity}Service } from "./services/${kebab}";`);
  }

  lines.push("");
  lines.push(`export type ServiceInstances = {`);
  for (const config of configs) {
    lines.push(`  ${config.sdk}: ${config.entity}Service;`);
  }
  lines.push(`};`);
  lines.push("");

  lines.push(`export function createServices(config: RequestConfig): ServiceInstances {`);
  lines.push(`  return {`);
  for (const config of configs) {
    lines.push(`    ${config.sdk}: new ${config.entity}Service(config),`);
  }
  lines.push(`  };`);
  lines.push(`}`);
  lines.push("");

  // Re-export service classes for direct access
  for (const config of configs) {
    const kebab = kebabCase(config.sdk);
    lines.push(`export { ${config.entity}Service } from "./services/${kebab}";`);
  }
  lines.push("");

  return lines.join("\n");
}

function kebabCase(s: string): string {
  return s.replace(/([A-Z])/g, "-$1").toLowerCase().replace(/^-/, "");
}
